[Feature:Developer] Whitelisting Mime Types
Submitty/Submitty pull request #10003
Opened 2023-11-20 05:35 UTC by musaabimran

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2023-11-21 17:16 UTC, cjreed121 requested changes

2023-11-21 17:16 UTC, cjreed121 commented on mimetype.patch
> +diff --git a/site/app/controllers/MiscController.php b/site/app/controllers/MiscController.php
Don't commit the patch

2023-11-21 17:16 UTC, cjreed121 commented on site/app/controllers/MiscController.php
> +        if (in_array($mime_type, FileUtils::Allowed_Inline_Types)) {
Add `true` as a third argument to specify strict comparison. By default this is `false`.

2023-11-21 17:16 UTC, cjreed121 commented on site/app/controllers/MiscController.php
> +        elseif (in_array($mime_type, FileUtils::Allowed_Text_Types)) {
Same here

2023-11-21 17:16 UTC, cjreed121 commented on site/app/libraries/FileUtils.php
> +    const Allowed_Text_Types = [
const vars are usually preferred to be all caps

2024-06-20 16:13 UTC, micpap25 commented
I did some testing; all these filetypes work but I've found two separate issues that should be addressed (and probably need some discussion before addressing):
1. the course materials display was updated by this PR but the pop-out for viewing files in current gradable version was not, and that functions incorrectly when an octet stream or any other filetype that shouldn't be viewed inline is popped out in this way. Leading into:
2. Both course materials and current version views use another explicitly defined list of filetypes to choose which files may be popped out and viewed inline. I think these need to be removed and perhaps synched up with the allowed MIME types?
3. 
In other news, the MIME types for most files (even python, java, erlang, etc.) are just "text/html". I'm not certain why this is happening and it's not an issue on our end, it's how the files are interpreted.

2024-06-24 19:16 UTC, micpap25 commented
Putting this on draft until we fix the existing issues with the implementation of preventing pop-outs based on file extension.

2025-04-25 20:10 UTC, bmcutler commented
closing this PR as it needs significant work.
Related to issue #10618

2025-04-25 20:10 UTC, closed without merging