[Bugfix:InstructorUI] Restrict SQL-Toolbox textarea from resizing undesirably
Submitty/Submitty pull request #10016
Opened 2023-11-29 07:17 UTC by krishnachandran-u

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #10008 

The textarea in the SQL-Toolbox within the InstructorUI can expand beyond the width of its parent div tag, resulting in the textarea's width exceeding the total screen size.
![Screenshot from 2023-11-29 08-04-42 (1)](https://github.com/Submitty/Submitty/assets/129476971/69db88a4-de4c-46ff-ad62-218b0613ffde)
The textarea can also be truncated in both height and width, resulting in an undesirable and improper style.
![Screenshot from 2023-11-29 08-04-24](https://github.com/Submitty/Submitty/assets/129476971/6b30de9c-f2f5-42a0-8846-f08e3f131232)

### What is the new behavior?

Restricted the textarea from expanding or shrinking horizontally.
Width is now fixed at 100% of the parent tag. 
set a minimum height for the textarea to prevent it from shrinking to an excessively small height.
![Screenshot from 2023-11-29 12-20-39](https://github.com/Submitty/Submitty/assets/129476971/0f93b69d-f60b-402b-83a5-741c6353b10f)

### Other information?

2023-12-01 04:08 UTC, VVVITH requested changes
Several things:
1. I test both SQL tool box and the course setting text box mentioned in #10008 , it works as discribed. 
2. A comment in issue #10008 recommend you refer to PR #10007 , which seems make a different solution for the same textbox problem. Please see and make sure your solution is in the right way.
3. In this case, I find the textbox is conflict with the button side, please fix it.
<img width="363" alt="截屏2023-11-30 22 57 30" src="https://github.com/Submitty/Submitty/assets/92846547/4520c5b8-c35d-4338-9624-d4805afb8918">

2023-12-02 17:09 UTC, williamjallen commented
This PR does not resolve https://github.com/Submitty/Submitty/issues/10008.  The changes should be applied to the generic markdown template so all markdown areas are consistent.

2023-12-12 21:08 UTC, VVVITH approved these changes
I have made the changes I request myself. Now the margin do not conflit with the button down there. As William said, this PR do not fix the issue orginially start with, but this PR does a useful and reasonable change. Can have more reviews and may ready to be merged.

2023-12-13 04:34 UTC, cjreed121 approved these changes

2023-12-13 07:52 UTC, merged