[Bugfix:Submission] Moved the text outside the label tag to avoid accidental clicking.
Submitty/Submitty pull request #10040
Opened 2023-12-03 16:35 UTC by sahilsuman933

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [X] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #10039 

On clicking anywhere on the paragraph of text beneath the checkbox and to the right of the "hide from students" text toggles this checkbox.

![image](https://github.com/Submitty/Submitty/assets/34382211/4d0c11a3-fc4e-4b23-bdbf-776032193c5d)

### What is the new behavior?
=> On clicking anywhere on the paragraph of text beneath the checkbox and to the right of the "hide from students" text will not toggle this checkbox.

![image](https://github.com/Submitty/Submitty/assets/34382211/234f086b-8648-4e5e-a649-44690441df33)

### Other information?

None.

2023-12-03 20:21 UTC, cjreed121 requested changes
Thanks for the contribution! According to your screenshot, there seems to be a larger gap between the button and text which shouldn't change. Could you use some CSS or maybe switch the p to span so that the gap doesn't change?

2023-12-03 20:53 UTC, sahilsuman933 commented on site/app/templates/course/EditCourseMaterialsFolderForm.twig
> +
@cjreed121 I have removed the extra line, <br> tag and fixed the gap issue.

2023-12-05 04:12 UTC, cjreed121 requested changes
Thanks for making the change. One more change and this should be good to merge. Before this PR, the red warning text appears below the note. After this PR, the red warning text appears above the note. Can you change the bit of JavaScript responsible for that to ensure it stays in the same spot?

2023-12-05 05:10 UTC, sahilsuman933 commented
@cjreed121 I am aware of this, but I believe it would be more appropriate to display the warning as a note before the text. It would provide a better user experience. If you still want me to make the change, please let me know and I will fix it.

2023-12-05 16:28 UTC, cjreed121 requested changes
Thanks for changing that back. It looks like the gap is still there. I think the label also needs to margin removed. And then the gap between the note and warning as well (they should all be right next to each other). Can you update that? After that this should be good.
![image](https://github.com/Submitty/Submitty/assets/55092742/31b04bbc-3797-4b24-b00e-917f33b51f68)

2023-12-05 18:17 UTC, sahilsuman933 commented
@cjreed121 Is the margin okay now? 
![image](https://github.com/Submitty/Submitty/assets/34382211/49d4f181-cefe-410b-b5b4-939f6ea412fe)

2023-12-05 19:47 UTC, cjreed121 approved these changes
Looks good to me. Thanks for making the changes.

2023-12-05 21:05 UTC, merged