[Feature:InstructorUI] Don't delete access information for deleted course materials #10006
Submitty/Submitty pull request #10075
Opened 2023-12-16 11:30 UTC by Simer13

### Please check if the PR fulfills these requirements:
fixes #10006
* [ ] Tests for the changes have been added/updated (if possible)

### What is the current behavior?
<!--  Currently the access information for deleted course material is deleted too.

### What is the new behavior?

<!-- Implemented soft deletion and a new column is "is_deleted" is added to the course_materials table.

2023-12-17 00:14 UTC, williamjallen commented
Please fill out the PR description with information about the changes you made, and why you made them.  Failure to do so will result in the PR being closed.

2023-12-17 06:03 UTC, Simer13 commented
@williamjallen Done

2024-04-26 23:34 UTC, williamjallen requested changes

2024-04-26 23:34 UTC, williamjallen commented on migration/migrator/migrations/course/20231206173634_course_materials.py
> +                     ALTER TABLE course_materials ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
Should the column be not null?

2024-04-26 23:34 UTC, williamjallen commented on migration/migrator/migrations/course/20231206173634_course_materials.py
> +                     UPDATE course_materials SET is_deleted = FALSE;
Is this necessary?

2024-04-26 23:34 UTC, williamjallen commented on migration/migrator/migrations/course/20231206173634_course_materials.py
> +                     ALTER TABLE course_materials DROP COLUMN IF EXISTS is_deleted;
We typically don't delete columns so data isn't lost if the submitty administrator needs to roll back a migration temporarily before rolling it forward again.  Instead, you could just drop the not-null constraint suggested above, and then update defaults and re-add the constraint in the up migration if necessary.

2024-04-26 23:34 UTC, williamjallen commented on site/app/entities/course/CourseMaterial.php
>      #[ORM\Column(type: Types::FLOAT)]
This needs some additional whitespace around it, as well as a Doctrine attribute.

2024-04-26 23:34 UTC, williamjallen commented on site/app/entities/course/CourseMaterial.php
> +        $this->deleted  = $deleted;
```suggestion
    public function setDeleted(bool $deleted): void {
        $this->deleted  = $deleted;
```

2024-04-26 23:34 UTC, williamjallen commented on site/app/entities/course/CourseMaterial.php
> +    {
```suggestion
    public function isDeleted(): bool {
```

2024-04-26 23:34 UTC, williamjallen commented on site/tests/app/controllers/course/CourseMaterialsControllerTester.php
> +            });
```suggestion
            ->willReturnCallBack(function($courseMaterial) use ($course_material) {
                $this->assertSame($course_material, $courseMaterial);
            });
```

2024-04-26 23:34 UTC, williamjallen commented on site/tests/app/controllers/course/CourseMaterialsControllerTester.php
Please add additional tests for the methods you added.

2024-04-26 23:34 UTC, williamjallen commented on site/tests/app/entities/course/CourseMaterialTester.php
> +        $activeSection =; ['1', '2']; //define the expected active sections
```suggestion
        $activeSection = ['1', '2']; //define the expected active sections 
```

2024-04-26 23:34 UTC, williamjallen commented on site/tests/app/entities/course/CourseMaterialTester.php
>          }
```suggestion
        foreach ($course_material->getSections()->toArray() as $section) {
            if (!$section->isDeleted()) { //check if the section is deleted 
                $this->assertEquals($sections[$index], $section->getSectionId());
                $index++;
            }
        }
```

2024-05-30 14:19 UTC, GO-viper7 commented
Will soon implement tests for this new feature

2024-06-12 20:24 UTC, IDzyre commented
I believe that the cypress tests are failing because the file is stored somewhere behind the scenes, and when it is 'soft deleted', in the back end the file is still stored, so you can't upload the same file again.

2025-06-13 19:12 UTC, williamjallen commented
This PR is pretty stale at this point, with lots of conflicts.  Creating a new PR for this low priority PR will probably be easier than trying to get this ready for review.

2025-06-13 19:12 UTC, closed without merging