[Feature:InstructorUI] Ability to Upload JSON to create gradeable
Submitty/Submitty pull request #10100
Opened 2024-01-12 21:22 UTC by IDzyre

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2024-01-23 20:20 UTC, cjreed121 requested changes
When trying to open the "Upload Gradeable JSON" modal, it did not work and I received the following error in the console:
<img width="522" alt="image" src="https://github.com/Submitty/Submitty/assets/55092742/489a2787-1459-4bcc-a0b8-9473d4860672">

2024-01-23 20:20 UTC, cjreed121 commented on site/app/controllers/admin/AdminGradeableController.php
> +     * @Route("/courses/upload/{_semester}/{_course}", methods={"POST"})
On all of our other routes we have `/courses/{_semester}/{_course}/...`. Is there a reason for it to be different that the others? I think it's better to keep it consistent.

2024-01-23 20:40 UTC, cjreed121 commented
Also when submitting only ID, title, and type (electronic) I get a server error and a lot of undefined key warnings. This should fail more gracefully.

2024-01-23 21:10 UTC, cjreed121 commented
> > When trying to open the "Upload Gradeable JSON" modal, it did not work and I received the following error in the console: <img alt="image" width="522" src="https://private-user-images.githubusercontent.com/55092742/299091470-489a2787-1459-4bcc-a0b8-9473d4860672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNDIyMjIsIm5iZiI6MTcwNjA0MTkyMiwicGF0aCI6Ii81NTA5Mjc0Mi8yOTkwOTE0NzAtNDg5YTI3ODctMTQ1OS00YmNjLWEwYjgtOTQ3M2Q0ODYwNjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDIwMzIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkN2I4OTQ2NmE3OTc0OGMyMDBhOThkZWVhNmQzNzkzNGFhMmMwYjNmYTY0YzM2ZWZmMjE2MTM2ZGEwNzMwNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0QWKf2Qi1FPHJ7OvtK1lRMuAaDrKSelHTjU3nWicTGM">
> 
> I'm not quite sure how to reproduce this. Is this happening when you click the 'upload gradeable json' button ?

Yeah as soon as I click that button

2024-01-30 03:21 UTC, williamjallen reviewed
The repeated query appears to be an existing defect in the gradeable creation process.  Given that this route is never used by many people at the same time, it is fine to ignore it by adding it to `.performance_warning_ignore.json`.

2024-02-02 21:40 UTC, cjreed121 approved these changes
Code looks good and tested locally

2024-02-02 21:49 UTC, IDzyre commented
https://github.com/Submitty/Submitty/pull/10119 should be merged before this one.

2024-02-24 14:43 UTC, bmcutler commented
@IDzyre 
Can you please resolve the merge conflicts?  thanks!

2024-03-01 20:57 UTC, merged