[UI/UX: InstructorUI] Add exception reason
Submitty/Submitty pull request #10124
Opened 2024-01-23 16:38 UTC by Xiayucheng1212

Closes #10123 

* [✅] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

- No reason shown after the late days exception.
### What is the new behavior?
- Add reason for why these late days are acceptable.
- The excuse is shown in the parentheses.
<img width="1559" alt="截圖 2024-01-24 上午12 03 40" src="https://github.com/Submitty/Submitty/assets/60954116/80bd7d0b-7f0e-4a4d-90d9-7bd9ee135768">

2024-01-23 20:25 UTC, DarthNyan requested changes

2024-01-23 20:25 UTC, DarthNyan commented on site/app/templates/LateDaysTablePlugin.twig
> +            <td data-before-content="Days From Extensions">{{ (late_day_info.getLateDayException() != 0) ? late_day_info.getLateDayException() != 0 ? late_day_info.getLateDayException() ~ ' (' ~ late
```suggestion
            <td data-before-content="Days From Extensions">{{ (late_day_info.getLateDayException() != 0) ?  late_day_info.getLateDayException() ~ ' (' ~ late_day_info.getReasonForException() ~ ') ' : placeholder }}</td>
```

You shouldn't need to make this check a second time.

2024-01-29 11:23 UTC, Xiayucheng1212 reviewed
Thank you for pointing out.

2024-01-30 22:03 UTC, DarthNyan requested changes
Two changes, then this should be good to merge.
1. You've added a second space after the '?'. Please change that to a single space.
2. Can you edit the title to reflect that you're adding the exception reason to the "My Late Days" page? PR titles go in the release notes so it's helpful for readers if your title is specific about what page/s your changes affect.

2024-02-07 06:27 UTC, Xiayucheng1212 commented
@DarthNyan Thank you for your review. Both suggestions are applied, please check 👍

2024-02-08 17:18 UTC, DarthNyan approved these changes
Looks good to me

2024-02-24 07:28 UTC, Xiayucheng1212 commented
@DarthNyan  Hi, could you please tell me how to solve the Cypress checks for UI? I am not sure why this happens.

2024-03-31 19:45 UTC, shailpatels approved these changes
Thanks for the PR!

Not sure why CI was stuck but kicked off again via a merge so hopefully it goes through this time

2024-04-03 02:41 UTC, williamjallen approved these changes
Thanks for this contribution, and apologies for letting this one go unreviewed for such a long time!  This is now on track to get merged in the near future.

2024-04-09 17:17 UTC, bmcutler commented
@Xiayucheng1212 Thanks for the contribution!

2024-04-09 17:17 UTC, merged