[Bugfix:TAGrading] Fix Progress Bar for Peer Graders
Submitty/Submitty pull request #10128
Opened 2024-01-25 13:06 UTC by NiaHeermance

### What is the current behavior?
When logged in as a peer grader, progress bar displays 100% even when one has not graded a single component.

### What is the new behavior?
The progress bar now accurately displays the number of components you have left to grade.

Solves issue #10050 .

2024-01-26 19:35 UTC, VVVITH commented
Hi, I have reviewed from the instructor view, looks all right, but haven't test from the peer grader view. Which account should I use to test peer grader view? I've tried many student account but neither of them have the peer grader access.
Also, the code on new line 1762, is there a problem and waiting to be fixed?

2024-01-26 21:02 UTC, NiaHeermance commented
Hello, I've just updated the main post with instructions how to test, so you can see the peer view with that. As for the comment, I do need to address it, as I have now learned there is peer grading for team gradeables.

2024-01-30 07:18 UTC, VVVITH reviewed
As the test instruction, I did test the case for 0 percentage of peer grade. It does change from 100 to 0. But when I try to do peer grade to see more progress bar cases. I meet something weird. Login with the peer grader student, I can access the grading and the actual grade page, but everytime I want to make change on the grading component and save my grade, it calls an error. Error message attached.
<img width="1692" alt="截屏2024-01-30 02 02 37" src="https://github.com/Submitty/Submitty/assets/92846547/9764b05c-d258-4e34-a130-b9f4dbd93cf5">
I'm not clear what settings I have to meet this situtation.

2024-01-30 20:39 UTC, williamlin6803 commented
Hi, I have reviewed this and it looks good to me. One critique I have is that: For example, some variables could benefit from more descriptive names. For example, $total_submitted could be renamed to something like $total_submitted_peer to make it clear that it's specifically related to peer grading.

2024-02-06 19:41 UTC, ZheyuDeng commented
Tested the code and follow test steps provided looks good!

2024-02-06 22:29 UTC, thegame615 reviewed
I followed the steps and was able to replicate the issue on main and verify that the issue was fixed on the branch. I imagine that we will probably have many issues associated with peer grading in the future.

2024-02-12 20:27 UTC, ZheyuDeng reviewed
After the php lint is fixed should be good to go

2024-02-13 19:00 UTC, ArnavPawar approved these changes
Has a PHP fix required but this seems to fix the issue with what is currently in the main branch. I don't get the same issue when testing it in your branch. As for the code it looks good seemed to have just added team checks and change the grading form if it was a team assignment.

2024-02-13 21:48 UTC, JWei17 approved these changes
This looks good to me, at less I didn't find out any bugs.

2024-02-27 20:28 UTC, arougey approved these changes
Code works as expected and is understandable

2024-04-03 02:46 UTC, williamjallen requested changes
Everything looks decent, but PHPStan is still failing.  This should be on track to merge once the PHPStan errors are resolved.

2024-04-03 02:46 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +     * @return The number of teams this peer is grading.
The "The" after the `@return` PHPDoc annotation is being interpreted as a type by PHPStan, and is causing a PHPStan error.

2024-04-03 02:46 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +     * @param array<Team> $teams All teams for this gradeable.
You need to add the right namespace for `Team` to fix the PHPStan error.

2024-04-27 07:41 UTC, thegame615 commented
Relevant issue is closed by [#10272](https://github.com/Submitty/Submitty/pull/10272)

2024-04-27 07:41 UTC, closed without merging