[Testing:TAGrading] Add cypress test cases for Numeric/Text gradeable
Submitty/Submitty pull request #10177
Opened 2024-02-11 10:24 UTC by charvimehradu

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Closes #8895 

Currently, there are no tests written for testing the functionality that double-clicking a cell activates typing mode and we can use arrow keys to control the cursor position within that cell.

### What is the new behavior?

Added cypress test to:
Test that in the sample numeric grading double click can activate typing mode.
Test that in the sample numeric grading double click can  simulate typing within a cell.
Test that in typing mode arrow keys can move the cursor within the cell.

2024-03-12 03:23 UTC, williamjallen commented
Hi @charvimehradu, apologies for the delay in reviewing this.  I just ran the tests for you.  @IDzyre is our local Cypress expert, so I have requested his review.

2024-03-12 06:07 UTC, IDzyre requested changes
After a selector is changed, and the js-linting is fixed i'll re-review.

2024-03-12 06:07 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/numeric_grading.spec.js
> +    cy.get('input#cell-1-0-0.option-small-box.cell-grade').should('exist');
This should be a better selector, consider adding a cypress selector to the html element. https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

2024-03-25 21:10 UTC, IDzyre approved these changes
Tests look alright to me, i am not familiar with the feature its self to know much about it.

2024-03-26 07:01 UTC, charvimehradu commented
Thanks for testing it @IDzyre

2024-04-03 02:06 UTC, merged