[Bugfix:Autograding] Copy all named executables to runner
Submitty/Submitty pull request #10173
Opened 2024-02-09 16:24 UTC by DarthNyan

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixies #10121 . Currently, the autograder only copies .out and .class files from the compiler to the runner. This means if the instructor creates a compilation testcase that compiles into anything other than .out or .class, the file will not be copied to the runner and other testcases will fail.

### What is the new behavior?
Now, in addition to copying all .out and .class files to the runner, any file that is listed in the "executable_name" field in the gradeable's config.json will also be copied to the runner. 

### Other information?

This needs more testing. I've been able to verify that it works when a single executable is produced, but I haven't been able to test whether it correctly handles an array of executable names. I'm currently working on a java example for this, and I'll upload it as a separate PR when it's done.

2024-02-09 20:33 UTC, williamlin6803 reviewed
Code looks good to me. I think this is a fantastic enhancement to the autograding system, and it directly addresses the limitations highlighted in issue #10121.

2024-02-16 18:12 UTC, cjreed121 commented on grading/load_config_json.cpp
> +          whole_config["autograding"]["compilation_to_runner"].push_back(*exe_name);
Should `**/` go in front of the executable name? I don't think we can be certain where they compiled the file.

2024-02-21 06:07 UTC, cjreed121 requested changes

2024-02-21 06:07 UTC, cjreed121 commented on grading/load_config_json.cpp
> +              std::string name = to_string(*itr);
`to_string` is not the best choice here. According to the [docs](https://json.nlohmann.me/api/basic_json/to_string/), `to_string` is used for getting the serialized result which is why you have to strip the quotes. I think you should just be able to get the value from the iterator. Or maybe std's to_string could help. There is definitely a way to accomplish this without stripping quotes.

2024-03-19 18:04 UTC, cjreed121 approved these changes
Code looks good

2024-04-09 18:09 UTC, bmcutler requested changes
Looks good overall, just asking for 1 more error message.

2024-04-09 18:09 UTC, bmcutler commented on grading/load_config_json.cpp
> +      }
I think we should add an else case here to error out if its not an array or a string.
(similar to the error when the array contains a non-string).
More error messages to the instructor is better :)

2024-04-18 01:52 UTC, bmcutler approved these changes
thanks for the refactor

2024-04-18 01:53 UTC, merged