Implemented-Search-For-Timezone
Submitty/Submitty pull request #10187
Opened 2024-02-14 21:48 UTC by samhithaarani

Genaral Approch:
listens for user input in the search input field.
As the user types, it filters the options in the dropdown based on whether they contain the search term.
If an option matches the search term, it's displayed; otherwise, it's hidden.

solved #10186 
![resolved](https://github.com/Submitty/Submitty/assets/73035235/a5042d8f-71fb-40fc-bf23-a198c0eaa91f)

2024-02-23 20:58 UTC, michaelkrar commented
@samhithaarani Reviewing this right now everything looks good but I do not understand how the commits in DatabaseQueries.php help to solve the issue or if it is a solution to another issue, as this looks like code that deals with Gradeable data rather than User data(correct me if I am wrong).

2024-02-23 21:19 UTC, michaelkrar requested changes
See above comment

2024-02-25 11:50 UTC, samhithaarani commented
> @samhithaarani Reviewing this right now everything looks good but I do not understand how the commits in DatabaseQueries.php help to solve the issue or if it is a solution to another issue, as this looks like code that deals with Gradeable data rather than User data(correct me if I am wrong). When I undo the changes done to that file the fix still works properly too.

Hey :) Thanks for your review....ther's nothing to do with the DatabaseQueries.php , i've got this unknown Deprecated error,so i've done this modification to ensures that json_decode() is not called with null, thus avoiding the deprecated behavior and addressing the issue ...... Thank you :)
![Issue-Submitty](https://github.com/Submitty/Submitty/assets/73035235/ffcac5c4-29d7-41df-b83a-7affe0923fac)

2024-03-05 18:31 UTC, IDzyre commented
> >
> Hey :) Thanks for your review....ther's nothing to do with the DatabaseQueries.php , i've got this unknown Deprecated error,so i've done this modification to ensures that json_decode() is not called with null, thus avoiding the deprecated behavior and addressing the issue ...... Thank you :)

This should be in a different PR in that case, since it is not related to the time zone issue you are trying to resolve.

2024-03-07 07:18 UTC, samhithaarani commented
> See above comment. also change title to include "[Feature:..."

Hey i'm sorry not aware of it ...i'm still learning! 
can i create a new issue and implement separate PR's  ?

2024-04-02 20:44 UTC, 04vmatsibekker commented on site/app/libraries/database/DatabaseQueries.php
> +            // updated the deprecated behavior in PHP. Passing null to json_decode()
remove this line

2024-04-02 20:44 UTC, 04vmatsibekker commented on site/app/libraries/database/DatabaseQueries.php
> +
remove this line

2024-04-02 20:44 UTC, 04vmatsibekker commented on site/app/templates/UserProfile.twig
> +
remove extra line

2024-04-02 20:44 UTC, 04vmatsibekker commented on site/app/templates/UserProfile.twig
> +<script>
I think you should move the code within the script tag into user-profile.js .

2024-04-02 20:45 UTC, 04vmatsibekker commented
Also the title was done incorrectly. Here is the submitty documentation for properly naming a PR: https://submitty.org/developer/getting_started/make_a_pull_request

2024-05-31 20:34 UTC, IDzyre commented
was this added in https://github.com/Submitty/Submitty/pull/10277

2024-05-31 20:38 UTC, dorian451 commented
Yeah, it seems we already have this feature in https://github.com/Submitty/Submitty/pull/10277. Thanks for your work!

2024-05-31 20:38 UTC, closed without merging