[Feature:Calendar] Add in Event Advertisements backend
Submitty/Submitty pull request #10190
Opened 2024-02-16 21:14 UTC by 04vmatsibekker

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Can't displays advertisements for clubs
### What is the new behavior?
Structured the backend so that we can display on globalHeader
### Other information?

2024-02-23 15:28 UTC, DarthNyan requested changes
There were some areas, especially in PHP code, where I had trouble following what you were doing and why it was necessary. Adding code comments throughout would help. A comment that explains the banner file structure would also be helpful for maintainers, as would comments describing the data fields in the BannerImage class.

I also noticed some changes to the poll code that seem like they belong to a separate PR.

Other than that, things look good to me.

2024-02-23 21:15 UTC, 04vmatsibekker commented on site/app/templates/polls/PollForm.twig
> +    <h1 id = "new-poll-title">{{ poll is not null ? "Edit Poll" : "Add a New Poll" }}</h1>
It makes my cypress test pass

2024-02-23 21:17 UTC, 04vmatsibekker commented on site/app/templates/banner/UploadBannerPopup.twig
> +        $('#url_link_address').hide();
It causes complications to move it, this can be a separate PR

2024-02-24 19:28 UTC, williamjallen commented on site/app/repositories/banner/BannerImageRepository.php
> +        return $this->_em->createQuery('
Regular SQL queries go in `DatabaseQueries.php`, but this is a Doctrine DQL query.  DQL queries belong in "Repositories" associated with a Doctrine entity.

2024-02-24 19:30 UTC, williamjallen commented
It would be helpful to fill out the PR description with details about why this change is made, and the future roadmap for this feature.  If another developer takes on the frontend later on, having information to refer to will be immensely helpful.

2024-02-27 13:25 UTC, 04vmatsibekker commented on site/app/controllers/banner/BannerController.php
> +        elseif ($count_item > 2) {
Cuz you can only have 1 banner, and 1 bigger banner

2024-03-01 02:12 UTC, cjreed121 requested changes

2024-03-01 02:12 UTC, cjreed121 commented on site/app/controllers/banner/BannerController.php
> +        for ($j = 0; $j < $count_item; $j++) {
Isn't `count_item` restricted to be 1? Can we remove this loop?

2024-03-11 17:05 UTC, williamjallen requested changes
Other than these comments, I think it's good enough to be considered done as a work-in-progress at this point.  There are a bunch of small stylistic things left, but they probably aren't worth blocking this further.

2024-03-11 17:05 UTC, williamjallen commented on site/public/js/drag-and-drop.js
> +                    'send it to an administrator, as well as what you were doing and what files you were uploading. - [handleUploadCourseMaterials]');
Did you copy this from somewhere?

2024-03-11 17:05 UTC, williamjallen commented on site/public/js/server.js
> +/* exported newUploadBanner */
This should be moved to the existing `exported` section at the top

2024-03-15 14:21 UTC, DarthNyan approved these changes
Looks good to me.

2024-03-15 22:02 UTC, williamjallen commented
The current PR title does not adequately describe what this PR does.  Please change the title to something that summarizes this PR so it's clear in the release notes.

The changes seem reasonable to me, and I'll approve once the title is changed.

2024-03-15 22:04 UTC, 04vmatsibekker commented
> The current PR title does not adequately describe what this PR does. Please change the title to something that summarizes this PR so it's clear in the release notes.
> 
> The changes seem reasonable to me, and I'll approve once the title is changed.

Done

2024-03-17 00:27 UTC, williamjallen approved these changes
Seems reasonable to me as a first step towards the final feature implementation.

2024-03-17 17:55 UTC, cjreed121 approved these changes
Changes look good for the backend of this feature

2024-04-26 23:02 UTC, bmcutler approved these changes
I tweaked text and switched access to superusers only to prevent confusing faculty with unfinished feature.

Ready to merge assuming tests pass...

2024-04-26 23:30 UTC, merged