[BugFix:Forum] Search for dashes as well when searching for discussions
Submitty/Submitty pull request #10204
Opened 2024-02-24 01:51 UTC by iamdanielyun

### What is the current behavior?

Fixes  #10141 

### What is the new behavior?
Able to do a more robust sql query to search for dashes as well in submitty forum serach field

*Code looks mostly the same except for reformatting, but the key detail is plainto_tsquery(:q) => phraseto_tsquery(:q)

2024-02-27 19:54 UTC, DarthNyan reviewed
This manages to search for dashes, but I remember doing a bit of research into this and I found the root cause was that the query was searching for a whole word, maybe with punctuation, surrounded by whitespace, and that the reason the search term failed to find was because of the ".java". I think a better fix would be to search for parts of words, not necessarily full words.

I really appreciate you splitting the query into multiple lines, but I still think you can break it into more lines to improve readability.

2024-02-27 20:18 UTC, RayReyRam submitted a review, later dismissed
When testing in my machine, the search function was still not working, Logged in as instructor, then created a thread having the same message as the initial bug and it still says that there is no thread that match my criteria. Heres some screenshots
<img width="1273" alt="image1" src="https://github.com/Submitty/Submitty/assets/148298134/92049598-3bfa-4e5e-912c-6127599e9239">
<img width="1271" alt="image2" src="https://github.com/Submitty/Submitty/assets/148298134/6a463094-1d42-49e5-912d-96143ff048f5">

2024-05-29 17:19 UTC, micpap25 commented
I would appreciate a review on this greatly. My observation is that periods are a "special character" in the context of submitty due to their frequent use in file names. Therefore, making it so users can easily search both the name of the file without the filetype, or the filetype without the name of the file, is important. This push resolves the linked issue but may require further testing to make sure it isn't too loose.

2024-05-31 19:18 UTC, zacharymnp approved these changes
Query results for 'file.extension' and 'file extension' will be identical, but the query itself is more robust

2024-06-03 15:27 UTC, ziesski commented on site/app/libraries/database/DatabaseQueries.php
> +                to_tsvector('english', replace(p.content, '.', ' '))
Notice that the format has improved, which is more organized, but would be better to state what you have changed to address the issue, especially when the github diff checker is not parsing the diff precisely. 

In this case I noticed that language parameter in to_tsvector is specified to english, and used replace function to remove period(`.`) from the content and title field. 

I think the changes are overall good improvements.

2024-06-03 15:34 UTC, ziesski requested changes
![스크린샷 2024-06-03 오전 11 31 05](https://github.com/Submitty/Submitty/assets/123261952/8f438c67-6137-4dac-85e3-a7b6d4d7b580)

I found a corner case while testing this PR. 
The problem is query finds 9876 and 4444, but it will not find 5432

To reproduce, create post with `int-int=int`
search for the middle int, and see the issue.

2024-06-03 17:58 UTC, ziesski approved these changes
Tested, the query now handles the above mentioned corner case as expected. Looks good to me.

2024-06-03 19:24 UTC, merged