[Bugfix:CourseMaterials] Disables ability to scroll on popup
Submitty/Submitty pull request #10200
Opened 2024-02-23 18:08 UTC by RayReyRam

Fixed a bug when the modal/popup in the course material page would pop up you would still be able to scroll, and see the background move

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Previously there was an ability, when a popup/modal was open  to scroll in the background behind/around the modal. Fixes issue [#10058](https://github.com/Submitty/Submitty/issues/10058)

### What is the new behavior?
This disables the ability to scroll when the modal is open, and then reenables the scrolling ability when the modal is closed.
### Other information?
To test go into the course material tab, and click any option that would create a popup, such as edit material page folder, or set release date

2024-02-23 19:32 UTC, ArnavPawar approved these changes
Code makes sense and works as expected. Before merging just ensure that this how an instructor would want the page to work, maybe instructors like the scroll in the background?

2024-02-23 20:02 UTC, williamlin6803 commented
The code introduces useful features and I verified its working on my machine. Adding on to what Arnav said, before finalizing, seek feedback from end-users on the new batch update functionality, ensuring it aligns with their workflow.

2024-02-23 20:03 UTC, williamlin6803 approved these changes
The code introduces useful features and I verified its working on my machine. Adding on to what Arnav said, before finalizing, seek feedback from end-users on the new batch update functionality, ensuring it aligns with their workflow.

2024-02-23 21:38 UTC, 04vmatsibekker approved these changes

2024-02-27 12:33 UTC, hansongu123 requested changes
I wouldn't oppose disabling scrolling the body after a popup form is opened as a way to resolve the bug (and potentially other issues), but you should ask Barb if we want to do that before merging.

2024-02-27 12:33 UTC, hansongu123 commented on site/app/templates/generic/Popup.twig
> +        $('body').css('overflow', 'auto');
This change should be placed outside of the `closePopup()` function

2024-02-27 12:33 UTC, hansongu123 commented on site/public/js/server.js
> +    $('body').css('overflow', 'hidden');
This change shouldn't be included in the captureTabInModal() function as the function is only used within some modals that require scrolling, this is the reason why you had to include the same line again in the for the release all form.

2024-04-04 16:50 UTC, jeffrey-asm approved these changes
The changes look good. For all of the potential forms on the course materials page, no instructor can scroll outside of the popup, but scrolling within the popup is still functional.

2024-04-07 21:25 UTC, hansongu123 submitted a review, later dismissed
The requested changes are addressed. Just some nitpicks. This PR should be good to go afterwards!

2024-04-07 21:25 UTC, hansongu123 commented on site/public/css/server.css
> +
```suggestion
```

2024-04-07 21:25 UTC, hansongu123 commented on site/public/js/server.js
> +
```suggestion
```

2024-04-07 21:25 UTC, hansongu123 commented on site/public/js/server.js
> -var lastActiveElement = null;
Is there any reason to move these lines?

2024-04-09 21:37 UTC, arougey approved these changes
Good refactoring to make popups a function. Everything works as expected when testing.

2024-04-19 03:33 UTC, williamjallen commented on site/public/js/server.js
> +function closePopup(id) {
Instead of ignoring the error inline like this, the name of the function should be added to the list at the top of the file.

2024-04-19 03:33 UTC, williamjallen commented on site/public/js/server.js
> +    $(selector).css('display', 'block');
jQuery has a `.show()` helper which could make this simpler.  Note: this is just a suggestion, not necessarily a requested change.
```suggestion
    $(selector).show();
```

2024-04-19 21:10 UTC, williamjallen approved these changes

2024-04-26 18:27 UTC, merged