[UI/]Fix the CodeMirror size for "Notebook.twig"
Submitty/Submitty pull request #10206
Opened 2024-02-24 16:11 UTC by Xiayucheng1212

Fixes #10182 

### What is the current behavior?
The text box for short answer question in a notebook can be manually resized arbitrarily. It sometimes conflicts with other UI components near by. 

### What is the new behavior?

https://github.com/Submitty/Submitty/assets/60954116/0af71dcf-b5d5-4a2d-a8c1-02a1a708ce64

2024-03-15 18:53 UTC, ArnavPawar requested changes
Reviewed this same PR earlier still not sure if it matches the issue that you is linked. If you can confirm with other people that it matches then It will be good to merge.

2024-03-18 14:10 UTC, Xiayucheng1212 commented
> Reviewed this same PR earlier still not sure if it matches the issue that you is linked. If you can confirm with other people that it matches then It will be good to merge.

@ArnavPawar  Thank you for review. I think this PR fulfills the issue #10182, but I would like to check with @VVVITH again. 
@VVVITH Hi, could you please check my PR to see it matches the issue number? Thank you!

2024-03-29 16:48 UTC, justin-sadakhom approved these changes
@Xiayucheng1212 Confirming that this PR matches #10182. Looks good from my end.

2024-04-06 13:10 UTC, Xiayucheng1212 commented
@ArnavPawar The change has been confirmed. I think it's good to go now.

2024-04-22 21:58 UTC, wuj18 reviewed
I tested the changes and everything works as expected. The textbox's width and minimum height are fixed, and resizing is only allowed vertically. However, I'm noticing another issue: when inputting a long string, it does not wrap to the next line upon reaching the maximum width. Pressing the Enter button doesn't move to a new line either. I'm not sure if it falls within the scope of this issue. If not I can create a new issue to address it.

https://github.com/Submitty/Submitty/assets/75406429/95acfdc3-6dbc-4da0-a61c-15faf6292042

2024-05-01 10:12 UTC, Xiayucheng1212 commented
@wuj18 Yeah, I think it should be included in this PR. Do you have any suggestion to solve it?

2024-05-29 17:52 UTC, micpap25 commented
Just a couple thoughts, looping in @ArnavPawar @wuj18 due to relevance to the issue.

Is it necessary to be able to resize the box for a "short answer" type of question where the answer should be constrained to a single line anyways? What value does increasing the height of the box provide? Perhaps we could allow users to increase and decrease the size of the box horizontally up to a limit? This only applies for short answer boxes, of course. 

For the other kinds of boxes, I think this change looks good to me. But I I would just like to change the functionality for short answer boxes.

2024-05-29 17:53 UTC, micpap25 requested changes

2024-05-29 17:53 UTC, micpap25 commented on site/public/css/gradeable-notebook.css
> +    min-height: 300px;
For a short answer, this is much too large.

2024-05-29 17:53 UTC, micpap25 commented on site/public/css/gradeable-notebook.css
> +    resize: vertical;
For a short answer, it may be useful to be able to extend horizontally, and it is definitely not useful to be able to extend vertically.

2024-05-30 15:15 UTC, micpap25 commented
Would really appreciate a review on this! How does it look graphically? Also, maybe a new name since it's also making notebook CSS a bit more flexible?

2024-06-04 18:42 UTC, zacharymnp approved these changes
https://github.com/Submitty/Submitty/assets/56311867/ea6fe3cd-4424-41b1-966d-dd50313d6f43

When short answer height is not default, only the vertical size can be changed. When short answer height is default, only the horizontal size can be changed.

2024-06-05 15:17 UTC, micpap25 commented
Updated main PR post to reflect changes

2024-06-05 23:01 UTC, merged