Fixed a bug #10207
Submitty/Submitty pull request #10209
Opened 2024-02-25 08:52 UTC by shreyashrpawar

Solved issue  #10207

The issue is generating because we are taking a value of first index of an array which is empty. So, I have added nested ternary block which will take that first element if the length of an array is greater than 0.

### What is the current behavior?
Now, because of the modification it is working fine

2024-02-25 21:54 UTC, michaelkrar requested changes
Not an issue in firefox. Was able to replicate the issue on chrome. The changes completely fix the issue and are non-breaking. Changes are a reasonable solution and the code is formatted well / logic is simple to follow. Also changes appear to not break anything in Firefox as well as student/ta logins.
PR Title shouuld be changed to be more specific as to what bug is being fixed, and also include the prefix: [Bugfix:Calendar]

2024-02-28 13:44 UTC, GO-viper7 requested changes
PR title should be bit more concise, as it is limited to 40 characters excluding [Bugfix:Calendar] and gives title-check fail if it is not followed.

2024-02-28 17:45 UTC, shreyashrpawar reviewed
Simplified the code as instructed by [arougey](https://github.com/arougey).
Also changed the title as suggested by [GO-viper7](https://github.com/GO-viper7).

2024-02-29 02:07 UTC, IDzyre commented
All of these warnings cause misalligned UI, it would be better to state what the warning is for, and/or where it is found, like `Fix Superuser Calendar View` or `Check if calendar array is empty`

2024-03-01 03:00 UTC, shreyashrpawar commented
> All of these warnings cause misalligned UI, it would be better to state what the warning is for, and/or where it is found, like `Fix Superuser Calendar View` or `Check if calendar array is empty`

Thanks for the suggestion. I have changed the title as more precise. Kindly approve. [IDzyre](https://github.com/IDzyre)   [GO-viper7](https://github.com/GO-viper7)   [arougey](https://github.com/arougey)   [michaelkrar](https://github.com/michaelkrar)

2024-03-02 01:28 UTC, iamdanielyun approved these changes

2024-03-09 06:13 UTC, JoJo-ESC approved these changes
Code looks good and changes can be seen on my machine. If I had any common it would be to pls change the title to calendar_fix.

2024-03-29 18:57 UTC, IDzyre requested changes

2024-03-29 18:57 UTC, IDzyre commented on site/app/views/calendar/CalendarView.php
> +            "calendar_course_cookie" => $_COOKIE['calendar_course'] ?? ($formatted_courses[0] ?? NULL),
```suggestion
            "calendar_course_cookie" => $_COOKIE['calendar_course'] ?? ($formatted_courses[0] ?? null),
```

for php lint

2024-04-02 18:23 UTC, IDzyre approved these changes

2024-04-02 19:44 UTC, cjreed121 approved these changes
Looks good to me

2024-04-02 19:53 UTC, merged