[Bugfix: InstructorUI] Feature for downloading grades via gradebook
Submitty/Submitty pull request #10213
Opened 2024-02-29 17:42 UTC by MUFFANUJ

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Closes #10078  

### What is the new behavior?
* Downloadable CSV: Implement a dedicated button labeled "Download Grades of grades" that allows users to easily export all gradebook data into a comma-separated values (CSV) file format.

* 

https://github.com/Submitty/Submitty/assets/151390316/06a29734-d22b-4074-9ffc-853bfa60783f

Last Updated Timestamp: Display a clear timestamp below the Download button indicating the exact date and time the gradebook data was last updated. This timestamp will help users understand the freshness of the information they might be downloading.

### Other information?

Successfully conducted local testing on the download functionality and data modification timestamp feature. This included verifying the file download process, along with confirming the accuracy of the displayed last modified time for the gradebook data.

This pull request builds upon the previous one #10079 , which was submitted over a month ago. It addresses the outstanding checks that were not met in the last iteration and aims to deliver a more comprehensive and well-rounded solution.

2024-04-11 03:42 UTC, DarthNyan requested changes
Sorry about the late review. Please see the attached comments.

2024-04-11 03:42 UTC, DarthNyan commented on site/app/libraries/Access.php
> +            $path = ($path[0] === "/") ? substr($path, 1) : $info["base"] . "/" . $path;
The ternary operation doesn't work as written as the old `$path = $info["base"] . "/" . $path);` is not in an else block.

2024-04-11 03:42 UTC, DarthNyan commented on site/app/libraries/Access.php
> +            $base = substr($info["base"], 0, -23) . "/rainbow_grades";
I don't like using "-23" as a literal here, as this feels succeptable to breaking. It would be better to calculate this from $info["base"].

2024-04-11 03:42 UTC, DarthNyan commented on site/app/templates/submission/RainbowGrades.twig
> +          No Grades Are Available...
These are fine left uncapitalized.

2024-04-12 21:25 UTC, 04vmatsibekker requested changes

2024-04-12 21:25 UTC, 04vmatsibekker commented on site/app/controllers/admin/ReportController.php
> +        $grade_summaries_last_run = $this->getGradeSummariesLastRun();
no spaces should be tabs

2024-04-12 21:25 UTC, 04vmatsibekker commented on site/app/controllers/admin/ReportController.php
> +
remove line

2024-04-12 21:25 UTC, 04vmatsibekker commented on site/app/libraries/Access.php
> -            // and lets us have relative paths. Convenient!
The comments don't look super concise.

2024-04-12 21:25 UTC, 04vmatsibekker commented on site/app/libraries/Access.php
> -
accidently removed a line

2024-04-12 21:25 UTC, 04vmatsibekker commented on site/app/templates/submission/RainbowGrades.twig
> +                    <button
you are having a lot of the styling defined in the twig file, perhaps you should try to move it to a css file?

2024-06-05 16:19 UTC, ziesski commented
This PR has valuable updates based on PR #10079 however, we are unable to carry both PRs and decided to cherry pick the updates that has been made in this PR and merged to the original PR. All works are credited accordingly. Thanks for contributing to our open source software :)

2024-06-05 16:46 UTC, closed without merging