[Refactor:Submission] Fix Abadon Team
Submitty/Submitty pull request #10210
Opened 2024-02-27 20:21 UTC by zhehua-zhang

fetch abandoned team with submission, and no team member

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2024-03-24 01:32 UTC, williamjallen commented
It looks like there's a spelling error in your PR title.  The title is also pretty generic, and could be improved by succinctly describing what specifically is being fixed.  On a related note, I'm having trouble understanding what this PR is supposed to fix based on the PR description alone.  Can you please update the PR description, and add before and after screenshots?  Remember that your PR title and description are the permanent record of what and why a change was made, and someone may refer to this at a future point.

2024-04-16 22:23 UTC, ziesski commented on site/app/controllers/grading/ElectronicGraderController.php
> +                //if ($team->getSize() === 0 && $show_empty_teams) {
Remove this for clarity

2024-04-16 22:29 UTC, ziesski commented
should instructor have access to the submission of the empty team? Just from the screenshot, I could not tell because it does not have view button.

2024-06-04 15:21 UTC, zacharymnp approved these changes
Empty Teams dropdown exists for Instructor grading and not TA grading, which matches expected behavior. Empty Teams dropdown exists when a team is emptied and disappears when the team is filled again.

2024-06-04 17:33 UTC, ziesski commented
Can you connect the newly created issues to this PR so future devs can use it as a reference?

2024-06-04 19:17 UTC, ziesski requested changes
Description mentions that this PR solves only some part of empty teams, however, it is not tackling the primary issue requested in issue #9985 that grading stats page does not correctly reflect abandoned teams. 

Here is an example, if you see section 1, there is only one valid team submission after removing one team. However, if we look at TA Grading By Sections: Section 1: 2 / 3 (66.7%), it is still 2/3 which is not correctly updated. 
Empty team is well displayed on the grading index page, matching the description, however, it also needs to match the grading stats page. Please fix them 

<img width="621" alt="스크린샷 2024-06-04 오후 3 11 44" src="https://github.com/Submitty/Submitty/assets/123261952/00e5e205-61c6-4ef2-8c5a-d83502f0b92c">

<img width="1044" alt="스크린샷 2024-06-04 오후 3 12 06" src="https://github.com/Submitty/Submitty/assets/123261952/ffa901ba-b3f6-4442-897c-b8a4701aa4d4">

2024-06-07 02:21 UTC, bmcutler approved these changes
I tested this, it solves a significant part of the problem.  Thank you!
I will leave the issue open.  There are remaining bugs as noted above, and we need to write tests of empty/abandoned teams within the TA grading interface to make sure this feature doesn't break again in the future.

2024-06-07 02:25 UTC, merged