[Bugfix:Calendar] Add year & month dropdown
Submitty/Submitty pull request #10246
Opened 2024-03-13 07:08 UTC by Xiayucheng1212

fixes #10242 
### What is the new behavior?
Two new buttons added aside the current `option` button.
The year button starts from the `current_year - 100` to `current_year + 100`
<img width="910" alt="截圖 2024-03-13 下午3 04 15" src="https://github.com/Submitty/Submitty/assets/60954116/627e33fb-428c-4605-a200-136605abd0fb">

2024-03-15 19:01 UTC, ArnavPawar requested changes
I think the change I requested is all that is needed to be fixed for this to be good to merge

2024-03-15 21:43 UTC, ArnavPawar commented
> I think the change I requested is all that is needed to be fixed for this to be good to merge

I just reviewed a new PR and I think it implemented this feature correctly. That one may get merged first so if you want to brainstorm with him I think there are some features that he is planning to work on to make the UI better.

2024-03-25 08:10 UTC, Xiayucheng1212 commented
> > I think the change I requested is all that is needed to be fixed for this to be good to merge
> 
> I just reviewed a new PR and I think it implemented this feature correctly. That one may get merged first so if you want to brainstorm with him I think there are some features that he is planning to work on to make the UI better.

Got it, thank you!

2024-03-26 21:36 UTC, arougey reviewed
Hey, I also created a PR with the same issue in the branch titled "Month and Year Dropdown Menus". If you want to work from there, there is an error where the Wednesday Cell is too wide. I also moved the dropdown menu from the top to the calendar which was requested by Submitty leaders. @Xiayucheng1212

2024-04-02 20:22 UTC, 04vmatsibekker requested changes

2024-04-02 20:22 UTC, 04vmatsibekker commented on site/app/templates/calendar/Calendar.twig
> +    function changeMonth(x) {
Yea I agree with this

2024-04-02 20:22 UTC, 04vmatsibekker commented on site/app/templates/calendar/Calendar.twig
> +                <select id="calendar-month-edit" onchange="changeMonth(this);">
Could we somehow have a list of the months, and then use a loop. Its just quite a few lines, and would be cleaner to read if we used a loop to look through each month in a list of months

2024-06-13 20:02 UTC, ZheyuDeng commented
Close PR #10246   as PR #10249 fixed the issue #10242

2024-06-13 20:02 UTC, closed without merging