[Feature:SubminiPolls] Add WebSocket to polls
Submitty/Submitty pull request #10253
Opened 2024-03-14 19:45 UTC by jeffrey-asm

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, the histogram of the poll page on the instructor side does not update dynamically. Instructors must refresh the page to get the most up-to-date poll information to be reflected on the histogram.

### What is the new behavior?
Instructors can now see updates reflected on the histogram as a student submits their poll response(s). On student submission, a WebSocket message will be sent only containing updates for the most recently changed option response counts. Only instructors will be able to receive WebSocket messages on the front end.

### Other information?
This is a small change to the polls feature of Submitty. I tested by submitting various changes in polls side by side as instructor and student. As a student would submit a change in a given poll, the histogram would update on the instructor side in constant time. This feature works toward completing [#5913](https://github.com/Submitty/Submitty/issues/5913).

2024-03-15 14:26 UTC, ZheyuDeng reviewed
I tested the case where a student edit his answer and submit again. The histogram will include both of his submission unless when the page is refreshed it will removes the first one. 
After second submission where student removes b and submit again, the histogram shows both submission as you can see the response goes to 2.
![71666907f718c2a25571f2a77e17bdd](https://github.com/Submitty/Submitty/assets/122962727/6f4e7135-5e84-4346-bd48-5bb225c73223)

2024-03-22 19:20 UTC, ZheyuDeng approved these changes
Tested and worked for me!

2024-03-29 21:41 UTC, cjreed121 commented
This is on hold of being merged until https://github.com/Submitty/Submitty/issues/10296 is closed

2025-03-15 02:23 UTC, williamjallen commented
@martig7 This would be a great PR to review if you're interested in some of the web socket stuff.

2025-03-18 21:51 UTC, martig7 approved these changes
This works well, I was able to test two people submitting a poll at the same time and it worked as expected. We should think about how we could test websockets using cypress.

2025-03-19 00:23 UTC, williamjallen requested changes
Looks pretty reasonable overall.  A few code comments to address and then this should be good to go.

2025-03-19 00:23 UTC, williamjallen commented on site/app/controllers/PollController.php
> +        $web_socket_message = ['type' => 'poll_updated', 'poll_id' => $poll_id, 'socket' => 'student', 'message' => 'Poll updated'];
It's generally more readable to wrap large associative arrays.  An additional benefit of doing so is that the diff will be cleaner if someone edits the array in the future--the same reason why a trailing comma is useful.  The same applies below as well.

```suggestion
        $web_socket_message = [
            'type' => 'poll_updated',
            'poll_id' => $poll_id,
            'socket' => 'student',
            'message' => 'Poll updated',
        ];
```

2025-03-19 00:23 UTC, williamjallen commented on site/app/templates/polls/ViewPoll.twig
> +                    <script>
This logic should be moved to `site/public/js/polls.js` so it gets linted.

2025-03-19 00:23 UTC, williamjallen commented on site/app/templates/polls/ViewPoll.twig
> +                                const custom_response_submit = document.querySelector('.custom-response-submit');
I'm torn regarding whether using jQuery for this would be cleaner.  We usually use jQuery whenever possible, but this code seems generally ok to me.  Thoughts?

2025-03-19 00:23 UTC, williamjallen commented on site/app/templates/polls/ViewPoll.twig
>                  data[0].x.push("{{ option.getResponse()|replace({"\n": " ", "\r": " ", "\t": " "})|e('js') }}");
Let's not duplicate code here and instead assign the value of the twig expression to a constant.

2025-03-19 00:23 UTC, williamjallen commented on site/app/templates/polls/ViewPoll.twig
> +            }
Let's move these functions to `site/public/js/polls.js` so they get linted.  The rest of the code can probably stay for now, although it all needs a bit of a refactor eventually.

2025-03-19 14:51 UTC, jeffrey-cordero commented on site/app/templates/polls/ViewPoll.twig
> +                                const custom_response_submit = document.querySelector('.custom-response-submit');
The `polls.js` almost entirely uses JQuery methods compared to my initial implementation in Twig. We should focus more on standard JS methods on new work, but file consistency is more important here.

2025-03-19 21:08 UTC, martig7 approved these changes
I tested it in the same way again and it still worked, I can't comment on the code form changes since I lack experience in that aspect.

2025-03-25 21:48 UTC, williamjallen approved these changes
Code looks reasonable to me.

2025-03-27 02:29 UTC, merged