[Bugfix:System] Move Doctrine Proxy Install
Submitty/Submitty pull request #10263
Opened 2024-03-18 03:05 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Doctrine proxies are installed before composer gets updated. This causes issues when we update Doctrine related code and could potentially be using old proxies or modify code that relies on the newer code.

### What is the new behavior?
Doctrine proxies are created after composer install.

### Other information?
This should be merged before #10245

2024-03-18 17:11 UTC, williamjallen reviewed
Do you need to move these lines as well?  https://github.com/Submitty/Submitty/blob/bb040a431a750cb881d2ec7627726f9952f3a94d/.setup/install_submitty/install_site.sh#L176-L178

2024-03-21 03:06 UTC, williamjallen approved these changes

2024-03-21 03:53 UTC, MasterOdin requested changes
Reviewing the script, looks like these lines should also be moved down after we run `composer install` since it loads composer autoload:

https://github.com/Submitty/Submitty/blob/c4a2aa52653ba3799c00c6a422f2db276f8612a8/.setup/install_submitty/install_site.sh#L161-L162

2024-03-21 03:53 UTC, MasterOdin commented on .setup/install_submitty/install_site.sh
> +mkdir -p ${SUBMITTY_INSTALL_DIR}/site/cache/doctrine-proxy
I'd consider leaving this block where it was just so it's in the same block of deleting and recreating cache folders, where we'd benefit from DRY that up by using an array and a loop, vs all the repetition.

2024-03-22 12:21 UTC, MasterOdin approved these changes

2024-03-22 12:21 UTC, merged