[UI/UX : Instructor UI] User resizing markdown text area fixed to vertical only.
Submitty/Submitty pull request #10295
Opened 2024-03-29 19:29 UTC by itssandeepverma

User resizing markdown text area #10008

 ### What is the current behavior?
Markdown textboxes that can be resized by the user can be expanded as much or as little as possible. I assumed it's supposed to stay fixed with auto resizing or the user is only suppose to be able to resize vertically.

### What is the new behavior?
It is now fixed to auto resizing or user is allowed to resize vertically only. 

### Other information?

Screenshots of the made changes. 

![image](https://github.com/Submitty/Submitty/assets/31655052/3e5b5c4f-4860-4dd2-8f7c-f851940775d3)
![image](https://github.com/Submitty/Submitty/assets/31655052/b555a781-0d88-4b84-a0b2-83c73b5cffc5)

Checked by running on remote server.

2024-03-29 19:32 UTC, ArnavPawar requested changes
This fix already has been made it is a duplicated PR. I will attach the PR that is associated with this in a bit.

2024-04-01 19:05 UTC, itssandeepverma commented
> This fix already has been made it is a duplicated PR. I will attach the PR that is associated with this in a bit.

Kindly mention it. Thanks

2024-04-02 20:14 UTC, 04vmatsibekker requested changes

2024-04-02 20:14 UTC, 04vmatsibekker commented on site/app/templates/admin/Configuration.twig
> +
remove space here, and put styling into a css file

2024-04-02 20:14 UTC, 04vmatsibekker commented on site/app/templates/admin/Configuration.twig
> +        <textarea class="config-row" name="course_email" id="course-email" style = "resize:vertical ;">{{ fields['course_email'] }}</textarea>
put styling into css file

2024-06-03 18:40 UTC, zacharymnp approved these changes

2024-06-04 04:07 UTC, merged