[Refactor:RainbowGrades] Refactor getDisplay
Submitty/Submitty pull request #10321
Opened 2024-04-02 17:16 UTC by ziesski

Inline the $isUsed variable inside the array directly, instead of declaring it before. 
More concise, enhance readability.

2024-04-04 18:01 UTC, justin-sadakhom requested changes
Good uses of variable names, ternary operator, and inline function call to make the code more readable. See my comment for a suggestion.

2024-04-05 19:24 UTC, ArnavPawar approved these changes
looks fine. Just doing the same code but changing the variable names. Could be less lines but its fine.

2024-04-05 19:25 UTC, ArnavPawar requested changes
correction ^ just fix changes from justin and it should be good

2024-04-05 20:34 UTC, ziesski commented on site/app/models/RainbowCustomization.php
> +        $allowedDisplayOptions = RainbowCustomizationJSON::allowed_display;
good catch, thanks!

2024-04-07 15:47 UTC, justin-sadakhom requested changes
Sorry, just one last variable left to change

2024-04-07 15:47 UTC, justin-sadakhom commented on site/app/models/RainbowCustomization.php
> +        foreach ($allowed_display_options as $optionId) {
You missed `$optionId`

2024-04-27 07:00 UTC, williamjallen approved these changes

2024-04-27 07:19 UTC, merged