[Bugfix:CourseMaterials] Disables ability to scroll on popup on manage grades/students
Submitty/Submitty pull request #10362
Opened 2024-04-16 17:33 UTC by RayReyRam

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Previously there was an ability, when a popup was open to scroll in the background behind/around the modal. 
related to #10200

### What is the new behavior?

On the instructor side in the sections manage grader and manage students when clicking on a popup the scrolling ability is disabled and reenabled when out of the popup 

### Other information?
To test enter as instructor, on side bar look for manage grader and or manage student open the popups there

2024-04-16 19:21 UTC, JoJo-ESC approved these changes
Functionality checked. All possible pop up opportunities checked.

2024-04-16 19:23 UTC, JoJo-ESC reviewed
Functionality checked. All popups checked in the process of review. fIx the test issue and ill approve.

2024-04-16 21:37 UTC, jeffrey-asm commented on site/public/js/directory.js
> +    showPopup('#download-form');
For all the JS files referencing this method, just add the method to the global comment at the top of the file like /* global ... showPopup */ and these errors will go

2024-04-16 21:42 UTC, jeffrey-asm requested changes
Most of the changes look good, just fix the linting issues and there may be a potential issue where the "Upload Student Photos" still allows scrolling on the student photos page popup, but I'm not sure if this page was a part of the issue.

2024-04-18 23:17 UTC, RayReyRam commented
> Most of the changes look good, just fix the linting issues and there may be a potential issue where the "Upload Student Photos" still allows scrolling on the student photos page popup, but I'm not sure if this page was a part of the issue.

Is this upload student photos button in the mange student section?

2024-04-18 23:27 UTC, jeffrey-asm commented
> > Most of the changes look good, just fix the linting issues and there may be a potential issue where the "Upload Student Photos" still allows scrolling on the student photos page popup, but I'm not sure if this page was a part of the issue.
> 
> Is this upload student photos button in the mange student section?

No, but they are related, so it would make reasonable to address it.

2024-06-04 16:07 UTC, ZheyuDeng approved these changes
Tested on Chrome works for me. The issue in user profile should be addressed in different pr

2024-06-04 16:46 UTC, merged