[Refactor:Autograding] Remove system program check for docker
Submitty/Submitty pull request #10360
Opened 2024-04-16 16:52 UTC by cjreed121

### What is the current behavior?
Only existing programs in the allowed list can be run in the jailed sandbox or in a container.

### What is the new behavior?
If we are grading inside docker, any command/program is allowed to be run. Docker gives us a more secure environment so we don't need to be as restrictive on what we can run.

### Other information?
Tested locally that this does allow other programs

2024-04-19 15:39 UTC, thegame615 approved these changes
Seems good to me. Just don't know if this is what Barb wants, but I'm assuming you checked with her.

2024-04-19 19:00 UTC, DarthNyan requested changes

2024-04-19 19:00 UTC, DarthNyan commented on grading/execute.cpp
> +    return true;
It looks like full_path_executable isn't getting set here. When I tested, this was causing validate_program to return an empty string and the assertion on line 513 to fail in execution.

2024-06-21 14:50 UTC, micpap25 approved these changes
Tested, looks all good to me!

Rerun the tests at some point, the failing PR is flaky.

2024-06-21 16:46 UTC, merged