[Bugfix:StudentUI] Add warning for unaligned time setting
Submitty/Submitty pull request #10469
Opened 2024-05-27 13:05 UTC by Xiayucheng1212

#fixes 10440

### What is the current behavior?
No banner warn the unsynchronized time settings between server and browser.

### What is the new behavior?
If the difference between server time and browser time larger than 2 min, show the banner.

2024-05-27 19:13 UTC, skara9 requested changes
Code looks mostly correct, but fails due to errors. Remember to test that your feature works as intended before marking your PR for review.
After applying the changes below, the message appears properly.

2024-05-27 19:13 UTC, skara9 commented on site/app/templates/GlobalHeader.twig
> +    <script>
Need to move all this code into a document load listener, or it won't be able to manipulate the element.

2024-05-27 19:13 UTC, skara9 commented on site/app/templates/GlobalHeader.twig
> +            document.querySelector('#server-time-not-aligned').removeAttr('hidden');
```suggestion
            document.querySelector('#server-time-not-aligned').removeAttribute('hidden');
```
'Attr' is jQuery

2024-06-12 03:19 UTC, ziesski approved these changes
After studying the code, I noticed that while Date.now() returns Unix epoch in user's local time zone, and server_time will provide Unix timestamp as well. So they are both derived from same epoch & UTC, and we can conclude that user's local time zone doesn't matter. 

I tried testing changing time on my mac, change from submitty profile page, change from my terminal (VM) and they behave as expected

2024-06-12 20:52 UTC, skara9 approved these changes

2024-06-12 20:52 UTC, merged