Rainbow customization accessibility
Submitty/Submitty pull request #10515
Opened 2024-06-06 14:29 UTC by zacharymnp

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Resolves #10505
HTML validator does not catch issues with Rainbow Grades Customization.

### What is the new behavior?
HTML validator catches issues with Rainbow Grades Customization, with no visual UI changes (only those that affect accessibility).

### Other information?

Cypress Accessibility tests pass for Rainbow Grades Customization, and the site is visually unchanged.

2024-06-06 14:56 UTC, powe97 requested changes
Padding to the left of `USER ID` in the plagiarism penalty table is missing, and the table headers are misaligned with the content.
![image](https://github.com/Submitty/Submitty/assets/116031952/0a8ca9f9-a4db-42b4-9237-6813913f4236)

2024-06-07 15:48 UTC, zacharymnp commented
The padding was already missing, so I'm inclined to leave it as-is.

2024-06-07 16:24 UTC, powe97 approved these changes

2024-06-07 16:59 UTC, williamjallen approved these changes
The changes seem reasonable to me.  I didn't test manually.

2024-06-07 17:13 UTC, merged