[Feature:Developer] Update ESLint to 9.4.0
Submitty/Submitty pull request #10538
Opened 2024-06-12 16:28 UTC by dorian451

This update includes updating our ESLint config to the new [flat config](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-file) format, so that we can benefit from ESLint updates now and in the future.

2024-06-12 18:41 UTC, dorian451 commented
It appears that a lot of the styling rules we had enabled before this change weren't working properly, 2,443 of the errors in the last js-lint check were style errors caused by updated versions of the rules that we had "enabled" before.

2024-06-13 19:10 UTC, dorian451 commented
As discussed in our meeting on 6/12/24, I'll defer the updates to the style rules, and put them in another PR.

2024-06-14 20:33 UTC, williamjallen reviewed
Can you please update the PR description with information about any behavior changes you've made?  For example, it looks like you've disabled the `no-unused-vars` rule.

2024-06-17 14:17 UTC, dorian451 commented
That rule was already off before; the new update added it to the list of recommended rules, so there's no behavior change. If I were to enable it,  it would create 293 new linting errors that weren't there with the old config

2024-06-18 02:03 UTC, williamjallen requested changes
Good to merge once the typo is addressed.

2024-06-18 15:49 UTC, dorian451 commented on site/eslint.config.js
> +        ignores: ['cypress/support/e2e.js', 'cypress/plugins/index.js', 'public/js/notebook_builder/widgets/widget.js'],
Fixed in a1e148a903d78a43bf612f0a0644508df1397214

2024-06-18 20:18 UTC, williamjallen approved these changes
Good to merge if tests pass

2024-06-19 18:53 UTC, merged