[Feature:System]  Revamp worker setup and fix QEMU
Submitty/Submitty pull request #10530
Opened 2024-06-10 18:04 UTC by skara9

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Worker configuration currently fails on QEMU due to lack of support for private networking.

### What is the new behavior?
The QEMU plugin has been modified to add support for socket networking.
The worker management configuration has been revamped to better accomodate the networking needs of the new QEMU plugin setup.

Testing instructions:
* Run `vagrant workers generate` to generate the worker machines
* (If on QEMU macOS) Run `vagrant workers start` in a separate terminal to start the network socket server
* Run `vagrant workers up` to boot up the worker machines

In general, all vagrant commands for interacting with workers should include `vagrant workers`.
Vagrant commands for interacting with the main submitty machine should just be `vagrant`.

2024-06-19 08:44 UTC, GO-viper7 commented
Please request a review after this PR gets out of draft.

2024-06-21 15:20 UTC, skara9 commented
@ziesski When you install homebrew, it gives you a command to update your PATH. You may have missed this step.

2024-06-21 15:37 UTC, ziesski commented
It has been long while since I installed homebrew. 

<img width="741" alt="Screen Shot 2024-06-21 at 11 33 17 AM" src="https://github.com/Submitty/Submitty/assets/123261952/4a27a959-9fb0-49ed-b6de-40ef8eaa35ae">

This is my current `HOMEBREW_PREFIX` What do you want me to update it to.

2024-06-25 11:47 UTC, GO-viper7 reviewed
So, I was already on workers set up
Thus I removed only the worker-VM manually from GUI and ran the commands you mentioned above
You can see the result in the screenshot below  
It probably has an issue with the ssh connection or Do I need to remove even the primary machine to try this ?

![image](https://github.com/Submitty/Submitty/assets/81346327/037077b2-a642-45fd-9c30-0322ded4821d)

2024-07-01 13:51 UTC, ziesski commented
@skara9 I am doing this time on my M3 MacOS 14, qemu, and getting below error. this is after I did `vagrant destroy`
Could you tell me what is wrong? 
<img width="1447" alt="스크린샷 2024-07-01 오전 9 50 42" src="https://github.com/Submitty/Submitty/assets/123261952/caaaed19-ab96-4f78-b161-c52a8273d199">

2024-07-07 16:54 UTC, GO-viper7 approved these changes
I followed the testing instructions on Windows
All the commands show expected results, couldn't find any errors in CLI
and FYI, here's my `workers.json`
```json
{
    "version": 2,
    "provider": "virtualbox",
    "workers": {
        "worker-1": {
            "ip_addr": "192.168.56.2",
            "ssh_port": 2241
        }
    }
}
```

2024-07-10 19:23 UTC, dorian451 approved these changes
I think it works

2024-07-11 17:28 UTC, ziesski commented
Tested on intel Mac OS 12, works.
Will test on M3 once @skara9 provides the fix.

2024-07-15 17:02 UTC, ziesski commented
<img width="1033" alt="스크린샷-2024-07-15-오전-11 51 50" src="https://github.com/user-attachments/assets/100f6e37-3666-44bb-a858-a0d2a3ce12eb">
This is what I get after vagrant workers up, is this expected?
@skara9

2024-07-22 15:28 UTC, bmcutler commented
@skara

Notes on instructions above

* Please start with "vagrant destroy" (if you have an existing vagrant VM)
...  that is, assuming you must destroy the main VM first?  But maybe you don't?  I was getting errors, but I'm just starting to go through these steps.

* BASE=1 is the old version.  We switched to FROM_SCRATCH=1

* Where do I specify the # of workers?  These instructions are replacing the old instructions which had that as a clear option
https://submitty.org/developer/getting_started/worker_vm

2024-07-22 17:22 UTC, skara9 commented
@bmcutler You don't need to destroy the main VM for setting up workers, but you will have to reprovision it at the end because the installation scripts on the main still send the SSH key to the workers.

For multiple workers, it is `vagrant workers generate -n X`, this is documented in the new instructions (not merged yet).

2024-07-24 17:23 UTC, bmcutler commented
@skara9 
Please resolve conflicts

2024-08-12 10:03 UTC, GO-viper7 commented
@skara9 
I followed the testing instructions and here's what I got in windows 
Also, I made sure to set FROM_SCRATCH=1, as you have mentioned current prepackaged VM does not support workers.
It still didn't work as intended.

![image](https://github.com/user-attachments/assets/53906161-fc57-43ad-a0fd-85e2b8a9f4c9)

2024-08-12 10:11 UTC, GO-viper7 commented on workers.sh
> +fi
It only checks for Linux / MacOS
May be this is the reason I'm failing on Windows.

2024-08-16 18:59 UTC, bmcutler requested changes
I tested it, and with tweaks to the instructions, I did get this to work with 1 worker machine, and successfully share autograding between primary & 1 worker on an M1 mac.

2024-08-16 18:59 UTC, bmcutler commented on .setup/bin/refresh_vagrant_workers.py
> +os.system('systemctl restart submitty_autograding_shipper && systemctl restart submitty_autograding_worker')
Don't include autograding restart in this script

2024-08-16 18:59 UTC, bmcutler commented on .setup/bin/refresh_vagrant_workers.py
> +print("Generating SSH credentials...")
add a comment explaining what steps from the (non-vagrant) sysadmin instructions these is mimicing.
https://submitty.org/sysadmin/installation/worker_installation

2024-08-16 18:59 UTC, bmcutler commented on .setup/bin/refresh_vagrant_workers.py
> +SUBMITTY_REPOSITORY = os.environ['SUBMITTY_REPOSITORY']
these environment variables don't exist on production, let's not use this here...

2024-08-16 18:59 UTC, bmcutler commented on .setup/bin/refresh_vagrant_workers.py
> +import os
this script should only be run on vagrant, let's add a check towards the top of the file to make sure this isn't accidentally run on production.  (this script could be damaging to a production install)

2024-08-16 18:59 UTC, bmcutler commented on .setup/install_system.sh
> +alias refresh_vagrant_workers='python3 /usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/refresh_vagrant_workers.py'
I don't think this alias is necessary to add.
(I also believe recreate sample courses alias should only be on vagrant systems, not on production)

2024-10-22 21:08 UTC, williamschen23 approved these changes
Did not look at the code, works on m2 mac

2025-06-23 17:53 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    print("Error: could not find home directory for daemon user")
Should we not also `exit(1)` at this point to prevent subsequent failures in the SSH key removals?

2025-06-23 17:55 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +shutil.rmtree(os.path.join(DAEMON_HOME, b'.ssh'), True)
Removing the entire directory seems risky for existing machines. Should we not only delete the SSH files being modified in the following lines?

2025-06-23 18:03 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
`StrictHostKeyChecking=no` makes the script vulnerable to MITM attacks as this will trust any host claiming a given worker machine.

2025-06-23 18:06 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
We should also verify the process exit status code.

2025-06-23 18:41 UTC, jeffrey-cordero commented on Vagrantfile
> +def mount_folders(config, mount_options, type = nil, host = '10.0.2.2')
This default host may not work for non-VirtualBox instances, but I'll test this with Qemu.

2025-06-24 01:28 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
Yeah, I think this flag was kept in from the really old single worker config (pre v1). The general idea was that our devs are going to be reprovisioning worker VMs back up with the same addresses, and host key checking means our script will fail on setting up the SSH connection between the main VM and workers.

Now that we're wiping known hosts, we're probably in the clear to remove this though.

2025-06-24 01:28 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +shutil.rmtree(os.path.join(DAEMON_HOME, b'.ssh'), True)
SSH dir for the daemon user should be managed entirely by this script; i.e. if there's anything else in there it would be a concern. Good call in general, but wiping it in this case actually saves us from potential trouble.

2025-06-24 01:33 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    print("Error: could not find home directory for daemon user")
Good catch, fixed.

2025-06-24 01:35 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
Could throw in a exit code check here, I just didn't think it was necessary. If the scp errors but the ssh works we don't really lose anything, right?

2025-06-24 13:12 UTC, Chriun commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
Just tested and it seems that we do need `-o StrictHostKeyChecking=no` for scp at least, otherwise the host fails connection for the workers as a result of known hosts being empty. We couuld have a secure alternative for this by using ssh-keyscan on the worker and adding it directly to the known hosts. but I don't think MITM is that much of a concern considering this setup is purely local.

2025-06-24 13:27 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +shutil.rmtree(os.path.join(DAEMON_HOME, b'.ssh'), True)
My knowledge of this worker-to-main machine SSH connection workflow is lacking a bit. I just noted it because system administrators or developers could change the contents with root privileges, but I assume this isn't a common scenario.

2025-06-24 13:27 UTC, Chriun commented on .setup/bin/refresh_vagrant_workers.py
> +    json.dump(new_autograding_data, file)
Having indent=4 here would be really helpful here in terms of formatting the json. Currently, it dumps it all into a single line which is not pretty.

2025-06-24 13:47 UTC, jeffrey-cordero commented on vagrant-workers/generate_workers.py
> +            data['ssh_port'] = args.base_port + i
I would suggest handling conflicting ports by finding the next suitable port and potentially logging the conflict to the terminal.

2025-06-24 13:50 UTC, jeffrey-cordero commented on vagrant-workers/generate_workers.py
> +            data['mac_addr'] = args.mac_prefix + ":%02x:%02x:%02x" % tuple(random.randint(0, 255) for v in range(3))
Though the risk is near zero, adding functionality to handle conflicting MAC addresses would add robustness. On macOS, you can run `ifconfig | grep ether | awk '{print $2}'` to list all existing addresses on a new line.

2025-06-24 14:00 UTC, Chriun reviewed
Works on Windows 10. I did run into problems initially with the setup since I was building the pre-packaged vm instead of from scratch. I think this should be highlighted in the documentation as well.

2025-06-24 14:26 UTC, jeffrey-cordero commented on vagrant-workers/workers.py
> +                with urllib.request.urlopen(f'https://github.com/Submitty/vagrant-qemu/releases/download/v{PLUGIN_VERSION}/vagrant-qemu-{PLUGIN_VERSION}.gem') as res:
This does not work on macOS for me.

```bash
➜  Submitty git:(qwork) ✗ vagrant workers up
Updating QEMU plugin...
Traceback (most recent call last):
  File "/Users/jeffreycordero/Developer/open-source/Submitty/vagrant-workers/workers.py", line 145, in <module>
    main()
    ~~~~^^
  File "/Users/jeffreycordero/Developer/open-source/Submitty/vagrant-workers/workers.py", line 122, in main
    with urllib.request.urlopen(f'https://github.com/Submitty/vagrant-qemu/releases/download/v{PLUGIN_VERSION}/vagrant-qemu-{PLUGIN_VERSION}.gem') as res:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 527, in error
    result = self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 720, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 495, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/urllib/request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

I was able to fix the authorization issue by adding the user agent to the headers of the request:

```python
with urllib.request.urlopen(urllib.request.Request(f'https://github.com/Submitty/vagrant-qemu/releases/download/v{PLUGIN_VERSION}/vagrant-qemu-{PLUGIN_VERSION}.gem', headers={'User-Agent': 'Submitty/1.0'})) as res:
```

2025-06-24 14:35 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
I originally noted this because it could be a vulnerability for production environments. This should be inspected by someone with more senior-level security experience, but I think the original approach is fine because it is similar to the existing connection command.

```bash
$su submitty_daemon -c "sshpass -p 'submitty' ssh-copy-id -i ~/.ssh/id_rsa.pub -o StrictHostKeyChecking=no submitty@${IP}"
```

2025-06-24 14:39 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    shutil.copyfile(f"{SUBMITTY_REPOSITORY}/.vagrant/machines/{name}/{provider}/private_key", f"/tmp/worker_keys/{name}")
This will fail if the file doesn't exist on the worker machine. I'd recommend wrapping this in a `try-catch`, where if the file doesn't exist, create it in the exception block, or update the instructions to ensure `sudo touch /usr/local/submitty/GIT_CHECKOUT/Submitty/.vagrant/machines/<worker>/<provider>/private_key` is run before running the script.

```bash
root@ubuntu:/usr/local/submitty# refresh_vagrant_workers
Loading existing data...
Done loading data

Generating SSH credentials...
Done generating

Attempting to connect to worker-1
Traceback (most recent call last):
  File "/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/refresh_vagrant_workers.py", line 52, in <module>
    shutil.copyfile(f"{SUBMITTY_REPOSITORY}/.vagrant/machines/{name}/{provider}/private_key", f"/tmp/worker_keys/{name}")
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/submitty/GIT_CHECKOUT/Submitty/.vagrant/machines/worker-1/qemu/private_key'`
```

2025-06-24 15:09 UTC, jeffrey-cordero commented on Vagrantfile
> +          mount_folders(override, [], 'smb', ENV.fetch('GATEWAY_IP', '10.0.2.2'))
This will not work at all if `GATEWAY_IP` is not defined. This may be in the instructions somewhere, but if not, please append it. This should be set to the local host IP on macOS because `10.0.2.2` is the default host gateway IP used by VirtualBox’s NAT networking.

2025-06-24 15:23 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"ssh -i /tmp/worker_keys/{name} root@{data['ip_addr']} \"chown {SUPERVISOR_USER}:{SUPERVISOR_USER} /tmp/workerkey && su {SUPERVISOR_USER} -c \\\"mkdi
I'm infinitely blocked when using SSH from both local and main machines.

`ssh: connect to host <Worker IP> port 22: Connection refused`

This could be a networking issue with Qemu within the Vagrant file, but I'm a bit stuck on finding the right solution to this macOS-specific issue.

```bash
$Submitty git:(qwork) ✗ ping <Worker IP>             
PING <Worker IP>: 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
ping: sendto: No route to host
```

2025-06-24 16:01 UTC, jeffrey-cordero commented on Vagrantfile
> +          qe.ssh_host = data[:ip_addr]
For some reason, on Qemu, the installation script for the workers only invokes for `"127.0.0.1"` as any other IP leads to connection refusal. Not sure if this works for anyone else on macOS.

2025-06-24 16:08 UTC, jeffrey-cordero commented on Vagrantfile
> +          qe.ssh_host = data[:ip_addr]
This also only works, I see, when I remove the hardcoded file descriptor line.

2025-06-25 02:37 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +shutil.rmtree(os.path.join(DAEMON_HOME, b'.ssh'), True)
Yes, idea is they shouldn't be changing it.

2025-06-25 02:38 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    shutil.copyfile(f"{SUBMITTY_REPOSITORY}/.vagrant/machines/{name}/{provider}/private_key", f"/tmp/worker_keys/{name}")
I'm assuming that output is because you have a worker-1 configured but not provisioned, right?

2025-06-25 02:43 UTC, skara9 commented on Vagrantfile
> +          mount_folders(override, [], 'smb', ENV.fetch('GATEWAY_IP', '10.0.2.2'))
This variable is set by script, user shouldn't be touching it. If it's not set, that's intentional, and it will use `10.0.2.2`, which is the host gateway from the qemu VM.

2025-06-25 02:43 UTC, skara9 commented on vagrant-workers/workers.py
> +                with urllib.request.urlopen(f'https://github.com/Submitty/vagrant-qemu/releases/download/v{PLUGIN_VERSION}/vagrant-qemu-{PLUGIN_VERSION}.gem') as res:
It's strange that a user agent header would solve a 403. Have you retried without this change to make sure it wasn't just a temporary issue on GitHub's side?

2025-06-25 02:45 UTC, skara9 commented on Vagrantfile
> +          qe.ssh_host = data[:ip_addr]
If you're referring to ssh_host on this line, that can't be set to localhost. It should be the address of the worker VM.

2025-06-25 02:46 UTC, skara9 commented on Vagrantfile
> +          qe.ssh_host = data[:ip_addr]
What do you mean by file descriptor line? And what changes did you make to the workers.json?

2025-06-25 02:52 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"ssh -i /tmp/worker_keys/{name} root@{data['ip_addr']} \"chown {SUPERVISOR_USER}:{SUPERVISOR_USER} /tmp/workerkey && su {SUPERVISOR_USER} -c \\\"mkdi
If the worker IP isn't up, that's a networking issue.

2025-06-25 03:09 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"scp -i /tmp/worker_keys/{name} -o StrictHostKeyChecking=no ~/.ssh/id_rsa.pub root@{data['ip_addr']}:/tmp/workerkey"])
I'll just throw the flag back in for now then, we can deal with host keys later if we want to.

2025-06-25 03:40 UTC, skara9 commented
@Chriun 
> Works on Windows 10 with 1 and 3 workers. I did run into problems initially with the setup since I was building the pre-packaged vm instead of from scratch. I think this should be highlighted in the documentation as well.

Ideally once this is merged we can package the worker setup as well.

2025-06-25 11:47 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    shutil.copyfile(f"{SUBMITTY_REPOSITORY}/.vagrant/machines/{name}/{provider}/private_key", f"/tmp/worker_keys/{name}")
I assume that is the case. I followed your documentation steps, but I assume I need to follow the worker installation steps first - https://submitty.org/sysadmin/installation/worker_installation?

2025-06-25 11:52 UTC, jeffrey-cordero commented on Vagrantfile
> +          qe.ssh_host = data[:ip_addr]
I mapped localhost to the worker IP and the hard-coded port within the worker.json, and it worked. I'll retry the entire process today. SSH should work on localhost as the worker VM was open on port 22, but this is not the correct approach for socket networking in this case.

2025-06-25 12:51 UTC, jeffrey-cordero commented on vagrant-workers/workers.py
> +                with urllib.request.urlopen(f'https://github.com/Submitty/vagrant-qemu/releases/download/v{PLUGIN_VERSION}/vagrant-qemu-{PLUGIN_VERSION}.gem') as res:
It must have been some server issue on GitHub's end that potentially corrupted my setup yesterday, leading to many issues. I had to run `vagrant plugin expunge --force` and no errors show up today.

2025-06-25 13:05 UTC, jeffrey-cordero commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"ssh -i /tmp/worker_keys/{name} root@{data['ip_addr']} \"chown {SUPERVISOR_USER}:{SUPERVISOR_USER} /tmp/workerkey && su {SUPERVISOR_USER} -c \\\"mkdi
Probably. I'm following all your exact steps, and I'm still stuck in the SSH connection process now. I'll call it quits here and assume this works on your end.

```bash
➜  Submitty git:(qwork) vagrant workers up      
Bringing machine 'worker-1' up with 'qemu' provider...
==> worker-1: Checking if box 'perk/ubuntu-2204-arm64' version '20230712' is up to date...
==> worker-1: Importing a QEMU instance
    worker-1: Creating and registering the VM...
    worker-1: Successfully imported VM
==> worker-1: Preparing SMB shared folders...
    worker-1: You will be asked for the username and password to use for the SMB
    worker-1: folders shortly. Please use the proper username/password of your
    worker-1: account.
    worker-1:  
    worker-1: Username (jeffreycordero):
    worker-1: Password (will be hidden):
==> worker-1: Warning! The QEMU provider doesn't support any of the Vagrant
==> worker-1: high-level network configurations (`config.vm.network`). They
==> worker-1: will be silently ignored.
==> worker-1: Starting the instance...
==> worker-1: Waiting for machine to boot. This may take a few minutes...
    worker-1: SSH address: <IP>:22
    worker-1: SSH username: vagrant
    worker-1: SSH auth method: private key
    [BLOCKED INDEFINITELY]
```

2025-06-25 14:00 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    w = subprocess.run(['su', DAEMON_USER, '-c', f"ssh -i /tmp/worker_keys/{name} root@{data['ip_addr']} \"chown {SUPERVISOR_USER}:{SUPERVISOR_USER} /tmp/workerkey && su {SUPERVISOR_USER} -c \\\"mkdi
Well if you're reviewing it, you should make sure to get it working on your end.
If it adds to our troubleshooting steps or highlights something to clarify in docs, that would prevent future devs from getting stuck wherever you did.

In case you need any help debugging, you can message me on Zulip.

2025-06-25 14:30 UTC, skara9 commented on .setup/bin/refresh_vagrant_workers.py
> +    shutil.copyfile(f"{SUBMITTY_REPOSITORY}/.vagrant/machines/{name}/{provider}/private_key", f"/tmp/worker_keys/{name}")
Nope, that is for system administrators not developers.

2025-07-25 19:20 UTC, bmcutler commented
NOTE:  This PR works on MacOS 14 and below.  We will open an issue describing the problems with MacOS 15.

2025-07-25 19:20 UTC, merged