fix self_grading reference error
Submitty/Submitty pull request #10557
Opened 2024-06-14 17:25 UTC by manzil-infinity180

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Issue #10556 

<img width="1792" alt="Screenshot 2024-06-14 at 10 40 51 PM" src="https://github.com/Submitty/Submitty/assets/119070053/cf2e73e1-9c2e-4c72-8090-bf3a5283436b">

### What is the new behavior?

https://github.com/Submitty/Submitty/assets/119070053/c0ca516b-61af-4d25-87d0-31634c5370f0

### Other information?

2024-06-18 16:23 UTC, zacharymnp approved these changes

2024-06-18 17:57 UTC, bmcutler requested changes

2024-06-18 17:57 UTC, bmcutler commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +    function updateSubmitButton(valid_grader, valid_students, new_grader, grader_removed, button_id, error_div_id, self_grading) {
Shouldn't self_grading also be added to the comment above documenting each of the function arguments?

2024-06-19 18:35 UTC, bmcutler approved these changes
thanks for the fix!

2024-06-19 18:35 UTC, merged