[Feature:Submission] Hide Accessibility Text for Disabled
Submitty/Submitty pull request #10649
Opened 2024-06-30 22:12 UTC by sahilsuman933

Fix #10643

### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [X] Documentation has been updated/added if relevant
* [X] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
CodeMirror currently displays accessibility help text above all code boxes. This text is confusing in places where the code box is disabled and it is impossible to navigate to it.

### What is the new behavior?
This commit updates the `getLargeCodeMirror` function to conditionally display the accessibility help text only when the CodeMirror instance is enabled. This prevents confusion in scenarios where the code box is disabled and navigation is not possible.

![image](https://github.com/Submitty/Submitty/assets/34382211/dbf21029-63d0-4075-8bea-1d0391a4749b)

2024-07-02 03:40 UTC, williamjallen reviewed
Is it possible to detect whether the codemirror box can be navigated to on the client side alone?  It's true that the read-only boxes are currently correlated with the grading mode, but this is not necessarily guaranteed to be the case all the time.

2024-07-03 14:37 UTC, ZheyuDeng requested changes
Code looks good not seeing the changes for some reasons. Have tried running a full submitty_install and clearing cache. 
![image](https://github.com/Submitty/Submitty/assets/122962727/ad40c62a-5b3d-4f0f-91b9-6e235b1508f9)

2024-07-04 23:18 UTC, sahilsuman933 commented
> Code looks good not seeing the changes for some reasons. Have tried running a full submitty_install and clearing cache. ![image](https://private-user-images.githubusercontent.com/122962727/345466261-ad40c62a-5b3d-4f0f-91b9-6e235b1508f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzUzODcsIm5iZiI6MTcyMDEzNTA4NywicGF0aCI6Ii8xMjI5NjI3MjcvMzQ1NDY2MjYxLWFkNDBjNjJhLTViM2QtNGYwZi05MWI5LTZlMjM1YjE1MDhmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQyMzE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2Q2Njk1ZDhhMGE0OTRhYzg0ZDUwYWNkN2MxMjFkOWM2Y2RkNDVmZThhYjM5YWIxNzExOGI3ZDJkYzc4NTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.obEMW-udsR_mwnsXDPYYXfW32G7EPnL4bDQMYzXuR2E)

That's strange because I can see the change on my local environment. Can you please check on your end as well? @williamjallen﻿

2024-07-04 23:21 UTC, sahilsuman933 commented
Yes, we can do it on the client-side itself, but it will be a tedious task whereas this solution is more feasible. We just need to pass a new parameter `show_accessibility_msg`, which, by default, is true. So, in case we don't want it, we can just set the value to false or leave it as it is.
﻿
﻿
// @williamjallen

2024-07-11 16:51 UTC, ZheyuDeng approved these changes
Tested and works!
![image](https://github.com/Submitty/Submitty/assets/122962727/dfb7334e-be71-48b9-8dae-dad438ddd816)

2024-07-12 12:36 UTC, williamjallen approved these changes
The code looks reasonable to me, and I manually verified that the functionality works as expected.

2024-07-12 18:20 UTC, merged