[Bugfix:Autograding] Tolerance parse fix
Submitty/Submitty pull request #10688
Opened 2024-07-10 18:19 UTC by micpap25

Makes a fix on #8251 so it works with numbers that have non-period punctuation surrounding them will still be recognized as numbers.

2024-07-12 18:14 UTC, dorian451 approved these changes
Looks good to me

2024-07-13 14:32 UTC, ziesski approved these changes
Reviewed the code, and looks like it will recognize numbers numbers surrounded by non-period punctation, as described. Since it is cpp code, Barb should take another look before merging.

2024-07-15 14:37 UTC, bmcutler commented on grading/clean.cpp
> +      return str;
so you return the whole string if there is no number at all?
(this is not intuitive)

2024-07-15 14:38 UTC, bmcutler requested changes

2024-07-15 14:38 UTC, bmcutler commented on grading/clean.cpp
> +std::string isolateAlphanumAndNumberPunctuation(const std::string &str) {
this function is somewhat confusing in purpose and should at least have a comment at the start...

2024-07-15 21:46 UTC, bmcutler approved these changes
thanks!

2024-07-15 21:46 UTC, merged