fix - Markdown rendering: preprocess to ignore leading spaces
Submitty/Submitty pull request #10693
Opened 2024-07-11 06:45 UTC by boatnoah

### Please check if the PR fulfills these requirements:
* [ ] Tests for the changes have been added/updated (if possible)
* [x] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently, when users input Markdown text with 4 spaces or more, the Markdown parser incorrectly interprets these as code blocks.

### What is the new behavior?
The new behavior preprocesses Markdown content before rendering:
- Removes leading spaces from lines to prevent unintended code block formatting

### Other information?

This is not a breaking change. The modification enhances the existing functionality without altering the API or user interface significantly.

Testing was performed by:
1. Inputting Markdown text with various leading space configurations
2. Verifying that unintended code blocks are no longer created
3. Ensuring that intentional code blocks (marked with triple backticks) are still preserved and rendered correctly

<div>
    <a href="https://www.loom.com/share/b3c31ec340e84e0286b2c3f70c71cb09">
      <p>Course Settings - Sample - 10 July 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/b3c31ec340e84e0286b2c3f70c71cb09">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/b3c31ec340e84e0286b2c3f70c71cb09-with-play.gif">
    </a>
  </div>

2024-07-11 13:13 UTC, manzil-infinity180 commented
Fix your title pr
reference - https://submitty.org/developer/getting_started/make_a_pull_request

2024-07-11 19:21 UTC, bmcutler commented
@boatnoah 
Please edit your PR description to add a link to the issue that the PR is solving.

2024-07-12 18:26 UTC, bmcutler commented
@boatnoah 

FYI:  The phrase you added to the PR description will unfortunately NOT trigger the auto-close issue functionality in Github:
"This PR resolves this Issue https://github.com/Submitty/Submitty/issues/10634"

If you instead write:
"fixes #10634"
or
"closes #10634"
it will work.
When this PR is merged, the issue will be automatically closed.

2024-07-19 19:29 UTC, ZheyuDeng approved these changes
Tested locally fixed the problem

2024-07-22 18:46 UTC, ZheyuDeng requested changes
While this works when previwing, it still has code space enabled after posting it. I think we expected leading space to be ignored after posting it as well.

2025-06-13 05:36 UTC, bmcutler commented
closing this PR due to inactivity by original author.
If this is re-opened, please make sure that the description of how to reproduce the error is clearly documented.

2025-06-13 05:36 UTC, closed without merging