[Feature:InstructorUI] Use cookie for grade override and remove button
Submitty/Submitty pull request #10700
Opened 2024-07-11 19:28 UTC by ZheyuDeng

Fix #10676 

### What is the current behavior?
While instructor grade override page is similar to excused absence extension, users need to hit apply changes after selecting a gradable to see the data where as excused absence extension page directly shows the data and remember it with cookie.

### What is the new behavior?
Now it shows the data right after selecting the gradable and have cookie enabled.

2024-07-16 18:12 UTC, zacharymnp requested changes

2024-07-16 18:12 UTC, zacharymnp commented on site/app/templates/admin/GradeOverride.twig
> +<script src="/js/grade-override.js"></script>
This should be added in `GradeOverrideView.php` using `$this->core->getOutput()->addInternalCss('grade-override.js');`

2024-07-18 17:50 UTC, zacharymnp approved these changes

2024-07-18 21:08 UTC, ziesski approved these changes
After discussion, noticed cookie is used to remember last edited gradeable, so that when instructor comeback to the page, and have that gradeable page selected, this matches the excused absent page behavior. Code looks good.

2024-07-19 00:56 UTC, merged