[Feature:HelpQueue] Add cookie for office hour sliders
Submitty/Submitty pull request #10719
Opened 2024-07-16 17:43 UTC by ZheyuDeng

Fix #10590 

### What is the current behavior?
There are currently no cookies for office hour notification sliders. So when TA leave/refresh the page or even remove/restore a student from the queue it will goes back to default.

### What is the new behavior?
Now choices will be remembered.

https://github.com/user-attachments/assets/34dd2915-a9c1-4789-859a-987acc82d733

2024-07-16 18:02 UTC, zacharymnp requested changes

2024-07-16 18:02 UTC, zacharymnp commented on site/app/templates/officeHoursQueue/QueueFooter.twig
> +      document.getElementById('push-notification-switch').checked = push_notifications_enabled;
You should probably replace the ~4 uses of `document.getElementById()` that you added in this PR with JQuery.

2024-07-23 14:34 UTC, zacharymnp reviewed
Adding the `autoplay` attribute to the audio element in GlobalHeader.twig (~line 46) might fix the issue with the page requiring user interaction before playing sounds. It seems to work, although the behavior seems a little odd.

2024-07-23 15:19 UTC, ZheyuDeng commented
> Adding the `autoplay` attribute to the audio element in GlobalHeader.twig (~line 46) might fix the issue with the page requiring user interaction before playing sounds. It seems to work, although the behavior seems a little odd.

I think the auto play is just letting the sound play whenever things load instead of manually control it. I still get the DOM when sound is played.

2024-07-23 15:49 UTC, zacharymnp approved these changes
In that case, this works as well as it can at the moment.

2024-07-23 17:20 UTC, williamjallen approved these changes
Code looks reasonable to me, given the style of the surrounding code.  I did not test this manually.

It would be great if we could move most of the JS logic in this file to an external file so it gets linted automatically.  That should be done in a separate PR though.

2024-07-24 16:00 UTC, merged