Embedded iframes do not respect color theme
Submitty/Submitty pull request #10724
Opened 2024-07-17 05:06 UTC by KUNDAN1334

### What is the current behavior?
isssue #10713 Embedded iframes do not respect color theme #10713

### What is the new behavior?
The iframes within the TA grading interface now respect the user's chosen color theme.
The background and text color of the iframe content dynamically change to match the selected theme (light or dark).
The visual consistency of the TA grading interface is maintained, enhancing the user experience.

2024-07-17 19:07 UTC, micpap25 commented
PR does not seem to be accomplishing the stated goal: 
![image](https://github.com/user-attachments/assets/074f90c1-7223-4966-8b11-4fdc9b5600c9)

2024-07-17 19:08 UTC, micpap25 requested changes
Please let us know once you've made changes to address the above concern. Thank you!

2024-07-18 21:58 UTC, micpap25 requested changes
@KUNDAN1334 still does not work for me. Please post screenshots / video of it working for you in the future when you request a review, thank you!

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/2d0d46f1-06ae-40c0-8587-d5a0b4b10062">

2024-07-31 19:20 UTC, micpap25 commented
Hi @KUNDAN1334 do you intend to keep working on this PR? If not we can pick up the issue.

2024-08-04 03:14 UTC, KUNDAN1334 commented
@micpap25 done

2024-08-05 18:30 UTC, micpap25 commented
@KUNDAN1334 Breaks the CSS of the site. Please only commit after testing the PR on your end. Thank you.
![image](https://github.com/user-attachments/assets/603bb120-1dd6-4ff4-bda3-9fed4747ed99)

2025-04-25 20:25 UTC, bmcutler commented
closing due to lack of activity from author.
you may re-open if you address review comments.

2025-04-25 20:25 UTC, closed without merging