[Refactor:Developer] Remove key_to_click from buttons
Submitty/Submitty pull request #10740
Opened 2024-07-19 17:11 UTC by micpap25

Per Shail from #7819, remove all uses of `key_to_click` on buttons, where this class is redundant and serves no purpose since the functionality that `key_to_click` implements is the default for buttons.

2024-07-19 17:59 UTC, powe97 requested changes

2024-07-19 17:59 UTC, powe97 commented on site/app/templates/grading/electronic/AutogradingPanel.twig
> -        <button id="autograding-results-close-all" class="btn btn-default key_to_click" tabindex="0">Close All</button>
Remove the trailing space here. Looks good otherwise.

2024-07-19 18:01 UTC, powe97 requested changes

2024-07-19 18:01 UTC, powe97 commented on site/app/templates/grading/electronic/AutogradingPanel.twig
> +        <button id="autograding-results-close-all" class="btn btn-default " tabindex="0">Close All</button>
```suggestion
        <button id="autograding-results-close-all" class="btn btn-default" tabindex="0">Close All</button>
```

2024-07-19 18:01 UTC, powe97 commented on site/app/templates/grading/electronic/AutogradingPanel.twig
> +        <button id="autograding-results-close-all" class="btn btn-default " tabindex="0">Close All</button>
Looks good otherwise.

2024-07-22 16:15 UTC, ziesski approved these changes
Would have been nice if you cherry pick merged my commit, but its fine. The code changes seem reasonable to me. 

There should be a follow-up PR to address the issue with anchor tag, but it would have some stylistic changes, so we would need to review with care.

2024-07-22 16:16 UTC, micpap25 commented
> Would have been nice if you cherry pick merged my commit, but its fine. The code changes seem reasonable to me.

Didn't realize you could do this cross-PR, sorry!

2024-07-23 02:41 UTC, bmcutler commented
@micpap25 
Please fix version conflicts

2024-07-23 18:57 UTC, merged