[Testing:TAGrading] Rubric Grading Interface
Submitty/Submitty pull request #10755
Opened 2024-07-23 19:29 UTC by manzil-infinity180

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Currently no test for rubric/manual grading interface

### What is the new behavior?
Added test for rubric/manual grading interface

### Other information?

2024-07-23 19:30 UTC, manzil-infinity180 commented
In future we can verify it throw api test

2024-08-02 20:18 UTC, IDzyre requested changes

2024-08-02 20:18 UTC, IDzyre commented on site/cypress/e2e/Cypress-TAGrading/rubric_grading.spec.js
> +            .should('contain', 'Major errors in Read Me or Read Me missing');
```suggestion
        cy.get('[data-testid="component-64"]')
            .should('contain', 'Full Credit')
            .and('contain', 'Minor errors in Read Me')
            .and('contain', 'Major errors in Read Me or Read Me missing');
```

Same with other uses of chained should calls

2024-08-07 18:27 UTC, manzil-infinity180 commented on site/public/templates/grading/Component.twig
> +</div>
sorry ig not , i will change it

2024-08-07 19:20 UTC, IDzyre commented
Once you get the tests to pass, i'll do a final review and then merge if it looks good.

2024-08-13 18:32 UTC, IDzyre approved these changes
Looks good to me, once the new test names have passed, I will merge.

2024-08-13 19:37 UTC, merged