[Refactor:InstructorUI] Clean PollForm
Submitty/Submitty pull request #10769
Opened 2024-07-25 20:13 UTC by zacharymnp

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the new behavior?
Code in `PollForm.twig` moved to `polls.js` to allow linting and improve maintainability.

### Other information?

2024-08-22 17:18 UTC, ziesski requested changes
For some reason, when I test it locally, by trying to create new form from Submini polls page, I am unable to create new form. When I hit Add Poll button, I get ERR_SOCKET_NOT_CONNECTED, but in main branch I can create it.

2025-04-25 20:52 UTC, bmcutler commented
@zacharymnp what is the status of this PR?

2025-04-25 21:48 UTC, zacharymnp commented
This PR is more-or-less a draft. It could be deleted.

2025-04-25 22:55 UTC, closed without merging

2025-04-25 22:55 UTC, bmcutler commented
refactor PR, incomplete, Zachary says we can close it.