[Bugfix:RainbowGrades] add ClampGradeablesInBucket
Submitty/Submitty pull request #10765
Opened 2024-07-24 19:14 UTC by zacharymnp

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

Login to Instructor, then navigate to Grade Reports > Web-Based Rainbow Grades Customization.

### What is the current behavior?

The expected number of gradeables in a bucket can be set to any value. However, upon build, an error will be thrown if the expected number is set to a value below the current number of gradeables in the bucket.

### What is the new behavior?
Adds a clamp to the input that prevents a value that cause build to fail from being input.
https://github.com/user-attachments/assets/c1977c70-2351-4477-8b9c-eabe34b45153

### Other information?

2024-07-25 19:36 UTC, ziesski requested changes

2024-07-25 19:36 UTC, ziesski commented on site/public/js/rainbow-customization.js
> +// Forces the number of expected gradeables to be greater than or equal to the current number of gradeables
i think we should also add `displayerrormessage` that alerts the user why it shows this behavior.

2024-07-29 22:40 UTC, oliiso approved these changes
Works as expected.

2024-08-07 17:16 UTC, ziesski approved these changes
Looks good to me.

2024-08-08 21:39 UTC, merged