[Testing:Submission] Uncaught SyntaxError
Submitty/Submitty pull request #10787
Opened 2024-08-01 06:35 UTC by manzil-infinity180

### Please check if the PR fulfills these requirements:
Closes #10758

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

During testing for notebook view panel , when i add the notebook from notebook builder and move back to ta grading interface i am getting two uncaught syntaxerror
```js
Uncaught SyntaxError: Identifier 'showPopup' has already been declared
Uncaught SyntaxError: Identifier 'colorEvent' has already been declared
```
For `showPopup ` it is due to naming conflict, as we have variable and function with the same name 
For `colorEvent ` i did not get the possible reason for the syntax error

### What is the new behavior?
Fixes the both uncaught syntax error 
`colorEvent` is not used anywhere , so i wrap it inside the `emitEvent` function
And for `showPopup` its due to naming conflict, changed the variable name from `showPopup` to `show_popup`

### Other information?

2024-08-08 12:02 UTC, williamjallen requested changes
The `show_popup` changes look reasonable to me, but I want to make sure I understand why the other changes are necessary.  I haven't tested manually, but I'll do that next time I review.

2024-08-08 13:19 UTC, manzil-infinity180 commented on site/app/templates/grading/electronic/PDFAnnotationBar.twig
>          if(document.createEvent){
<img width="1728" alt="Screenshot 2024-08-08 at 6 24 19 PM" src="https://github.com/user-attachments/assets/270aef7d-601b-4eb5-af8c-61ae27954320">

So, the event which we are dispatch here is for the changing the color .

https://github.com/Submitty/Submitty/blob/f0dc54cb9388d7b505da2903fe4c66df8b7c0ebc/site/app/templates/grading/electronic/PDFAnnotationBar.twig#L33-L40

So i moved the part of code inside the function, it is not used anywhere and it is related to that function `emitEvent`

2024-08-13 19:15 UTC, williamjallen approved these changes

2024-08-13 19:15 UTC, williamjallen commented on site/app/templates/grading/electronic/PDFAnnotationBar.twig
>          if(document.createEvent){
Thanks for the explanation!

2024-08-13 19:22 UTC, merged