[Feature:InstructorUI] Capability / image buildtime error
Submitty/Submitty pull request #10839
Opened 2024-08-05 17:45 UTC by micpap25

Works on #10747 
Gives an error for gradeables at buildtime if the requested capability / image does not exist in the context of that gradeable.

![image](https://github.com/user-attachments/assets/65b4dc2d-fd83-4023-9dba-711529197f4f)

![image](https://github.com/user-attachments/assets/ee83ae00-f320-4a76-af8d-0446ee1fb76c)

To test, you can modify an existing config for a development course to either have a capability that does not exist or an image that does not exist and rebuild the gradeable for that course.

2024-08-07 15:19 UTC, micpap25 commented
There is an issue with this PR, in that the erroring process calls `exit(1)` which cancels the entire build, which is normal and fine for single builds but bad for the batch build that is called when the site is being installed (as some gradeables are expected to fail). There are a few solutions to this;
- Find and fix the batch build code (no idea where this is)
- Downgrade an image not being in the capability to a warning (i like this because building the gradeable then adding the image to a capability is a valid workflow)
- Remove the gradeables that are expected to fail from development and maybe migrate them to their own course

2024-08-08 20:30 UTC, micpap25 commented
@powe97 should work, please review!

2024-09-06 04:01 UTC, micpap25 commented
e2e testing needs at least 2 unused capabilities to work properly, so I added one to do so... please let me know if the name is acceptable.

2024-09-13 18:43 UTC, DarthNyan requested changes

2024-09-13 18:43 UTC, DarthNyan commented on grading/load_config_json.cpp
> +  }
Can we add behavior/error msg if we fail to open wfs?

2024-09-13 18:43 UTC, DarthNyan commented on grading/load_config_json.cpp
> +  }
same here

2024-09-13 18:43 UTC, DarthNyan commented on .setup/CONFIGURE_SUBMITTY.py
> +            capabilities.extend(["cpp", "python", "et-cetera", "notebook", "unsupported"])
What is this for?

2024-09-17 14:59 UTC, DarthNyan requested changes
I found this broke existing autograding examples, such as c_failure_messages and c_malloc_not_allowed. This occurred because "submitty/autograding-default:latest" is set as the default container when "container_image" is not specified, so any config running in jailed_sandbox mode on a machine lacking that image is expected to fail.

Probably good to discuss with Barb what the best fix is, as it will likely involve skipping this check for jailed_sandbox gradeables or editing a lot of existing examples.

I did confirm that it correctly failed to build when missing capabilities or images and correctly succeeded with a valid docker config.

2024-09-20 20:18 UTC, DarthNyan commented
Discussed with Barb. Best fix is to bypass the buildtime image check for non-docker gradables, but we still want to confirm capabilities exist.

2024-09-27 16:07 UTC, micpap25 commented
I thought the current goal was to dockerize all configs. Is that incorrect?

2024-09-27 16:38 UTC, bmcutler commented
@micpap25 

There are some cases of autograding that will run on the machine directly, outside of docker, in the jailed sandbox.  E.g., graphics grading that uses the graphics card & display.

@DarthNyan is pointing out that we have a default value for the docker container, even though we default the use of docker to false.  When use of docker is false, it doesn't make sense to check for the presence of the unused-for-this-gradeable, default docker container.

2025-06-13 14:49 UTC, Chriun requested changes
The functionality is good but it still does not pass integration checks. In addition the list of capabilities being checked does not encompass the entire list.

2025-06-13 14:49 UTC, Chriun commented on grading/load_config_json.cpp
> +  nlohmann::json capabilities_list = workers_json["primary"]["capabilities"];
It seems you're checking only the primary machine for all capabilities, which might not include all of them.

2025-06-13 14:49 UTC, Chriun commented on .setup/CONFIGURE_SUBMITTY.py
> +            "default":  [
Do we need to add this to the setup? I meant to highlight assigning additional capabilities for each image.

2025-06-20 16:10 UTC, bmcutler approved these changes

2025-06-20 16:10 UTC, merged