[Testing:RainbowGrades] Add RainbowGrades test to Github CI
Submitty/Submitty pull request #10879
Opened 2024-08-22 18:06 UTC by powe97

### What is the current behavior?
PR #10726 added rainbow grades Cypress tests, but since they were dependent on the SAMPLE course they do not run on Github CI.

### What is the new behavior?
This PR restructures the Cypress test to be runnable on CI. It uses the TESTING course from #10537 instead of SAMPLE. It also fixes a bug with the subtest "Enable viewing of rainbow grades and generating the rainbow grading", which appears to never work on a fresh system.

2025-02-07 21:03 UTC, IDzyre requested changes
A couple of small comments about the tests, but overall looks good. I look forward to having (at least some) RainbowGrades tests that run in CI.

2025-02-07 21:03 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/rainbow_grading.spec.js
Do we have any specific rules on where to declare functions/globals in javascript files? I always default to having them at the top of the file, but I am not entirely sure what Submitty's rules are. I believe that the location doesn't matter for the compiler, it's just a style preference.

2025-02-14 08:45 UTC, zacharymnp commented on site/cypress/e2e/Cypress-Gradeable/rainbow_grading.spec.js
> +    cy.get('[data-testid="display-grade-summary"]').should('be.visible').uncheck();
Changed in [a224dd2](https://github.com/Submitty/Submitty/pull/10879/commits/a224dd2cec3184ca6de3376ba0b8ac88d3877e87).

2025-02-14 08:46 UTC, zacharymnp commented on site/cypress/e2e/Cypress-Gradeable/rainbow_grading.spec.js
> +        cy.visit(['testing', 'reports', 'summaries']);
The first URL was for a HTTP request. Changed in [ae927c7](https://github.com/Submitty/Submitty/pull/10879/commits/ae927c7e422c5a6736bf34445e7bb19d11bd4409).

2025-02-23 21:46 UTC, IDzyre requested changes
One small comment about combining some tests.

Overall the overall tests look good. It would be nice to get another user who knows RainbowGrades to test the tests, and ensure that we are getting the best code coverage.

2025-02-23 21:46 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/rainbow_grading.spec.js
> +        cy.visit(['testing', 'gradeable', 'numeric', 'quick_link?action=release_grades_now']);
Ideally this would probably be a part of a different it() block, or in a before() block, but if it would be too difficult, its okay.

2025-04-04 02:45 UTC, IDzyre approved these changes
Test looks good, I don't know anything about RainbowGrades or what is being tested, so I would like someone who knows it to review also, and verify the functionality.

2025-04-06 03:21 UTC, williamjallen commented
@zacharymnp Do we need another review on this?  It seems simple enough to me, but like @IDzyre, I don't know much about this part of the codebase.

2025-04-08 02:45 UTC, merged