[Feature:Developer] Add eid al fitr duck
Submitty/Submitty pull request #10890
Opened 2024-08-27 21:12 UTC by ziesski

Welcoming all community members, embracing different cultures, adding festival of breaking the fast, eid al fitr duck. 

![스크린샷 2024-08-27 오후 5 12 51](https://github.com/user-attachments/assets/ad1ceadc-598a-48d3-8ad4-59356cf2627f)

2024-09-02 15:58 UTC, bmcutler requested changes
The date for this Eid al-Fitr changes every year.
Let's set this duck to display March 26 - April 2.  
(so it is visible for 1 week around the date for 2025).
And open a new issue to update this for future years
(either hard coding for specific years or algorithm for calculation)

2025-01-31 05:50 UTC, rafizamankhan commented
Submitty Duck Icons for March 2025

March 14 - March 20 Saint Patrick's Day
<img width="1421" alt="Mar 14 - Mar 20" src="https://github.com/user-attachments/assets/7c80da7d-ddba-4217-9881-9bbc5f097d59" />
 
March 26 - April 2 Eid-al-Fitr
<img width="1430" alt="Mar 26 - Apr 2" src="https://github.com/user-attachments/assets/4b1aa88e-b8e8-4eb7-9ec7-b8cf45691819" />

March 28 - April 3 International Transgender Day Of Visibility
<img width="1431" alt="Mar 28 - Apr 3" src="https://github.com/user-attachments/assets/52737409-32ec-4e0f-8228-336263a268d1" />

March Duck (Original)
<img width="1423" alt="March Duck" src="https://github.com/user-attachments/assets/d3bccaea-cee0-4a8a-af7b-f086ad4ef4d7" />

2025-01-31 22:31 UTC, rafizamankhan approved these changes
Submitty Icon For March 26 - April 2 (2025)

<img width="1430" alt="Mar 26 - Apr 2" src="https://github.com/user-attachments/assets/5e0e398a-02e9-4609-95c1-2c6450398e05" />

2025-02-03 20:21 UTC, bmcutler approved these changes

2025-02-03 20:22 UTC, merged