[Feature:Developer] Add transgender duck
Submitty/Submitty pull request #10891
Opened 2024-08-27 21:18 UTC by ziesski

Welcoming all community members, adding transgender flag duck called trans-duck
![스크린샷 2024-08-27 오후 5 18 24](https://github.com/user-attachments/assets/e5f04abf-5d6c-4d8c-bb8b-26b23f45038f)

2024-09-02 15:50 UTC, bmcutler requested changes
@ziesski 

International Transgender Day of Visibility is March 31.
Please set this duck to display March 28 - Apr 3,

2025-01-29 04:49 UTC, rafizamankhan commented
Submitty Duck Icons for April (Before adding [PR#10890](https://github.com/Submitty/Submitty/pull/10890))

March 28 - April 3 International Transgender Day of Visibility
<img width="1419" alt="March 28" src="https://github.com/user-attachments/assets/928e21d1-ed76-4229-a6e8-3bdb40b5ed8d" />

April 5 - Quantum Duck 
<img width="1416" alt="April 5" src="https://github.com/user-attachments/assets/37661a12-3203-4898-b076-25db37786624" />

April 24 - April 30 Arbor Day
<img width="1419" alt="April 24" src="https://github.com/user-attachments/assets/fb185efb-2b68-4a9c-93bb-7e3ec486b93f" />

April Duck (Flowers)
<img width="1421" alt="April Duck" src="https://github.com/user-attachments/assets/47499ffa-1c47-423e-8630-049a8c33e35f" />

[PR#10890](https://github.com/Submitty/Submitty/pull/10890) would add Eid-al-Fitr Duck between March 26 - April 2 for 2025. The overlap could be addressed by toggling between the icons.

2025-01-31 22:29 UTC, rafizamankhan approved these changes
Submitty Icon For March 28 - April 3

<img width="1419" alt="March 28" src="https://github.com/user-attachments/assets/bc55e53a-75f9-4b26-aa96-6fce536e6e51" />

2025-02-03 20:18 UTC, bmcutler approved these changes

2025-02-03 20:18 UTC, merged