Fix  #10895 fully and add tests
Submitty/Submitty pull request #10921
Opened 2024-09-07 16:12 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Attempting to modify a queue with an empty queue code will both fail at the html form validation level and at the server level.
#10895

### What is the new behavior?
Modifying a queue with an empty code will work as expected.

### Other information?
Tests have been updated to test both creation and modification of blank queue codes

2024-09-10 20:19 UTC, williamschen23 requested changes
Can you also make the student join and leave the blank queue? Also @IDzyre thoughts on changing the redirection limit here.

The other aspects of the PR works as intended.

2024-09-10 23:51 UTC, IDzyre commented
> Can you also make the student join and leave the blank queue? Also @IDzyre thoughts on changing the redirection limit here.
> 
> The other aspects of the PR works as intended.

If it is absolutely needed then I think it's okay, however if you can find a way to not then that would be ideal, as more redirects cause more time.

2024-09-11 21:16 UTC, lavalleeale commented
Yeah, I removed the line by splitting up the test, I think there might be a glitch in Cypress here where it's not that a single request has that many redirects, but since the test keeps redirecting from (or too I honestly don't know) the same url the count adds up over the course of the test.

2024-09-12 16:05 UTC, williamschen23 requested changes

2024-09-12 16:05 UTC, williamschen23 commented on site/cypress/e2e/Cypress-Feature/office_hours_queue.spec.js
> +        cy.login('student');
otherwise the PR looks good!

2024-09-13 16:19 UTC, williamschen23 approved these changes

2024-09-17 20:10 UTC, williamjallen approved these changes
Code looks good to me

2024-09-26 03:18 UTC, merged