Superuser accesss to AutogradingStatus page
Submitty/Submitty pull request #10956
Opened 2024-09-17 03:08 UTC by yanliw123

### What is the new behavior?
Allow superuser access to AutogradingStatus page through sidebar or link.
![image](https://github.com/user-attachments/assets/81d8b8f8-028d-43a3-83cd-e8df8a347a31)

2024-09-19 16:27 UTC, DarthNyan requested changes

2024-09-20 19:17 UTC, DarthNyan approved these changes
Looks good to me. Code makes sense.

2024-09-20 19:31 UTC, lavalleeale commented
Looks good to me, very simple change and I saw the issue too beforehand

2024-09-24 16:58 UTC, ziesski approved these changes
Reviewed, code looks good.

2024-09-26 03:17 UTC, merged