[Bugfix:InstructorUI] Fix error: 0 items for Numeric gradeable
Submitty/Submitty pull request #10967
Opened 2024-09-20 20:41 UTC by williamschen23

### What is the current behavior?

Currently if a numeric gradeable has 0 items, it throws a lot of json_decode() errors.

### What is the new behavior?
We can use js to restrict the rubric to not have 0 items

### Other information?

2024-09-24 16:07 UTC, ziesski requested changes
We should avoid using `.html()` which can introduce XSS attack, and it is in general good practice. Also, the error text should be consistent with rest of the error message.

2024-09-24 16:07 UTC, ziesski commented on site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
> +                $('#save_status').html('<span style="color: red">Some Changes Failed!</span>');
```suggestion
                $('#save_status').text('Error Saving Changes').css('color', 'red');
```

2024-09-24 16:07 UTC, ziesski commented on site/app/templates/admin/admin_gradeable/rubric/NumericRubric.twig
> +                $('#save_status').html('<span style="color: red">Some Changes Failed!</span>');
```suggestion
                $('#save_status').text('Error Saving Changes').css('color', 'red');
```

2024-10-30 16:53 UTC, williamschen23 commented
This is done it just needs a review

2024-11-12 21:11 UTC, ziesski approved these changes
I haven't tested the functionality, but the code looks good.

2024-11-20 04:13 UTC, merged