[Refactor:TAGrading] Start switching to async/await
Submitty/Submitty pull request #10996
Opened 2024-10-01 20:02 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

This should work identically to the old behavior, but now will be far easier to read.

2024-10-02 16:38 UTC, williamschen23 requested changes

2024-10-02 16:38 UTC, williamschen23 commented on site/public/js/ta-grading-rubric.js
>   * @return {Promise}
change returns and update the comments as necessary

2024-10-22 20:36 UTC, williamschen23 approved these changes

2024-10-22 20:50 UTC, williamjallen approved these changes

2024-11-01 13:24 UTC, merged