[Refactor:InstructorUI] refactor pronouns cypress test using testid
Submitty/Submitty pull request #11003
Opened 2024-10-04 20:00 UTC by yanliw123

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2024-10-05 14:49 UTC, IDzyre requested changes
A few nitpicky comments about hyphens instead of underscores, but a good start overall. I will do a testing sometime later today or tomorrow.

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/EditPronounsForm.twig
> +                   data-testid="pronounsInput"
```suggestion
                   data-testid="pronouns-input"
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/EditPronounsForm.twig
> +            <button aria-label="Clear pronoun input" data-testid="Clear-pronoun-input" type="button" style="background: none;border:none;" onclick="clearPronounsBox();"><i class="fas fa-trash" style=
```suggestion
            <button aria-label="Clear pronoun input" data-testid="clear-pronoun-input" type="button" style="background: none;border:none;" onclick="clearPronounsBox();"><i class="fas fa-trash" style="padding:0.5rem;" title="Clear pronouns field"></i></button>
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/UserProfile.twig
> +                        <button id='pronouns_val' data-testid="pronouns_val" class="icon" tabindex="0" onclick="showUpdatePronounsForm()" aria-label="Edit user pronouns" title="Edit user pronouns">
```suggestion
                        <button id='pronouns_val' data-testid="pronouns-val" class="icon" tabindex="0" onclick="showUpdatePronounsForm()" aria-label="Edit user pronouns" title="Edit user pronouns">
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/UserProfile.twig
> +                        <button id='display_pronouns_val' data-testid="display_pronouns_val" class="icon" tabindex="0" onclick="showUpdatePronounsForm()" aria-label="Edit user pronouns" title="Edit u
```suggestion
                        <button id='display_pronouns_val' data-testid="display-pronouns-val" class="icon" tabindex="0" onclick="showUpdatePronounsForm()" aria-label="Edit user pronouns" title="Edit user pronouns">
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/forum/CreatePost.twig
> +			    <strong class="post_user_id" data-testid="post_user_id" title="Original Poster">{{ visible_username }} <span style="color: var(--standard-medium-vibrant-blue);"><strong>OP</strong></span></str
```suggestion
			    <strong class="post_user_id" data-testid="post-user-id" title="Original Poster">{{ visible_username }} <span style="color: var(--standard-medium-vibrant-blue);"><strong>OP</strong></span></strong>
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/forum/CreatePost.twig
> +                <strong class="post_user_id" data-testid="post_user_id">{{ visible_username }}</strong>
```suggestion
                <strong class="post_user_id" data-testid="post-user-id">{{ visible_username }}</strong>
```

2024-10-05 14:49 UTC, IDzyre commented on site/app/templates/forum/CreatePost.twig
> +                <strong class="post_user_pronouns" data-testid="post_user_pronouns">({{post_user_info.pronouns}})</strong>
```suggestion
                <strong class="post_user_pronouns" data-testid="post-user-pronouns">({{post_user_info.pronouns}})</strong>
```

2024-10-05 14:49 UTC, IDzyre commented on site/cypress/e2e/Cypress-UI/pronouns_change.spec.js
> +        cy.get('[data-testid="post-action-container"]').eq(0).find('[data-testid="post_user_pornouns"]').should('not.exist');
```suggestion
        cy.get('[data-testid="post-action-container"]').eq(0).find('[data-testid="post-user-pronouns"]').should('not.exist');
```

2024-10-08 18:01 UTC, yanliw123 commented
> A few nitpicky comments about hyphens instead of underscores, but a good start overall. I will do a testing sometime later today or tomorrow.

code style fixed,need a re-review

2024-10-08 20:37 UTC, IDzyre requested changes

2024-10-08 20:37 UTC, IDzyre commented on site/app/templates/GlobalHeader.twig
> +                        <span class="icon-title" data-testid="icon_{{button.getTitle()}}"> {{ button.getTitle() }} </span>
Is this being used anywhere?

2024-10-08 20:38 UTC, IDzyre commented
If you could also add a description.

2024-10-14 03:18 UTC, IDzyre approved these changes

2024-10-15 01:49 UTC, merged