ta-grading-histograms-missing-in-some-cases
Submitty/Submitty pull request #11011
Opened 2024-10-11 05:52 UTC by KUNDAN1334

#10944 

### What is the new behavior?
The functionality to display all relevant tabs and show appropriate messages based on the grading status has been implemented correctly across the mentioned files.

2024-10-15 04:00 UTC, DarthNyan requested changes
See documentation on [PR Titles](https://submitty.org/developer/getting_started/make_a_pull_request) and [Linting](https://submitty.org/developer/testing/linting_static_analysis). All CI checks need to pass.

2024-10-15 04:00 UTC, DarthNyan commented on site/public/js/ta-grading.js
> +    const autogradingPanel = document.getElementById('autograding_results');
Use jQuery if possible

2024-10-30 02:50 UTC, IDzyre requested changes

2024-10-30 02:50 UTC, IDzyre commented on site/app/controllers/grading/ElectronicGraderController.php
> +
Whitespace additions should be reverted, as they are outside the scope of this PR, and some of them will cause phplint failures.

2025-04-26 02:08 UTC, bmcutler commented
closing due to inactivity

2025-04-26 02:08 UTC, closed without merging