[Feature:Autograding] Haskell Sample Config
Submitty/Submitty pull request #11017
Opened 2024-10-12 00:32 UTC by Adsalor

haskell sample config.json + correct and incorrect submissions

### Please check if the PR fulfills these requirements:

* N/A Tests for the changes have been added/updated (if possible)
* [X] Documentation has been updated/added if relevant
* N/A Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
There is no haskell sample gradeable currently.

### What is the new behavior?
There is now a haskell sample gradeable.

### Other information?
This is not a breaking change, I tested using the `main.hs` and `incorrect.hs` files in submissions/

2024-10-15 03:20 UTC, DarthNyan requested changes
This is a good start.

Aside from the code comments, we'll also want to add a gradable using this to the Development sample course. See `.setup/data/courses/development.yml`

Lastly, and this is a nitpick, as this is not a feature but a usage example it would be better under [Documentation:Autograding] than [Feature:Autograding]

2024-10-15 03:20 UTC, DarthNyan commented on more_autograding_examples/haskell_hello_world/config/config.json
> +            "command" : "ghc --make -v0 main.hs -o main",
Compiling `*.hs` instead of `main.hs` should allow us to avoid renaming files for testing submission

2024-10-15 03:20 UTC, DarthNyan commented on more_autograding_examples/haskell_hello_world/config/config.json
> +            "executable_name" : "main",
Other sample configs produce `a.out` as their compile-testcase executable. Can we do the same here?

2024-10-21 20:28 UTC, DarthNyan approved these changes
Rebuilt sample courses and tested, it worked.

Code looks good as well. Should be good to merge as soon as YAML lint is fixed.

2024-10-22 20:11 UTC, williamjallen commented
Moving this back to "Work in Progress" until the failing test.  Please move this back to "Awaiting Maintainer Review" directly once the tests are passing.

2024-10-31 19:04 UTC, Adsalor commented
Sorry if I've missed something, I haven't had much free time to focus on this recently--I remember YAMLLint was failing, it's passing now--is there anything else I should change for this?

2024-11-01 13:27 UTC, merged