[Feature:TAGrading] Add text option for checkpoint lab
Submitty/Submitty pull request #11023
Opened 2024-10-18 19:49 UTC by ZheyuDeng

Fixes issue #10893 

### What is the current behavior?
Currently, only numerical lab is able to have extra text column for note.

### What is the new behavior?
Now you can also add text items into checkpoint lab.
![image](https://github.com/user-attachments/assets/81327ba6-6bd7-4325-b54b-7d1647bb15bc)

2024-11-08 15:02 UTC, fausta4303 requested changes
-UI looks good after resizing the window to various dimensions
-Functionality for a single text/note checkpoints works
-Having multiple text/note checkpoints works (Tested having 2 and 10.)

Bugs/Suggestions:
1. Adding a new graded checkpoint after creating text/note checkpoints converts all the text/note ones into graded ones. Here's before and after pictures:
Before:
![image](https://github.com/user-attachments/assets/06afcd6f-173d-4db6-b279-3274ad9a0599)

After adding checkpoint 2:
![image](https://github.com/user-attachments/assets/a8a7367b-eec5-49ca-905d-6e917f5bfcca)

2. The edit gradeable page allowed me to make 500 and 1000 text/note checkpoints. Maybe add a limit to how many can be made?

3. Small nitpick, but once text/note checkpoints are made they're lasted as "Extra Credit" checkpoints and have no clear distinction that they're text/note checkpoints within the edit gradeable page. Maybe give them their own label so as to avoid potential confusion?

2024-12-12 20:07 UTC, zacharymnp approved these changes
Feature works as expected. 
![image](https://github.com/user-attachments/assets/e90b0501-3ac5-4287-a136-38b9e4da732d)
The textboxes shrink when not in focus, but this matches the behavior of the textboxes in numeric labs, so the issue is not relevant to this PR.

 Adding a note count as an edit by a grader.
![image](https://github.com/user-attachments/assets/d557a5f9-4a7f-4705-890e-7075374d133d)

2024-12-12 20:07 UTC, zacharymnp commented on site/app/templates/grading/simple/Display.twig
>          {% if component.isText() %}
If you delete the body of this if-statement, it would be cleaner to get rid of it entirely and replace the else-statement with its negation.

2025-01-18 03:02 UTC, williamjallen requested changes
While the feature seems to work as expected according the functionality review, this PR still needs substantial work to meet our code style guidelines.  If you need help with any of this or have thoughts about any of these comments, feel free to ping me on this PR or on Zulip.

2025-01-18 03:02 UTC, williamjallen commented on site/public/js/simple-grading.js
> +                console.log('Failed to save data');
Is there any additional information you can add to this message to make it easier to determine what went wrong if someone sends the contents of their browser console to a developer when something goes wrong?

2025-01-18 03:02 UTC, williamjallen commented on site/public/js/simple-grading.js
> -
This whitespace change is not necessary and should be reverted.

2025-01-21 17:48 UTC, ZheyuDeng commented on site/app/templates/admin/admin_gradeable/rubric/CheckpointsRubric.twig
> +    <label for="numeric_num-items">How many checkpoint items?</label>
I can do that but the numerical lab has the same phrase. Should I modify them as well?

2025-01-21 22:43 UTC, ZheyuDeng commented
As discussed with William I will make a separate PR working on the codestyle changes requested on checkpoint rubric twig file since I basically coppied them from numerical rubric to keep the same format.

2025-03-17 19:25 UTC, bmcutler requested changes
I'm trying to test this PR...

I edited an existing gradeable with grades (the "grading lab" gradeable in the sample course) to add a text column.  Every time I add or edit a text entry I get this pop up error:
<img width="450" alt="Screenshot 2025-03-17 at 3 22 15 PM" src="https://github.com/user-attachments/assets/104f402f-3479-4d20-b1c8-fe7f58511885" />

There are many errors in the javascript console -- not sure if they are related.
<img width="502" alt="Screenshot 2025-03-17 at 3 24 48 PM" src="https://github.com/user-attachments/assets/f4f29a6e-14ef-4e34-83d9-50919b3618c1" />

Edit to add:

The instructor UI for specifying the number and labels on the text column look ok.
And the data for the text boxes seems to save ok.  But the popup happens on every edit making the feature use annoying.

I was testing on Mac Chrome.

2025-03-18 16:50 UTC, Troy-bailan-King approved these changes
Test good in local

2025-04-11 00:27 UTC, zacharymnp commented
On the error I screenshotted, it does appear to be a fairly critical error. I am not getting this when I try to load sample:

![image](https://github.com/user-attachments/assets/83e611bf-9b03-4416-b620-25d662cb0ca0)

2025-04-25 20:12 UTC, ZheyuDeng commented
I have added a clamp to prevent checkpoint rubrics to reach 0. But numerical lab might also has this issue since it is in similar structure.

2025-04-25 20:15 UTC, ZheyuDeng commented
https://github.com/Submitty/Submitty/issues/10503

2025-04-25 20:16 UTC, ZheyuDeng commented
issue #10503 (delete last rubric breaks site) is a similar issue to this but in a different place.

2025-04-26 00:34 UTC, sbelsk requested changes
Testing this, it seems that the web socket logic to automatically update the checkpoint values as other graders are grading, no longer works.

Also nothing that after testing this and switching back to main, this is what the grading page looks like: 
![image](https://github.com/user-attachments/assets/155a7f64-036d-4456-9f63-cb0d1f93093b)
```
Warning: Undefined property: app\models\gradeable\Component::$comment in /usr/local/submitty/site/app/models/AbstractModel.php on line 193
```

2025-05-23 21:15 UTC, williamschen23 approved these changes
Did the best I can, testing could not beak the code.

2025-05-23 21:22 UTC, merged