Add Cypress tests for bulk upload
Submitty/Submitty pull request #11021
Opened 2024-10-17 15:25 UTC by jaseemuddinn

Related to #11002

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Submitty/Submitty/issues/11002?shareId=da15eb17-e3f3-414b-8636-e728b15c8ae2).

2024-10-21 19:57 UTC, DarthNyan requested changes
This is a really good start. See the documentation on [PR titles](https://submitty.org/developer/getting_started/make_a_pull_request). Other than that, there are just a few additional checks I think should be added.

2024-10-21 19:57 UTC, DarthNyan commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +        });
Bulk uploading should trigger a daemon job and inform the user of the job's status. Can you add a check to verify this (for QR and page count)

2024-10-21 19:57 UTC, DarthNyan commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('.alert-success').should('contain', 'Bulk upload deleted');
Similarly here, we should verify not only that the 'Bulk upload deleted' banner appears, but that which we deleted has actually been deleted.

2024-10-22 00:29 UTC, IDzyre requested changes

2024-10-22 00:29 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('[data-testid="grade-button"]').first().click();
This is an example of a good selector. If you can add (if they aren't already there)  data-testids, and use them for the elements being selected in this test? You can edit the relevant twig files to add them. 

Good start!

2024-10-22 06:20 UTC, jaseemuddinn commented
I have made a new pull request with updated PR title, Do Check!
https://github.com/Submitty/Submitty/pull/11030

2024-10-22 06:20 UTC, closed without merging

2024-10-22 12:20 UTC, IDzyre commented
You can edit the title of a PR, so in the future, it would be better to do so to not lose prior reviews.