Live ta grading indicators
Submitty/Submitty pull request #11038
Opened 2024-10-25 20:43 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

TAs could be grading the same problem without their knowledge

### What is the new behavior?
TAs will be able to see who is currently grading each component and when they started grading it

### Other information?

2024-10-26 17:16 UTC, williamschen23 commented on migration/migrator/migrations/course/20240816095713_late_days_constraint.py
why?

2024-10-26 17:30 UTC, lavalleeale commented on migration/migrator/migrations/course/20240816095713_late_days_constraint.py
The migration was not repeatable so I had to edit it for development, this PR definitely needs more work in many other places as well

2024-12-12 18:38 UTC, DarthNyan requested changes
A few nitpicks, but code looks mostly good. I haven't tested yet.

2024-12-12 18:38 UTC, DarthNyan commented on site/app/models/gradeable/GradedGradeable.php
> +    protected $active_graders_names = [];
Are default values here necessary with the constructor parameters being required?

2024-12-12 18:38 UTC, DarthNyan commented on site/public/js/ta-grading-rubric.js
> +const units = [
Can units be non-global?

2024-12-12 18:38 UTC, DarthNyan commented on site/public/js/ta-grading-rubric.js
> +            ACTIVE_GRADERS_LIST[component.id] = graded_gradeable.active_graders[component.id]?.map((_, index) => `${graded_gradeable.active_graders[component.id][index]} (${timeAgo(luxon.DateTime.fro
Can you split this into multiple lines for readability?

2024-12-12 18:38 UTC, DarthNyan commented on site/public/js/ta-grading-rubric.js
> +            ACTIVE_GRADERS_LIST[component] = response.data.active_graders[component]?.map((_, index) => `${response.data.active_graders[component][index]} (${timeAgo(luxon.DateTime.fromISO(response.d
Same comment here about line length

2024-12-12 18:38 UTC, DarthNyan commented on site/public/js/ta-grading-rubric.js
> +            ACTIVE_GRADERS_LIST[component] = response.data.active_graders[component]?.map((_, index) => `${response.data.active_graders[component][index]} (${timeAgo(luxon.DateTime.fromISO(response.d
Same comment here about line length

2024-12-13 02:14 UTC, williamjallen requested changes
Here's an initial round of comments.  I'll do a more thorough review sometime when I'm less tired.

2025-01-13 16:12 UTC, lavalleeale commented on migration/migrator/migrations/course/20241011142039_add_current_graders.py
> +            ag_team_id character varying(255),
I am unsure how that can work while they are nullable, I think ensuring one of them is not null is the best we can do (seen for other tables in the codebase).

2025-01-17 23:03 UTC, zacharymnp requested changes
![image](https://github.com/user-attachments/assets/54d01ac7-41cd-4c9c-ad56-0a2623bbdb98)
![image](https://github.com/user-attachments/assets/7df9fadc-0ba5-4b0f-9977-7b994b837989)

I recommend a larger font so that the message is more visible. The message does show up reliably on page load.

2025-01-21 20:01 UTC, zacharymnp requested changes
The item being graded by a TA does not seem to update.

https://github.com/user-attachments/assets/73008fdd-c74e-4241-8ed0-0cd7777d4e20

2025-01-22 01:34 UTC, lavalleeale commented
@williamjallen I would love your review on this now

2025-01-23 04:23 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +    public function addComponentGrader($component, $isTeam, $grader_id, $graded_id) {
It would be better to use native PHP type annotations for these arguments as follows.  PHPdoc annotations are only necessary if you're providing extra information, such as a template type.  Apply throughout.
```suggestion
    public function addComponentGrader(Component $component, bool $isTeam, string $grader_id, string $graded_id): void {
```

2025-01-23 04:26 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +            WHERE gc_id = ? AND grader_id = ? AND ag_user_id = ? AND ag_team_id IS NULL
I'm not sure if it would be cleaner or not, but you could combine these into something along the lines of this since the database constraints guarantee that only one of the columns may have a value:
```
WHERE gc_id = ? AND grader_id = ? AND (ag_user_id = ? OR ag_team_id = ?)
```

2025-01-23 04:27 UTC, williamjallen commented on site/app/models/gradeable/GradedGradeable.php
> +    public function __construct(Core $core, Gradeable $gradeable, Submitter $submitter, array $details, array $active_graders, array $active_graders_timestamps, array $active_graders_names) {
What do you think about adding default values for the new parameters?  That way, you won't have to edit any existing code which doesn't use the new parameters.

2025-01-23 04:32 UTC, williamjallen commented on site/public/templates/grading/Component.twig
> +        &nbsp;Currently being graded by: {{ graders|join(", ")}}
What's the purpose of the non-breaking space here?

2025-01-23 04:33 UTC, williamjallen commented on migration/migrator/migrations/course/20241011142039_add_active_graders.py
> +            FOREIGN KEY (ag_team_id) REFERENCES gradeable_teams(team_id),
Should all of these have `ON DELETE CASCADE`?

2025-01-23 04:35 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +        // Ensure the current grader is not in the list of active graders:w
Vim user? ;)

```suggestion
        // Ensure the current grader is not in the list of active graders
```

2025-01-23 04:38 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +                        array_splice($timestamps[$component_id], $i, 1);
Is `array_splice()` needed here?

2025-01-23 04:40 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +            return;
It would be better to return a `JsonResponse::getErrorResponse()` or similar instead of exiting with no explanation.  Apply throughout.

2025-01-23 04:40 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +            $this->core->getOutput()->renderJsonFail('Insufficient permissions to save component/marks');
It would be better to return a `JsonResponse::getErrorResponse()` instead.

2025-01-23 04:42 UTC, williamjallen commented on site/app/controllers/grading/ElectronicGraderController.php
> +    public function ajaxCloseGradedComponent($gradeable_id) {
There's a lot of duplicated code between this method and `ajaxOpenGradedComponent()`.  Any way you could share some code here?

2025-01-24 21:40 UTC, zacharymnp approved these changes
Status indicators have been fixed and update properly, they look good.
![image](https://github.com/user-attachments/assets/8c2001bd-c7d5-4f8b-8a9f-122149c11b09)

2025-01-31 02:03 UTC, williamjallen requested changes
A few overall thoughts and comments:
1. Is this really the best user experience we can provide?  It feels clunky to me.  Perhaps a google docs-style indicator circle would be a better option.
2. What happens if someone opens a component and then closes the window?
3. What happens if someone opens a component and then leaves their computer for a long period of time?
4. Knowing whether someone is actually grading an open component at the moment is hard.  Perhaps we should phrase it as "last opened by Bitdiddle at 12:04 PM" instead of the current language which implies that we have the ability to tell whether someone actually has the component open.

Please also add screenshots to the PR description for documentation purposes.

2025-03-15 02:22 UTC, williamjallen requested changes
Things look pretty good here; I expect to approve once the requested changes are made.  It also looks like you need to resolve some conflicts.

I am concerned about the testing of this feature.  Is there anything you can do to test this feature more thoroughly?  As it is now, this PR adds only a handful of assertions to an existing test.  Features like this which aren't critical are easily broken, and breakages often go unnoticed for long periods of time.  I would feel much more confident if you added more rigorous testing.

2025-03-15 02:22 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +    }
The formatting is a bit odd here.  What about this instead?

```suggestion
    public function addComponentGrader(Component $component, bool $isTeam, string $grader_id, string $graded_id): void {
        $this->course_db->query("
            INSERT INTO active_graders (gc_id, grader_id, ag_user_id, ag_team_id, timestamp)
            VALUES (?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
        ", [
            $component->getId(),
            $grader_id,
            $isTeam ? null : $graded_id,
            $isTeam ? $graded_id : null,
            $this->core->getDateTimeNow(),
        ]);
    }
```

2025-03-15 02:22 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +     * @return void
There's no need to add PHPDoc annotations if they don't provide additional information beyond that provided by the native PHP annotations.
```suggestion
```

2025-03-15 02:22 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +    }
Same here.

2025-03-19 00:29 UTC, williamjallen approved these changes

2025-03-19 00:32 UTC, williamjallen commented
@lavalleeale I reviewed the code, but it's not clear to me how much testing has occurred recently.  I'll leave the decision of whether or not additional functionality reviews are needed.  If you think this is good to go, feel free to move this directly to "ready to merge".

2025-03-21 21:23 UTC, merged