[Feature:InstructorUI] filter withdrawn student function
Submitty/Submitty pull request #11036
Opened 2024-10-25 07:35 UTC by yanliw123

fiter withdrawn student in checkpoint/numeric lab and detail grading page

Step to test:
1. login as instructor
2. go to manage students page
3. edit student -> change some students' registration type to withdrawn
4. go to checkpoint/numeric lab see checkbox
5. go to details grading page see filter withdrawn student button
6. test if withdrawned student is filtered
![image](https://github.com/user-attachments/assets/0ffb6246-62ff-4505-9e70-2e663fdf2937)
![image](https://github.com/user-attachments/assets/752820f3-6b40-41d9-98f5-ab97d006908d)

2024-10-30 02:35 UTC, IDzyre commented on site/public/js/simple-grading.js
> +    // filter student who withdrawned from this course
```suggestion
    // filter student who have withdrawn from this course
```

2024-10-30 02:36 UTC, IDzyre commented on site/app/views/grading/ElectronicGraderView.php
> +    public function detailsPage(Gradeable $gradeable, $graded_gradeables, $teamless_users, $graders, $empty_teams, $show_all_sections_button, $show_import_teams_button, $show_export_teams_button, $sh
Is this being used anywhere?

2024-11-16 13:59 UTC, IDzyre commented on site/cypress/e2e/Cypress-TAGrading/ta_grading_details.spec.js
> +        cy.get('[id="view-your-sections"]').should('contain', 'Only Assigned Sections');
These should be `data-testid` not `id`

2025-01-14 01:59 UTC, williamjallen commented
This still needs a functionality review and initial approval before maintainer review.  Moving back to "Seeking Reviewer".

2025-01-17 22:46 UTC, ajiang024 approved these changes
This works as specified in the testing instructions. I tested the functions for both TAs and instructors, and for both of them, the withdrawn students are correctly filtered when the box is checked off.
I would recommend someone with more PHP experience to review the code. Testing-wise, it looks good to me.

2025-01-21 21:23 UTC, polibear21 approved these changes
I followed the testing instructions and the website functions exactly as described in the pull request. When I check the box of "Hide withdrawn students", students withdrawn from the course do not show up in the list. Someone with more PHP experience should review the exact PHP code. The UI and functionality of the PR looks good.

2025-01-22 00:09 UTC, williamjallen requested changes
This work looks pretty good overall and should be good to merge once these minor nitpick comments are resolved.  Please also improve the PR description.  The PR should clearly list before and after screenshots, along with a clear description of the work completed.  Please also use a GitHub keyword like "closes #xyx" to automatically close the issue linked in the PR description when this gets merged.

2025-01-22 00:09 UTC, williamjallen commented on site/public/js/details.js
> +        Cookies.set(`anon_mode_${gradeable_id}`, 'off');
Do you need to set the status of `anon_status` here?  I guess if it defaults to unchecked that's good enough?

2025-01-22 00:09 UTC, williamjallen commented on site/public/js/simple-grading.js
> +            console.log(this.checked);
This log should be removed.

2025-01-22 00:09 UTC, williamjallen commented on site/app/templates/grading/electronic/Details.twig
> +        {% if not graded_gradeable.getSubmitter().isTeam() and graded_gradeable.getSubmitter().getUser().getRegistration_type() == "withdrawn"%}
```suggestion
        {% if not graded_gradeable.getSubmitter().isTeam() and graded_gradeable.getSubmitter().getUser().getRegistration_type() == "withdrawn" %}
```

2025-01-22 00:09 UTC, williamjallen commented on site/app/templates/grading/simple/Display.twig
> +
```suggestion
```

2025-01-22 00:09 UTC, williamjallen commented on site/app/templates/grading/simple/Display.twig
> +        {% if grade.getSubmitter().getUser().getRegistration_type() == "withdrawn"%}
```suggestion
        {% if grade.getSubmitter().getUser().getRegistration_type() == "withdrawn" %}
```

2025-01-22 00:09 UTC, williamjallen commented on site/cypress/e2e/Cypress-TAGrading/ta_grading_details.spec.js
> +
Let's match the formatting of the surrounding code:

```suggestion
        cy.get('[data-testid="random-default-order"]').should('contain', 'Randomize Order');
        cy.get('[data-testid="toggle-anon-button"]').should('contain', 'Anonymize Student Name');
        cy.get('[data-testid="toggle-grade-inquiry"]').should('contain', 'Only Grade Inquiry');
```

2025-06-20 23:41 UTC, JManion32 commented
@yanliw123 @Troy-bailan-King To complete this PR, I found it easiest to create a new branch in order to better integrate changes from both this branch and main. #11792 supersedes this one and includes all of your commits. Thank you both for your contributions!

2025-06-20 23:41 UTC, closed without merging