[Testing:Submission] Add Cypress tests for bulk upload
Submitty/Submitty pull request #11030
Opened 2024-10-22 06:18 UTC by jaseemuddinn

Fixes #11002

Add Cypress tests for bulk upload functionality.

* Add tests for upload and split by QR code.
* Add tests for upload and split by page count.
* Add tests for delete uploads functionality.
* Add tests for submit uploads linking to student in grading interface.
* Verify daemon job status for QR and page count uploads.
* Verify that deleted uploads are actually deleted.

2024-10-25 20:01 UTC, DarthNyan requested changes

2024-10-25 20:01 UTC, DarthNyan commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('#bulk-upload-file').selectFile('cypress/fixtures/bulk_upload_qr.pdf', { force: true });
I ran the tests in CI and its failing here. These tests should pass before being merged. Check out [the docs](https://submitty.org/developer/testing/cypress) on how to run & debug locally.

2024-10-29 15:53 UTC, IDzyre requested changes
I think that all these added tests could be combined into one, as a lot of each `it` section is the same code.

2024-10-29 15:53 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('[data-testid="view-sections"]').click();
Copying this here, as this review is in the old PR (also advised to not close, just to edit the PR title)

This is an example of a good selector. If you can add (if they aren't already there) data-testids, and use them for the elements being selected in this test? You can edit the relevant twig files to add them. You can find examples of this in the relevant twig files, and other Cypress files.

2024-10-29 15:53 UTC, IDzyre commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('#bulk-upload-file').selectFile('cypress/fixtures/bulk_upload_qr.pdf', { force: true });
Can you use selectFile without `force: true` ?

2025-03-11 19:59 UTC, grt812 requested changes

2025-03-11 19:59 UTC, grt812 commented on site/cypress/e2e/Cypress-Gradeable/bulkupload.spec.js
> +            cy.get('#bulk-upload-file').selectFile('cypress/fixtures/bulk_upload_qr.pdf', { force: true });
The appropriate id for the selectFile function seems to be input-file1 to upload the files, but it would be good to double check and test this.

2025-04-26 02:12 UTC, williamjallen commented
Superseded by https://github.com/Submitty/Submitty/pull/11603.

2025-04-26 02:12 UTC, closed without merging