[Bugfix:Autograding] Add alert if config unuploaded
Submitty/Submitty pull request #11139
Opened 2024-11-15 19:44 UTC by fausta4303

### Please check if the PR fulfills these requirements:

* [X] Tests for the changes have been added/updated (if possible)
* [N/A] Documentation has been updated/added if relevant
* [N/A] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
When choosing an autograder config file to upload for a gradeable, the user is not alerted if they have not actually uploaded the file. This can cause confusion for users who go to other pages and thinking they uploaded their config, when they didn't.

### What is the new behavior?
Submitty should now properly alert the user if they have an un-uploaded file, and give them the chance to either upload it or cancel the upload.

### Other information?
How to test:
1. Go to any gradeable and go into it's "Edit Gradeable Configuration" via the pencil icon
2. Go to the Submissions/Autograding tab
3. Click "Upload a custom autograding configuration"
4. Upload a config file, and try to leave/refresh/close the page without uploading or cancelling the upload.

2024-11-15 22:05 UTC, DarthNyan requested changes

2024-11-15 22:05 UTC, DarthNyan commented on site/app/templates/admin/UploadConfigForm.twig
> +    document.getElementById("configUpload").addEventListener("change", function(event) {
You can use jQuery to eliminate a lot of boilerplate syntax. `$('#config-upload').on(...` or similar syntax is much nicer to read.

2025-06-11 17:35 UTC, williamschen23 requested changes
Functionality looks good

2025-06-11 17:35 UTC, williamschen23 commented on site/app/templates/admin/UploadConfigForm.twig
> +    <br>
Remove inline CSS

2025-06-11 17:54 UTC, williamschen23 requested changes
Fix css lint

2025-06-11 18:03 UTC, williamschen23 approved these changes

2025-06-12 02:46 UTC, merged