[Bugfix:InstructorUI] Prevent gradeable deleting from throwing frog robot
Submitty/Submitty pull request #11133
Opened 2024-11-08 21:32 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Deleting a gradeable can possibly throw a frog robot due to peer grading not being deleted.

### What is the new behavior?
Deleting a gradeable will work successfully.

### Other information?

Testing requires editing the [canDelete](https://github.com/Submitty/Submitty/blob/3b9c945261a67cbc1a2b864a1404d0f56d48b2fa/site/app/models/gradeable/Gradeable.php#L1804) function to allow the deletion button to be shown in the UI.

2024-11-08 22:42 UTC, williamschen23 approved these changes
I tested the change, so I deleted a gradeable and looking at the sql, it deleted the gradeable_id from the gradeable table, the gradeable in the electronic_gradeable table, and the anon_id in the gradeable_anon table

2024-11-08 23:15 UTC, ziesski requested changes

2024-11-08 23:15 UTC, ziesski commented on migration/migrator/migrations/course/20241108162239_cascade_on_delete_gradeable.py
> +    pass
```suggestion
        database.execute("""
            ALTER TABLE gradeable_anon DROP CONSTRAINT gradeable_anon_g_id_fkey;
            ALTER TABLE gradeable_anon ADD CONSTRAINT gradeable_anon_g_id_fkey
                FOREIGN KEY (g_id) REFERENCES gradeable(g_id)
                ON UPDATE CASCADE ON DELETE CASCADE;

            ALTER TABLE peer_grading_panel DROP CONSTRAINT peer_grading_panel_g_id_fkey;
            ALTER TABLE peer_grading_panel ADD CONSTRAINT peer_grading_panel_g_id_fkey
                FOREIGN KEY (g_id) REFERENCES public.electronic_gradeable(g_id)
                ON UPDATE CASCADE ON DELETE CASCADE;
        """)
```

2024-11-08 23:15 UTC, ziesski commented on migration/migrator/migrations/course/20241108162239_cascade_on_delete_gradeable.py
> +    pass
We should wrap migration sql commands in one transaction.

2024-11-10 03:33 UTC, ziesski approved these changes
ON DELETE CASCADE is reasonable approach. Code looks good.

2024-11-12 00:44 UTC, merged