[Feature:InstructorUI] Add Rubric to Upload/Download Gradeable
Submitty/Submitty pull request #11138
Opened 2024-11-15 14:39 UTC by IDzyre

### Please check if the PR fulfills these requirements:

* [x] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
The gradeable upload and download was added without the rubric settings being saved or uploaded.

Closes #10937 

### What is the new behavior?
The rubric section has been added to the upload and download portions of this, reusing the add rubric code, so there is not much duplication between the download/upload just rubrics, and download the whole gradeable.

2025-01-19 17:45 UTC, williamjallen requested changes

2025-01-19 17:45 UTC, williamjallen commented on site/app/controllers/admin/AdminGradeableController.php
> +        }
A few comments about this block of code:
- Should you also check to make sure this field is iterable?
- What verifies that `$component` satisfies the contract expected by `importComponent()`?  It looks like adding additional error checking to `importComponent()` and catching the resulting exceptions would be useful here.
- What happens if there are no components?  Don't you still need to create a blank component?

2025-01-19 17:45 UTC, williamjallen commented on site/app/controllers/admin/AdminGradeableController.php
> +            $values['rubric'] = $_POST['rubric'];
Is there an object you can create instead of processing an arbitrary array here?  Lots of magic values to deal with here...

2025-01-19 17:45 UTC, williamjallen commented on site/app/controllers/admin/AdminGradeableController.php
> +                $values['grade_inquiry_allowed'] = 'true';
What was the motivation for this change?

2025-01-19 17:45 UTC, williamjallen commented on site/app/controllers/admin/AdminGradeableController.php
> +                    'team_size_max' => $gradeable->getTeamSizeMax(),
Does this break backwards compatibility with existing JSONs instructors may have?

2025-01-19 21:18 UTC, IDzyre commented on site/app/controllers/admin/AdminGradeableController.php
> +                    'team_size_max' => $gradeable->getTeamSizeMax(),
The UploadJSON function expects the variable to be `team_size_max`, so yes it is not 'backwards compatible', but the old JSON's wouldn't have the valid variable either.

2025-01-25 00:44 UTC, IDzyre commented on site/app/controllers/admin/AdminGradeableController.php
> +        }
A gradeable can set it's components to a list of already created components, should I use that function instead of import components as an array? That way it wouldn't be working with "magic values" also.

2025-01-27 02:14 UTC, williamjallen commented on site/app/controllers/admin/AdminGradeableController.php
> +        }
Which function are you referring to?  The idea sounds like it's on a better path at least.

2025-01-28 01:02 UTC, IDzyre commented on site/app/controllers/admin/AdminGradeableController.php
> +        }
Gradeable's setComponents() function

2025-03-13 01:47 UTC, williamjallen approved these changes
The code looks much better to me now.  I still have a funny feeling about the boolean strings being used in various places, but that isn't necessarily related to the PR itself.  Note that I didn't test this manually but I did review the tests you wrote.

2025-03-13 01:48 UTC, williamjallen commented
@IDzyre Feel free to move directly to "ready to merge" once you get the tests passing unless you want me to take another look.  For now, moving back to "in progress"...

2025-03-24 23:27 UTC, IDzyre commented
> The code looks much better to me now. I still have a funny feeling about the boolean strings being used in various places, but that isn't necessarily related to the PR itself. Note that I didn't test this manually but I did review the tests you wrote.

I do agree that the boolean strings are annoying and weird to use, but it's the way that the javascript variables get passed through the request, and it is what the `createGradeable` function is looking for. I don't know a way around it without refactoring the function to expect booleans, and/or have a wrapper function to take the boolean strings and convert them to actual booleans.

2025-04-04 16:22 UTC, merged