[UI/UX:Forum] Clarify Pin Thread checkbox name
Submitty/Submitty pull request #11180
Opened 2024-11-26 18:25 UTC by xixvtt

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

fix #11169 

### What is the new behavior?
- forum will have new name regarding to this changes
- no other breaking changes made 

### Other information?

- I was trying to find which page i should look into, but failed, appreciated if someone could point it out which page is this forum at so I could provide the latest screenshot
-

2024-11-26 21:49 UTC, DarthNyan requested changes
Text has a typo that needs fixing - otherwise it looks good.

Please change the PR title to be more descriptive. PR titles go in the release notes and something along the lines of "Clarify 'Pin Thread' checkboxes" will be more informative.

2024-11-26 21:49 UTC, DarthNyan commented on site/app/templates/forum/ThreadPostForm.twig
> +            {% set announcement_text = email_enabled ? "Notify Students(w/email & notification)" : "Notify Studnets(w/ notification)" %}
'Studnets' is a typo

2024-11-26 21:59 UTC, xixvtt commented on site/app/templates/forum/ThreadPostForm.twig
> +            {% set announcement_text = email_enabled ? "Notify Students(w/email & notification)" : "Notify Studnets(w/ notification)" %}
good catch thx

2024-11-26 22:22 UTC, DarthNyan approved these changes
Looks good.

I wonder if the `(w/email & notification)` and `(w/ notification)` tags can be clarified as well, but I think it's fine as is.

2024-11-26 22:26 UTC, xixvtt commented
> Looks good.
> 
> I wonder if the `(w/email & notification)` and `(w/ notification)` tags can be clarified as well, but I think it's fine as is.

I'm not sure if changing these two names maybe will break the ui cuz looks like we trying to make the checkbox name short? we could do a quick update later on if we needed it

2024-11-26 23:19 UTC, xixvtt commented
been away for a while since July, wonder any new rules updated or added since then?
looks like I'm not authorized to merge this PR even thou every tests passed @DarthNyan

2024-11-27 02:15 UTC, IDzyre commented
There are only a handful of people who can merge PRs, after it goes through the review process, and a maintainer reviews it, then it will get merged if the maintainer approves.

2024-11-28 16:08 UTC, williamjallen requested changes
This unfortunately does not at all resolve https://github.com/Submitty/Submitty/issues/11169.  The behavior and meaning of the two checkboxes needs to be reconsidered, not just a simple text change.

2025-04-04 20:39 UTC, rafizamankhan commented
Fixed by [PR11567](https://github.com/Submitty/Submitty/pull/11567).

2025-04-04 20:39 UTC, closed without merging