[Bugfix:TAGrading] Fix saving mark order
Submitty/Submitty pull request #11189
Opened 2024-12-01 07:22 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

When attempting to update the order of marks in a component in a TAGrading rubric, the mark order will not change.

### What is the new behavior?
When attempting to update the order of marks in a component in a TAGrading rubric, the mark order will successfully change.

### Other information?

This was a regression in #11008 
Tested in the UI by using the sample grading homework

2024-12-12 19:14 UTC, williamschen23 requested changes

2024-12-12 19:14 UTC, williamschen23 commented on site/public/js/ta-grading-rubric.js
>      // No conflicts, so don't open the popup
update comment

2024-12-12 19:52 UTC, williamschen23 approved these changes
tested the feature and it worked, the code also makes a lot of sense

2024-12-12 21:41 UTC, williamjallen approved these changes
Code looks good to me.  @IDzyre it would be great if you could take a look at the new Cypress test here.

2024-12-12 21:51 UTC, IDzyre requested changes
A couple of comments about Cypress test testids and other small changes, but the test overall looks good once these are addressed/explained.

2024-12-12 21:51 UTC, IDzyre commented on site/cypress/e2e/Cypress-TAGrading/rubric_editing.spec.js
> +        cy.get('[data-testid^="component"]').eq(-1).click(20, 25);
Is there a reason for the `^` here?

2024-12-12 21:51 UTC, IDzyre commented on site/cypress/e2e/Cypress-TAGrading/rubric_editing.spec.js
> +        cy.get('[aria-label="mark title"]').eq(-1).type('First New Mark');
Is it possible to add testids for the elements that aren't using them ?

2024-12-12 21:51 UTC, IDzyre commented on site/cypress/e2e/Cypress-TAGrading/rubric_editing.spec.js
> +        });
Is there a way to do this without the waits? (ans without the eslint disable lines?)

2024-12-12 23:17 UTC, IDzyre approved these changes
Changes addressed.

2024-12-13 00:40 UTC, bmcutler approved these changes
thanks for the fix!

2024-12-13 02:54 UTC, IDzyre commented
What is the drag and drop for in this case ?

2025-01-06 04:12 UTC, merged