[Bugfix:Forum] Dark mode working properly for category filters
Submitty/Submitty pull request #11181
Opened 2024-11-26 21:43 UTC by fausta4303

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)

### What is the current behavior?
Currently, category filters for forum posts have white mode backgrounds even if you're using dark mode.
![image](https://github.com/user-attachments/assets/1979c6e8-cd9f-447a-9d27-241dbe34141c)

### What is the new behavior?
They should properly have dark backgrounds now
![image](https://github.com/user-attachments/assets/fa605eab-20f5-496f-9111-e0fbd41e9159)

### Other information?
To test, just check to see if category filter tags have the dark background. Leave a comment if you think another shade/color should be used

2024-12-06 03:50 UTC, williamjallen commented
Can you please add a screenshot of the new UI to the PR description?

2025-01-21 20:25 UTC, williamjallen requested changes
This looks like an appropriate solution for the immediate problem.

@JManion32, please move the screenshots from the comment you posted into the PR description so they go into the commit message when this gets merged.  I'll approve once that is done.

2025-01-21 22:14 UTC, jeffrey-cordero approved these changes
Dark mode UI changes for the thread category buttons look good.

2025-01-21 23:44 UTC, williamjallen approved these changes

2025-01-23 02:40 UTC, merged