[UI/UX:Forum] Improved Colors for Deleted Posts
Submitty/Submitty pull request #11184
Opened 2024-11-28 09:37 UTC by ryvaru

Closes #11165 

### What is the current behavior?
Currently, the deleted forum post background colors are hard to differentiate from the standard posts, and they are not visually appealing in dark mode.

### What is the new behavior?
Made the colors of deleted posts shades of blue. This distinguishes them from active posts while also being a better fit for dark mode. Light mode remains unchanged.

**Light Mode (Unchanged)**
![Screenshot 2025-02-07 215215](https://github.com/user-attachments/assets/a47ffc7b-836b-4f35-9ab3-0f69dc9fa76c)

**Dark Mode (Current Main)**
![Screenshot 2025-02-07 215847](https://github.com/user-attachments/assets/619644ad-e596-46e2-a447-dadad0ad4f8c)

**Dark Mode (Changed)**
![image](https://github.com/user-attachments/assets/467b7a32-960a-4eb9-a0a5-3601ed8a5ade)

**Summary of Changes**
![image](https://github.com/user-attachments/assets/e0197ad3-cd42-4c5a-b75b-9e4c2685c87d)

2025-01-19 17:19 UTC, williamjallen reviewed
@ryvaru Is there a existing color which could be used for this?

2025-01-22 17:15 UTC, Troy-bailan-King submitted a review, later dismissed
The color looks good to me

2025-01-24 18:52 UTC, JManion32 submitted a review, later dismissed
**STALE REVIEW, SEE BELOW**

I agree that the light gray color is not visually appealing in dark mode, however, I believe the issue goes deeper than the colors.

**Here is an example of all possible colors that a discussion forum post can have with your changes:**
![all post colors in dark mode](https://github.com/user-attachments/assets/5594573c-c133-4301-994f-b1b9b7d0f1b4)

It is not immediately clear to the user what each of the colors signify, and this is the case for our current discussion forum without your suggested change as well. I believe the best way to fix this is to either utilize colors other than the gray scale (such as red for deleted), or add more indicators that can clearly convey what the status of the post is to to the user (such as what we already have for merged threads).

2025-02-08 02:58 UTC, JManion32 commented
To solve the problem, I have made the deleted colors in dark mode shades of gray-blue. This distinguishes them from active posts while also being a better fit for dark mode. Light mode remains unchanged.

**Light Mode (Unchanged)**
![Screenshot 2025-02-07 215215](https://github.com/user-attachments/assets/a47ffc7b-836b-4f35-9ab3-0f69dc9fa76c)

**Dark Mode (Current Main)**
![Screenshot 2025-02-07 215847](https://github.com/user-attachments/assets/619644ad-e596-46e2-a447-dadad0ad4f8c)

**Dark Mode (Proposed Changes)**
![Screenshot 2025-02-07 215318](https://github.com/user-attachments/assets/fd1c9d5c-49d7-4660-9633-90f0d9deeb46)

**Summary of Changes**
![Screenshot 2025-02-07 215417](https://github.com/user-attachments/assets/80038000-dc85-408c-b242-d3e493a54347)

2025-02-11 20:24 UTC, hinyan17 requested changes
This is a nitpick but I think you should swap the colors for "unviewed" and "deleted" for dark mode. This keeps things consistent, where the blue tint means unviewed, and darker color means non-deleted (in light mode, lighter color means non-deleted).

2025-02-14 18:04 UTC, JManion32 commented
The colors are now easier to differentiate from the standard viewed / unviewed posts.

New Dark Mode:
![image](https://github.com/user-attachments/assets/467b7a32-960a-4eb9-a0a5-3601ed8a5ade)

Summary of New Changes:
![image](https://github.com/user-attachments/assets/068e7d22-7e37-4e4c-8edf-096fd1c8cd29)

2025-02-18 21:25 UTC, max1dyer reviewed
I like the choices of color for unviewed and deleted, but I think deleted might be a little too dark. Right now deleted and viewed look a little similar. I think making deleted just a little bluer would improve the visibility.

2025-02-21 21:11 UTC, hinyan17 approved these changes
The new colors stand out nicely. Although they don't follow the coloring convention I mentioned earlier they still make sense.

2025-02-21 22:05 UTC, JManion32 approved these changes
All tests are passing and the colors look much better in dark mode.

2025-02-22 02:37 UTC, williamjallen reviewed
Hmm, I'm not convinced that changing the background color is the right way to convey the fact that the post has been deleted.  Instead, I think it would make sense to show more of a "disabled" look by changing the color of the font itself.  See [this](https://ux.stackexchange.com/questions/146988/how-to-indicate-disabled-list-items-in-a-list-with-alternating-backgrounds) post for an example of what I'm imagining.  Thoughts?

2025-02-23 18:33 UTC, bmcutler commented
@williamjallen 
This new requested change is out of scope to the original issue.  The rendering of deleted posts in light mode is fine.  The solution in this PR for dark mode is appropriate.  Let's not overdesign or overcomplicate this feature.  It is only available for instructor users and only available if they enable it.  The use case is tiny.  The current design is fine.

2025-02-23 18:34 UTC, bmcutler approved these changes
I approve the new colors.  Thanks for the PR.

2025-02-23 18:35 UTC, merged