[Testing:CI] Add test for code watcher script #11158
Submitty/Submitty pull request #11237
Opened 2024-12-11 14:31 UTC by Seanlxx256

### [Testing:CI] Add test code watcher

### Please check if the PR fulfills these requirements:

* [ ✔️] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Fixes #11158
The code_watcher.py script currently does not have a dedicated test to validate its functionality. This makes it difficult to ensure the script runs as expected and reacts properly to file system changes.

### What is the new behavior?
This PR introduces a new unit test using unittest to verify the basic functionality of the code_watcher.py script. The test:

- Starts the code_watcher.py script.

- Simulates file creation, modification, and deletion events in the watched directory.

- Checks of code_watcher.py script can detect the changes and trigger the expected behavior within a timeout period.

- Ensures any processes started during the test are terminated and temporary files are cleaned up.

### Other information?
Issue: as mentioned in @#11114, the updated version of watchdog 6.0.0 does not function properly.

2024-12-13 01:15 UTC, williamjallen commented
@IDzyre Can you do an initial review here if you have time?

2024-12-13 02:59 UTC, IDzyre requested changes
I'm not the most knowledgeable in python, and processes, so someone with more knowledge about python and security should review 

To me it seems a little unsafe to have it kill processes, but im not sure.

2024-12-13 02:59 UTC, IDzyre commented on tests/e2e/test_code_watcher.py
> +        self.script_path = Path("/usr/local/submitty/GIT_CHECKOUT/Submitty/.setup/bin/code_watcher.py")
This could be simplified by using some of the previously set variables to reduce possible points of confusion later if the path is changed.

2024-12-22 03:09 UTC, cjreed121 requested changes
Could you verify that bin and sbin are working properly too.

Also, rather than killing first, could you sent a newline in STDIN to try and have it gracefully end.

Lastly, killing it midway through running the installer may cause other issues in CI. I would suggest temporarily moving the install scripts somewhere else, making a substitute shell script which you can verify is run (in the place of the regular shell script), and then finally deleting/swapping back.

2025-04-25 23:52 UTC, bmcutler commented
closing inactive PR

2025-04-25 23:52 UTC, closed without merging