[Feature:Forum] Show upduck list
Submitty/Submitty pull request #11235
Opened 2024-12-10 20:40 UTC by ZheyuDeng

### Please check if the PR fulfills these requirements:
fixes #11191 
This gives instructor the ability to see who has upducked the post more easily.

![image](https://github.com/user-attachments/assets/cae19548-ab4c-4e8d-b14e-ee5880ac5e33)

![image](https://github.com/user-attachments/assets/f4471e9a-9599-44f4-9752-9500a833d6e9)

2025-01-17 21:29 UTC, jeffrey-cordero commented on site/app/controllers/forum/ForumController.php
> +        }
Adding another check for proper access level would be nice here.

2025-01-17 21:34 UTC, jeffrey-cordero commented on site/app/templates/forum/CreatePost.twig
> +    {% if userGroup <= 2 %} {# Show only for instructors and above #}
Perhaps we could also hide the icon if there are no likes for the given post?

2025-01-17 21:35 UTC, jeffrey-cordero requested changes
Most of the proposed changes look good. I think adding that extra security check in the backend method and hiding the icon for posts for with no likes would be helpful changes.

2025-01-23 19:40 UTC, williamschen23 commented on site/app/libraries/database/DatabaseQueries.php
> +            ORDER BY u.user_id ASC
is there a point in ordering it by userids?

2025-01-23 19:40 UTC, williamschen23 commented on site/app/controllers/forum/ForumController.php
> +        $post_id = (int) $post_id;
use intval instead of straight casting

2025-01-28 19:22 UTC, ZheyuDeng commented on site/app/libraries/database/DatabaseQueries.php
> +            ORDER BY u.user_id ASC
I can remove that if you think it is not necessary

2025-01-28 19:40 UTC, ajiang024 approved these changes
The "show upduck list" function works as intended.
To test, I logged in as a student and upduck-ed a post in the Spring 2025 sample discussion forum. I did the same as a TA. Afterward, I logged in as an instructor to test whether or not I could view the upduck list.
The option only appears on posts with upducks, and successfully shows who upduck-ed the post.

2025-01-28 20:11 UTC, williamschen23 commented on site/app/libraries/database/DatabaseQueries.php
> +            ORDER BY u.user_id ASC
I don't have a strong opinion for or against it

2025-01-28 20:24 UTC, williamschen23 requested changes
It should be GET because you are not uploading/updating any data

2025-01-28 20:24 UTC, williamschen23 commented on site/app/templates/forum/CreatePost.twig
> +    {% if userGroup <= 2 and post_up_duck.upduck_count > 0 %} {# Show only for instructors and if there are likes #}
If likes come in, this button will not show. Would it be better for it to show this button regardless?

2025-01-28 20:24 UTC, williamschen23 commented on site/app/controllers/forum/ForumController.php
> +    #[Route("/courses/{_semester}/{_course}/forum/posts/likes/details", methods: ["POST"])]
This should be a GET request

2025-01-28 20:24 UTC, williamschen23 commented on site/public/js/forum.js
> +        type: 'POST',
change to GET here too

2025-01-28 20:26 UTC, williamschen23 requested changes

2025-01-28 20:26 UTC, williamschen23 commented on site/public/js/forum.js
> +        data: { post_id: post_id, csrf_token: csrfToken },
```suggestion
        data: { post_id: post_id, csrf_token: csrf_token },
```

2025-01-28 21:31 UTC, jeffrey-cordero commented on site/app/templates/forum/CreatePost.twig
> +    {% if userGroup <= 2 and post_up_duck.upduck_count > 0 %} {# Show only for instructors and if there are likes #}
This should always be rendered to ensure the dynamic forum page for instructors.

2025-01-28 21:32 UTC, jeffrey-cordero commented on site/app/libraries/database/DatabaseQueries.php
> +            ORDER BY u.user_id ASC
I would remove the sort as someone will eventually bring it up again.

2025-01-28 21:34 UTC, jeffrey-cordero requested changes
Overall, the changes look good. I would recommend removing the sort and ensuring to always render the instructor button, and then it should be good.

2025-01-28 21:39 UTC, williamschen23 requested changes

2025-01-28 21:39 UTC, williamschen23 commented on site/public/js/forum.js
> +        data: { post_id: post_id, csrf_token: csrf_token },
CSFR is not required for get requests

2025-01-28 21:48 UTC, williamschen23 commented on site/app/controllers/forum/ForumController.php
> +        if (!$this->core->getUser()->accessGrading()) {
this should be a instructor check, not accessgrading. At least keep it consistent for when you are showing the icon

2025-01-28 22:34 UTC, williamschen23 requested changes
Last but not least, add cypress tests!

2025-01-31 21:22 UTC, jeffrey-cordero approved these changes
New feature looks great for fetching the like list as an instructor. A future issue would be adding Cypress tests as another mentioned, but it would be an extensive testing file.

2025-02-03 05:13 UTC, merged