[Refactor:Forum] Move getEditPostContent to doctrine
Submitty/Submitty pull request #11239
Opened 2024-12-12 15:36 UTC by lavalleeale

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

When getting the details needed to edit a post, currently doctrine is not being used.

### What is the new behavior?
When getting the details needed to edit a post, currently doctrine will be used.

### Other information?

This should not change functionality in any way.

2024-12-22 02:40 UTC, cjreed121 requested changes

2024-12-22 02:40 UTC, cjreed121 commented on site/.performance_warning_ignore.json
> +  "/courses/<term>/<course>/forum/posts/delete",
Why is the delete route being added in this PR?

2025-02-14 20:47 UTC, grt812 reviewed
Code looks good, but it seems that deleting attachments does not work when editing. To elaborate, the attachments do not show in the thread UI when you first delete them, but in the popup editor, it seems that the attachments aren't actually deleted. This behavior is not the same on main. Perhaps deleted attachments are still stored in the database but just not displayed on both branches? If so, I am unsure if this is within the scope of the PR.

2025-02-21 21:57 UTC, DarthNyan approved these changes
Code looks good. I haven't tested.

2025-03-04 03:04 UTC, DarthNyan requested changes
![{AFD3313E-BDC5-43F5-A803-D467D5A1FE36}](https://github.com/user-attachments/assets/7ae0bc30-b514-4e7b-886a-12eb8c742afa)

Some bugs around title & date fetching. Categories, content, attachments seem to work.

2025-03-18 09:28 UTC, grt812 commented
> ![{AFD3313E-BDC5-43F5-A803-D467D5A1FE36}](https://private-user-images.githubusercontent.com/89590361/418815720-7ae0bc30-b514-4e7b-886a-12eb8c742afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIyODkwMzYsIm5iZiI6MTc0MjI4ODczNiwicGF0aCI6Ii84OTU5MDM2MS80MTg4MTU3MjAtN2FlMGJjMzAtYjUxNC00ZTdiLTg4NmEtMTJlYjhjNzQyYWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE4VDA5MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzNhZWU1MzllMDU2NTIyNDcwOWE2YWUzMzNhZDlkYjU4YmI1ZjhkMDk0MjNkMDUwYjA2MGZmZDM0NzU0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t3is3jd7bbDUedaGO0FewwGgYhrlNbh5flaKo9ciSUg)
> 
> Some bugs around title & date fetching. Categories, content, attachments seem to work.

I wasn't able to reproduce this. Could you elaborate how you got this error?

2025-04-07 17:29 UTC, Troy-bailan-King requested changes
Need to solve the code conflicts

2025-06-04 18:39 UTC, lavalleeale reviewed
Functionality tested and code looks good to me, should have the same behavior as previous. I can't approve this since I'm technically the owner however.

2025-06-04 18:41 UTC, JManion32 approved these changes
Me and Alex approve

2025-06-05 19:14 UTC, merged