[Bugfix:TAGrading] Simple Gradeable CSV Upload
Submitty/Submitty pull request #11259
Opened 2024-12-22 17:56 UTC by williamschen23

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2025-02-07 23:01 UTC, grt812 requested changes
Functionality works as expected. I tested blank values, extra cell in row, missing cells, wrong total, string instead of float, wrong total type. All work as expected. Just need to get rid of parseInt on gradeable id (I am unsure if they are needed on the other ones too) and fix styling on dark mode.

2025-02-10 13:45 UTC, williamschen23 commented
> I am unsure if they are needed on the other ones too) and fix styling on dark mode.
Pretty much just for !== instead of != which would need a eslint override

2025-02-11 19:42 UTC, grt812 approved these changes

2025-02-18 00:24 UTC, polibear21 approved these changes
The code looks good to me. After testing, I found that the CSS background colors do display. The values in the gradable text also change.

2025-02-22 02:33 UTC, williamjallen approved these changes
These changes seem reasonable to me.  Even though the new code might not be ideal, it's worth noting that the surrounding code is rather poor and this change is a definite improvement over the previous code.  I did not test this manually.

2025-02-22 17:46 UTC, merged