[Bugfix: Developer] Removed getUserId method and replaced usage with getUser()->getId()
Submitty/Submitty pull request #11267
Opened 2024-12-28 12:28 UTC by DuaaScripts

- Removed the `getUserId()` method that was not being used in the codebase.
- Replaced all occurrences of `getUserId()` with `getUser()->getId()` where necessary.

## Questions

I did not make any changes to static methods/variables, as it wasn't clear which static types needed to be verified or refactored. Could you please clarify if there are specific static methods that need to be addressed?

## Feedback Request

Would appreciate feedback on the changes I've made to ensure everything is correct and aligned with the project's standards.

2024-12-28 16:52 UTC, cjreed121 requested changes
This is not the desired change for this issue. Instead, you should only be removing the `$user_id` member variable from `Core.php` and then improving some of the type hints as they are not correct with their default values. No other PHP files should be need to be changed for this PR.

2024-12-29 06:40 UTC, DuaaScripts commented
@cjreed121 Thank you for the feedback!  I’ll remove the $user_id member variable from Core.php and fix the type hints as per your suggestion. I’ll update the PR shortly with these changes. @cjreed121

2024-12-29 09:25 UTC, DuaaScripts commented
@cjreed121 
I’ve made the requested changes:
- Removed the $user_id member variable from Core.php.
- Updated the type hints where they were incorrect or didn’t match the expected values.
- 
Please let me know if anything else needs to be improved, or if I missed anything! Looking forward to your feedback.

2024-12-29 14:21 UTC, cjreed121 commented
Please revert changes to all other files besides `Core.php` in this PR

2024-12-29 15:41 UTC, DuaaScripts commented
@cjreed121 
Done with the changes, ready for review

2024-12-29 16:51 UTC, cjreed121 commented
Please address the failing PHP lint test. Static analysis may also fail so make sure to run them locally first.

2024-12-29 17:43 UTC, DuaaScripts commented
@cjreed121 
I've tried to fix the PHP lint errors. waiting for your review.

2024-12-29 22:09 UTC, cjreed121 commented
Please fix PHP static analysis test and verify it passes locally. See https://submitty.org/developer/testing/linting_static_analysis#php-static-analysis for more details on how to run it and regenerate the baseline.

2025-01-02 08:41 UTC, DuaaScripts commented
@cjreed121 
I’ve fixed the PHPStan error and tested the code locally. Hopefully, the tests will pass now. 
Looking forward to your review! 😊

2025-01-02 15:35 UTC, cjreed121 commented
Please update the PR description to reflect new changes. Remove the "Fixes ..." since this does not address the whole issue since there will need to be a bit more done but we can get this merged first. Still mention the issue but with some other keyword than "Fixes" or "Closes".

2025-01-02 16:08 UTC, DuaaScripts commented
@cjreed121  Done!

2025-01-02 16:13 UTC, cjreed121 commented
The description changes have not been updated. The description says you removed a certain method when you did not. Please address this.

Also no need to ping me for every change and don't hit the update branch button unless you need to pull in other changes or resolve conflicts.

2025-01-02 17:13 UTC, cjreed121 approved these changes

2025-01-06 12:17 UTC, williamschen23 approved these changes

2025-01-16 03:48 UTC, merged