[Bigfix:Submission] Restrict access to Leaderboard page for inaccessible gradeables
Submitty/Submitty pull request #11261
Opened 2024-12-22 19:15 UTC by amRohitKumar

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [x] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixes #11100 

### What is the new behavior?
If the gradeable is not visible, the leaderboard will also not be visible.

![image](https://github.com/user-attachments/assets/ae288344-c9d5-44fb-b086-df5fe5ee6cb0)

### Other information?

2025-01-19 17:15 UTC, williamjallen requested changes
@amRohitKumar These changes seem reasonable to me, but it looks like the CI failed.  Can you fix those errors?  It would also be great if you could add a Cypress test to verify that this fix works, and continues to work in the future.

2025-02-22 15:29 UTC, jeffrey-cordero commented on site/app/controllers/student/LeaderboardController.php
> +                && !$gradeable->isTaGradeReleased()
Leaderboard should still be visible to students with no TA grades to mimic an actual competition. I would look into making `tryGetElectronicGradeable` from `SubmissionController` into a shared method within the extending class `AbstractController`.

2025-02-22 15:30 UTC, jeffrey-cordero requested changes
The changes do seem to block students/TA's from seeing the future leaderboard, but when the submissions are open, neither account can access the gradeable.

2025-03-11 21:18 UTC, jeffrey-cordero approved these changes
The changes look solid. Leaderboard access is now restricted for future leaderboard assignments.

2025-04-25 19:38 UTC, williamjallen approved these changes

2025-04-25 19:39 UTC, merged