[TAGrading:Feature]
Submitty/Submitty pull request #5643
Opened 2020-07-07 17:36 UTC by jchulton

### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
closes #5349 
### What is the current behavior?
All peer grading is double blind grading (neither the student nor the grader know eachother's id). All other grading is non-blind (the grader knows the student id) .
### What is the new behavior?
Peer grading for a gradeable can be set to double blind, single blind (the grader can see the student id, but the student can't see the grader id) or unblind in the edit gradeable menu. Limited Access grader grading can be set to unblind or blind. Instructors and full access graders can enter an anon grading mode in the grading details page (similar to blind grading).

![image](https://user-images.githubusercontent.com/11095297/86820319-de72b000-c056-11ea-9ad0-91b2ef081c1d.png)

### Other information?

2020-07-11 20:41 UTC, bmcutler commented
Got this error attempting to either grade or open create edit gradeable on an existing gradeable:

Oh no! Something irrecoverable has happened...

ParseError (Code: 0) thrown in /usr/local/submitty/site/app/views/grading/ElectronicGraderView.php (Line 850) by:
        if (!$peer && $gradeable->getLimitedAccessBlind() !== 2l) {


Message:
syntax error, unexpected 'l' (T_STRING)

Stack Trace:
#0 /usr/local/submitty/site/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/usr/local/submitty/site/vendor/composer/../../app/views/grading/ElectronicGraderView.php')
#1 unknown file(unknown line): Composer\Autoload\ClassLoader->loadClass('app\views\grading\ElectronicGraderView')
#2 /usr/local/submitty/site/app/libraries/Output.php(374): spl_autoload_call('app\views\grading\ElectronicGraderView')
#3 /usr/local/submitty/site/app/libraries/Output.php(201): app\libraries\Output->getView('app\views\grading\ElectronicGraderView')
#4 /usr/local/submitty/site/app/libraries/Output.php(170): app\libraries\Output->renderTemplate('grading\ElectronicGrader', 'popupStudents')
#5 /usr/local/submitty/site/app/controllers/admin/AdminGradeableController.php(268): app\libraries\Output->renderOutput(Array, 'popupStudents')
#6 /usr/local/submitty/site/app/controllers/admin/AdminGradeableController.php(28): app\controllers\admin\AdminGradeableController->editPage(app\models\gradeable\Gradeable, 'f20', 'sample', 0)
#7 unknown file(unknown line): app\controllers\admin\AdminGradeableController->editGradeableRequest('peer_gradeable', 0)
#8 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(217): call_user_func_array(Array, Array)
#9 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(195): app\libraries\routers\WebRouter->run()
#10 /usr/local/submitty/site/public/index.php(127): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)



============================


Got this error when attempting to make a new gradeable:




Oh no! Something irrecoverable has happened...

app\exceptions\DatabaseException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/database/DatabaseQueries.php (Line 4192) by:
                throw new DatabaseException("Electronic gradeable didn't have an entry in the electronic_gradeable table!");


Message:
Electronic gradeable didn't have an entry in the electronic_gradeable table!

Stack Trace:
#0 unknown file(unknown line): app\libraries\database\DatabaseQueries->app\libraries\database\{closure}(Array)
#1 /usr/local/submitty/site/app/libraries/database/DatabaseRowIterator.php(56): call_user_func(Closure, Array)
#2 /usr/local/submitty/site/app/models/gradeable/GradeableList.php(72): app\libraries\database\DatabaseRowIterator->next()
#3 /usr/local/submitty/site/app/controllers/NavigationController.php(29): app\models\gradeable\GradeableList->__construct(app\libraries\Core)
#4 unknown file(unknown line): app\controllers\NavigationController->navigationPage()
#5 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(217): call_user_func_array(Array, Array)
#6 /usr/local/submitty/site/app/libraries/routers/WebRouter.php(195): app\libraries\routers\WebRouter->run()
#7 /usr/local/submitty/site/public/index.php(127): app\libraries\routers\WebRouter::getWebResponse(Symfony\Component\HttpFoundation\Request, app\libraries\Core)

2020-07-18 17:33 UTC, bmcutler commented
@jchulton 
Please merge master and hook up/tweak the double-blind/single-blind variables in 
site/app/templates/grading/electronic/Status.twig
as appropriate.
Thanks!

2020-07-21 15:41 UTC, jchulton commented
The variables have been hooked up

2020-08-19 14:04 UTC, emaicus commented on site/app/templates/grading/electronic/Status.twig
> +        </fieldset>
Why the empty fieldset?

2020-08-19 21:37 UTC, jchulton commented on site/app/controllers/grading/ElectronicGraderController.php
> +        $anon_mode = false;
Removed setting anon_mode to false. Tested and seems fine.

2020-08-19 21:37 UTC, jchulton commented on site/app/controllers/grading/ElectronicGraderController.php
> +        if ($peer && $gradeable->getPeerBlind() == 3) {
Removed this line

2020-08-19 21:38 UTC, jchulton commented on site/app/controllers/grading/ElectronicGraderController.php
> +        if ($gradeable->getLimitedAccessBlind() == 2 && $this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER) {
Removed this line

2020-08-19 21:41 UTC, jchulton commented on site/app/templates/grading/electronic/Status.twig
> +        </fieldset>
Removed

2020-08-19 21:41 UTC, jchulton commented on site/app/controllers/grading/ElectronicGraderController.php
> +        if ($gradeable->getLimitedAccessBlind() == 2 && $this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER) {
I've added a enumeration to Gradeable.php, similar to the user groups in User.php

2020-08-19 21:45 UTC, jchulton commented
I've added an amIBlindGrading function and enum to Gradeable.php for the blind grading. Hopefully this makes things clearer.

2020-09-21 15:13 UTC, emaicus commented on tests/e2e/base_testcase.py
> +#from websocket import create_connection
Un-comment this to help fix travis

2020-09-28 04:54 UTC, jchulton commented on tests/e2e/base_testcase.py
> +#from websocket import create_connection
Fixed

2020-11-07 17:36 UTC, bmcutler commented
@jchulton @emaicus 
What is the status of this PR?

2020-11-09 07:18 UTC, jchulton commented
I retested it and it seems to work fine.

2020-11-10 20:20 UTC, emaicus requested changes
This PR is mostly working, but isn't perfect. Student ids are being exposed in the source of the grading and submission pages (after grades are released).

2020-11-11 18:50 UTC, emaicus commented
I advise that this PR be updated to pass Travis, then merged. Once this PR is merged, work should be done on #5783 to fix any new issues. I can then review #5783 so that it can be merged.

2020-11-14 03:29 UTC, jchulton commented
Alright, this PR should be good to merge then

2020-11-15 05:22 UTC, jchulton commented
I believe I have patched all of the student id exposure (on a separate branch but I can merge to this one). The testing PR is proving more difficult due to changes to sample courses.

2020-11-16 16:12 UTC, merged