[Refactor: InstructorUI] Remove support for old TA-grading interface
Submitty/Submitty pull request #5859
Opened 2020-08-31 15:47 UTC by mukul-kmr-jha

### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Currently, we have two TA grading interfaces the legacy (old) Interface and the new one. The new TA grading interface is in the beta stage and can be checked out by tapping out the`tag-icon` provided on the old interface toolbar. (It has `/beta` in its URL endpoint)

### What is the new behavior?
Removed support for the old TA-grading interface and set the new interface as the default one.

### Other information?

2020-12-15 07:48 UTC, mukul-kmr-jha commented
Hi @bmcutler , really sorry for no catch up on this one, I'm going to fix the merge conflicts and push the changes ASAP, thanks!

2021-01-11 19:03 UTC, bmcutler commented
@mukul-kmr-jha 
Are you able to help with the merge conflicts?
We would like to merge this ASAP.  Thanks!

2021-01-14 08:16 UTC, mukul-kmr-jha commented
Sure, adding the changes

.

2021-01-15 22:41 UTC, bmcutler commented
@shailpatels 
This PR seems to be passing the github action php lint but failing the travis php lint.
Can you investigate?

2021-01-16 16:33 UTC, shailpatels commented
@bmcutler  hmm not sure yet, travis and gh actions seem to use the same version for phpcs and phpstan so not sure what the difference might be.

@MasterOdin any ideas ? Do you think its the version of PHP travis is running against, I think on github its grabbing whatever's the latest

2021-01-18 22:06 UTC, emaicus approved these changes
I applied a patch to remove the linting warnings/some errors that were being thrown on the TA grading page. I think that this PR looks good to go.

2021-01-19 01:55 UTC, MasterOdin requested changes

2021-01-19 01:55 UTC, MasterOdin commented on site/app/views/grading/ElectronicGraderView.php
> +        $return . <<<HTML
```suggestion
        $return .= <<<HTML
```

2021-01-19 02:07 UTC, MasterOdin commented
@bmcutler, @shailpatels The difference between Travis and GitHub actions is that the former is using PHP 7.2 and the latter is using PHP 7.4. In PHP 7.3, ("flexible heredocs")[https://www.php.net/manual/en/migration73.new-features.php] were introduced which lifted some of the rigorous requirements of heredocs of prior PHP versions, including that the closing tag had to have no indentation. In PHP 7.2 and before, if the closing tag was indented, it was not considered as a closing tag, and so would keep parsing till it found one. This then makes the file end up in a very weird state for phpstan / phpcs to scan and so we get a ton of weird error messages. In PHP 7.3+, you can now have indentation.

The block that @emaicus edited in his commit had this indented heredoc closing tag:
https://github.com/Submitty/Submitty/blob/fdd96da52b6d0872f5d7b6cd4e60996ea5236603/site/app/views/grading/ElectronicGraderView.php#L1063-L1068

and so the proper way to write it would be:

```php
         return $return . <<<HTML 
                                              </div> 
                                          </div> 
                                      </div> 
                          		</div> 
HTML; 
```

2021-01-19 13:04 UTC, shailpatels approved these changes

2021-01-19 18:54 UTC, bmcutler commented
@MasterOdin 
I committed your edit, but now its failing php linting???

2021-01-20 16:33 UTC, merged