[WIP] [Feature:InstructorUI] Add registration subsection
Submitty/Submitty pull request #6145
Opened 2021-01-19 04:20 UTC by vikrsri

### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
There is currently no way to put students into subsections, allowing further sorting of students.
Addresses #6064.

### What is the new behavior?
This PR adds a registration subsection that can be set by an instructor. Further PR's will allow sorting and grading by students' registration subsections.

2021-01-19 17:47 UTC, bmcutler requested changes

2021-01-19 17:47 UTC, bmcutler commented on migration/migrator/migrations/course/20210113174909_registration_subsection.py
> +    database.execute('ALTER TABLE users DROP IF EXISTS registration_subsection')
I don't think it should be necessary to delete this column in the down migration (we don't want to lose data if we temporarily revert this PR).

2021-01-19 17:47 UTC, bmcutler commented on migration/migrator/migrations/course/20210113174909_registration_subsection.py
> +    database.execute('ALTER TABLE users ADD COLUMN registration_subsection character varying(255)')
Make this an 'add if does not exist' 
(see other migration files for exact syntax)

2021-01-22 04:59 UTC, bmcutler approved these changes
Quick code review and quick test look ok!  Thanks!
This is what we agreed for the step 1 PR.

@MasterOdin -- @vikrsri and I discussed the unexpected additional edits to the .sql file (changes were made using the postgres dump instructions... ).  Can you please review and advise?

2021-01-22 11:25 UTC, MasterOdin approved these changes

2021-01-22 11:25 UTC, MasterOdin commented on site/app/models/User.php
> +    }
you can get rid of this function, it's not needed (as using `@prop` annotation automatically makes available this getter field.

2021-01-22 11:25 UTC, MasterOdin commented on site/app/models/User.php
> +
you can get rid of this function, it's not needed (as using `@prop` annotation automatically makes available this setter field.

2021-01-22 11:26 UTC, MasterOdin commented
The SQL file changes are fine. The `gradeable_access` table was added by hand in #5623 and then no one has run the dump DB command since then. The reason for that it looks like `gradeable_access`'s schema changed is that `SERIAL` is a pseudo-type in postgresql that translates under the hood to creating a sequence, assigning ownership, etc. It's a shorthand that the pg_dump command does not use, as it is more inline with how the data structures are actually stored in the DB.

2021-01-23 23:12 UTC, merged