[Bugfix:SubminiPolls] Add Correct Response Requirement
Submitty/Submitty pull request #6181
Opened 2021-02-05 00:21 UTC by BenKelly99

### What is the current behavior?
Closes #6177
Currently, polls are able to be submitted if there are no correct responses.

### What is the new behavior?
Now, each poll is required to have at least 1 correct response.

2021-02-05 01:11 UTC, MasterOdin commented
I was able to hit an error state where on editing a poll, if I de-selected a correct answer, it would then block me from submitting until I added a new question and then marked it as correct. If I got rid of the new question, I would then be blocked again. See https://www.loom.com/share/7685992435fe410f91d5167f55eac9f4 as an example of it.

2021-02-05 01:11 UTC, MasterOdin requested changes
I was able to hit an error state where on editing a poll, if I de-selected a correct answer, it would then block me from submitting until I added a new question and then marked it as correct. If I got rid of the new question, I would then be blocked again. See https://www.loom.com/share/7685992435fe410f91d5167f55eac9f4 as an example of it.

2021-02-05 01:34 UTC, BenKelly99 commented
@MasterOdin the problem with editing should be fixed now.

2021-02-05 02:52 UTC, shailpatels requested changes

2021-02-05 02:52 UTC, shailpatels commented on site/app/controllers/PollController.php
> +            return MultiResponse::RedirectOnlyResponse(
If you are returning only 1 response type you can just do
```php
return new RedirectResponse($this->core->buildCourseUrl(['polls'])) 
```

2021-02-05 02:52 UTC, shailpatels commented on site/app/controllers/PollController.php
> +                new RedirectResponse($this->core->buildCourseUrl(['polls']))
same as above comment

2021-02-05 02:52 UTC, shailpatels commented on site/app/templates/polls/NewPollPage.twig
> +                        <input aria-label="Is correct" class="correct_box" type=checkbox name="is_correct_{{response}}" {{ poll.isCorrect(response) ? "checked": "" }}>
CSS classes and Id's should use dashes instead of underscores:
https://submitty.org/developer/coding_style_guide/css

2021-02-05 02:52 UTC, shailpatels commented on site/app/templates/polls/NewPollPage.twig
> +        } else if ($(".correct_box:checked").length == 0) {
For JS you should use `===` in order to prevent accidentally implicit type conversions

2021-02-08 02:10 UTC, MasterOdin approved these changes
As indicated in #6177, an update to the website docs would not be amiss to indicate that at least one correct response should be made, and that for polls without any definitive right answer (e.g. asking preferred OS), all answers should be marked as correct.

2021-02-08 02:27 UTC, merged