[UI/UX:HelpQueue] Truncate Queue Statistics
Submitty/Submitty pull request #6252
Opened 2021-03-01 15:01 UTC by A3Digital

### Please check if the PR fulfills these requirements:
* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
The average time displays several decimal places for the seconds if they're non-zero.
Fixes #6179

### What is the new behavior?
The average time is always truncated to the nearest second.

2021-03-04 00:22 UTC, MasterOdin requested changes

2021-03-04 00:22 UTC, MasterOdin commented on site/app/libraries/database/DatabaseQueries.php
>                  SUM(CASE
Can you extract the common part of all of these queries (it looks like would cover it:

```
                 COUNT(*) AS queue_interactions,
                 COUNT(DISTINCT name) AS number_names_used,
                 COUNT(DISTINCT user_id) AS number_distinct_students,
                 AVG(time_out - time_help_start) AS avg_help_time,
                 DATE_TRUNC('second', AVG(time_out - time_help_start)) AS avg_help_time,
                 MIN(time_out - time_help_start) AS min_help_time,
                 MAX(time_out - time_help_start) AS max_help_time,
                 AVG(time_help_start - time_in) AS avg_wait_time,
                 DATE_TRUNC('second', AVG(time_help_start - time_in)) AS avg_wait_time,
                 MIN(time_help_start - time_in) AS min_wait_time,
                 MAX(time_help_start - time_in) AS max_wait_time,
                 SUM(CASE
                   WHEN removal_type IN ('helped', 'self_helped') THEN 1
                   ELSE 0
                 END) AS help_count,
                 SUM(CASE
                   WHEN removal_type IN ('removed', 'emptied', 'self') THEN 1
                   ELSE 0
                 END) AS not_helped_count
```
)

into a private function that then gets called and appended into these queries?

e.g.

```
private function getInnerQueueSelect(): string {
    return <<<SQL
                 COUNT(*) AS queue_interactions,
                 COUNT(DISTINCT name) AS number_names_used,
                 COUNT(DISTINCT user_id) AS number_distinct_students,
                 AVG(time_out - time_help_start) AS avg_help_time,
                 DATE_TRUNC('second', AVG(time_out - time_help_start)) AS avg_help_time,
                 MIN(time_out - time_help_start) AS min_help_time,
                 MAX(time_out - time_help_start) AS max_help_time,
                 AVG(time_help_start - time_in) AS avg_wait_time,
                 DATE_TRUNC('second', AVG(time_help_start - time_in)) AS avg_wait_time,
                 MIN(time_help_start - time_in) AS min_wait_time,
                 MAX(time_help_start - time_in) AS max_wait_time,
                 SUM(CASE
                   WHEN removal_type IN ('helped', 'self_helped') THEN 1
                   ELSE 0
                 END) AS help_count,
                 SUM(CASE
                   WHEN removal_type IN ('removed', 'emptied', 'self') THEN 1
                   ELSE 0
                 END) AS not_helped_count
SQL;
}
```

We should try and follow the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle here, and make it easier to modify the next time through.

2021-03-06 22:16 UTC, shailpatels approved these changes
Changes look good and works as described
Precision for avg time restricted to two places
```

1 | 1 | 00:00:02 | 00:00:02 | 00:00:02 | 10 days 21:58:08 | 10 days 21:58:08 | 10 days 21:58:08 | 1 | 0



```

2021-03-08 17:42 UTC, MasterOdin approved these changes

2021-03-08 17:43 UTC, merged