[TAGrading:Feature] Rubric component wraparound
Submitty/Submitty pull request #6299
Opened 2021-03-17 19:33 UTC by DefinitiveAbove

### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)

### What is the current behavior?
Clicking the up arrow at the top of the grading rubric does not wrap around to the bottom, clicking the bottom arrow at the bottom of the grading rubric does not wrap around to the top.

### What is the new behavior
Works on #4739 
Clicking the up arrow at the top of the grading rubric wraps around to the bottom, clicking the bottom arrow at the bottom of the grading rubric wraps around to the top.

2021-03-18 03:47 UTC, MasterOdin commented on site/public/js/ta-grading.js
>      // Last component is open, scroll to general comment for easier access
```suggestion
    // Last component is open, close it and then open and scroll to first component
```

2021-03-18 03:47 UTC, MasterOdin commented on site/public/js/ta-grading.js
> +    // First component is open, so open the last one
```suggestion
    // First component is open, close it and then open and scroll to the last one
```

2021-03-18 03:47 UTC, MasterOdin commented on site/public/js/ta-grading.js
>      // Last component is open, scroll to general comment for easier access
Need to make sure we keep comments up-to-date with what the code behavior is :)

2021-03-22 11:28 UTC, shailpatels requested changes
Works fine for normal rubrics for individual and team gradeables.

For peer gradeables there is an issue where pressing the up arrow at the first component or 
pressing the down arrow at the last component (i.e trying to loop around) causes the alert message:

`Are you sure you want to delete the custom mark?` consistently 

The following JS console error also is logged:

`Uncaught (in promise) undefined`

2021-03-31 14:50 UTC, KKhaghani approved these changes
Tested the new behavior after the peer component fix, looks good.

2021-04-06 20:40 UTC, shailpatels approved these changes
Changes look good and works as described

2021-04-07 02:01 UTC, merged