[Feature:System] Add support for ldap authentication
Submitty/Submitty pull request #6482
Opened 2021-05-22 16:38 UTC by MasterOdin

### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Closes #2054 

Submitty does not currently support using LDAP to authenticate users.

### What is the new behavior?

Adds LDAP support for Submitty.

### Other information?

2021-10-30 03:10 UTC, MasterOdin commented on .setup/CONFIGURE_SUBMITTY.py
> +        json.dump(config, json_file, indent=2)
What do you mean? All changes in this file (and throughout the PR) have 4 spaces for indentation it looks like?

2021-10-30 17:48 UTC, williamjallen commented on .setup/CONFIGURE_SUBMITTY.py
> +        json.dump(config, json_file, indent=2)
Perhaps I misunderstood then.  I thought the `indent=2` parameter indented each level of the JSON by 2 spaces.

2021-10-31 00:24 UTC, MasterOdin commented on .setup/CONFIGURE_SUBMITTY.py
> +        json.dump(config, json_file, indent=2)
Oh, I thought you were talking about indentation in the python file, not the argument. You're right, this should be `indent=4`.

As a note, this is a great usage of the `suggestion` PR comment, like so:
````
```suggestion
        json.dump(config, json_file, indent=2)
```
````

This gets rendered as:

```suggestion
        json.dump(config, json_file, indent=4)
```

(Not sure if you knew about this)

2021-10-31 16:12 UTC, williamjallen requested changes

2021-10-31 16:12 UTC, williamjallen commented on migration/migrator/migrations/system/20210918211432_authentication_method.py
> +        json.dump(db_info, db_file, indent=2)
```suggestion
        json.dump(db_info, db_file, indent=4)
```

2021-10-31 16:12 UTC, williamjallen commented on migration/migrator/migrations/system/20210918211432_authentication_method.py
> +        json.dump(db_info, db_file, indent=2)
```suggestion
        json.dump(db_info, db_file, indent=4)
```

2021-10-31 16:12 UTC, williamjallen commented on migration/migrator/migrations/system/20210918211432_authentication_method.py
> +            auth_file.write(json.dumps(auth_info, indent=2))
```suggestion
            auth_file.write(json.dumps(auth_info, indent=4))
```

2021-10-31 16:12 UTC, williamjallen commented on migration/migrator/migrations/system/20210918211432_authentication_method.py
> +            json.dump({'authentication_method': config.database['authentication_method'], 'ldap_options': []}, auth_file, indent=2)
```suggestion
            json.dump({'authentication_method': config.database['authentication_method'], 'ldap_options': []}, auth_file, indent=4)
```

2021-11-22 21:11 UTC, MasterOdin commented
Running a final vagrant up test here: https://github.com/Submitty/Submitty/actions/runs/1492144889

2021-12-02 03:55 UTC, merged