[Feature:Submission] Gradeable Pre-Requisite Locking
Submitty/Submitty pull request #6578
Opened 2021-06-08 14:34 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [x] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Currently there is no support for automatic opening of gradeables for an individual student after they complete a different gradeable.
Closes #3698

### What is the new behavior?
Now there is a support for gradeables to be locked until a student completes the pre-requisite gradeable with a certain autograder score. Until the student completes the gradeable with a high enough score they will not be able to click or submit the next assignment. It will just say locked.
![image](https://user-images.githubusercontent.com/55092742/121204678-0b21df80-c845-11eb-8920-d6d054fd3cfd.png)

2021-06-09 06:33 UTC, DefinitiveAbove requested changes
Tested and everything looks good functionality wise.

I'm not sure if this was brought up before, but maybe instructors (and full/limited access graders?) should be able to ignore the lock on gradeables for testing submissions.

2021-06-09 06:33 UTC, DefinitiveAbove commented on site/app/controllers/admin/AdminGradeableController.php
> +            $depend_gradeable = $this->tryGetGradeable($gradeable->getDependsOn());
It looks like this function is only being called from a HTML-returning route, so false should be passed in as the second parameter to disable JSON rendering.

2021-06-09 06:33 UTC, DefinitiveAbove commented on site/app/templates/admin/admin_gradeable/AdminGradeableAuto.twig
> +            <legend>Points Required to Unlock:</legend>
I think that it should be specified here that the points checked are only autograding points and not the overall score.

2021-06-10 22:13 UTC, DefinitiveAbove approved these changes
Looks good to me!

2021-06-11 14:22 UTC, MasterOdin requested changes

2021-06-11 14:22 UTC, MasterOdin commented on site/app/controllers/admin/AdminGradeableController.php
> +                    $gradeables = new GradeableList($this->core);
Why are you constructing a whole GradeableList here and not just doing a simple existence query check?

2021-06-11 14:22 UTC, MasterOdin commented on migration/migrator/data/course_tables.sql
> +    eg_depends_on character varying(255) DEFAULT NULL::character varying,
Looks like `eg_depends_on` should only be set to null or a valid `g_id`. As such, we should add a [foreign key](https://www.postgresqltutorial.com/postgresql-foreign-key/) constraint to ensure data consistency, as well as handling the case where a gradeable is deleted where another gradeable depends on it.

2021-06-14 21:32 UTC, eddiekrystowski requested changes
Seems to work well for the most part, except when I put 0 points required, it always unlocks the next gradeable, even if I haven't made a submission to the prior one yet.

Steps:
1. Create Assignment 1
2. Create Assignment 2
3. Make Assignment 2 depend on Assignment 1 getting 0 points
4. Assignment 2 can now be done even though nothing has been submitted to Assignment 1

2021-06-15 14:35 UTC, cjreed121 commented
> Seems to work well for the most part, except when I put 0 points required, it always unlocks the next gradeable, even if I haven't made a submission to the prior one yet.
> 
> Steps:
> 
> 1. Create Assignment 1
> 2. Create Assignment 2
> 3. Make Assignment 2 depend on Assignment 1 getting 0 points
> 4. Assignment 2 can now be done even though nothing has been submitted to Assignment 1

@eddiekrystowski Thanks for noticing this. Just a small type error. It seems to work now. Can you give it another try?

2021-06-22 19:33 UTC, eddiekrystowski approved these changes
Works as described. Nice work!

2021-07-07 14:38 UTC, bmcutler commented
@cjreed121 Please resolve merge conflicts

2021-07-07 14:53 UTC, bmcutler commented
When I test this, 
I'm getting "Internal server error" when choose a gradeable.
Maybe it's unrelated to this PR?  Merge conflicts prevent updating to master branch.

2021-07-07 14:55 UTC, bmcutler commented
Maybe the internal server error was related to it being in the a "future" category?  
I wasn't getting the extra info about # of autograding points available -- or maybe I had only picked assignments with no autograding points?

I tried with another gradeable, no internal server error, I did get the message with # of available points, but on leaving the edit gradeable page I got this frog robot message:

<img width="691" alt="Screen Shot 2021-07-07 at 10 53 45 AM" src="https://user-images.githubusercontent.com/5871417/124781951-d3748900-df11-11eb-9a98-742b66912612.png">

2021-07-07 14:56 UTC, bmcutler requested changes
merge conflicts & bugs when tested

2021-07-09 14:10 UTC, bmcutler commented
Installation error:  [ DId I only get this because I've tried to test your PR previously?  Or is this a bug? ]

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) constraint "fk_depends_on" for relation "electronic_gradeable" already exists

[SQL: ALTER TABLE electronic_gradeable ADD CONSTRAINT fk_depends_on FOREIGN KEY(eg_depends_on) REFERENCES electronic_gradeable(g_id);]

2021-07-09 14:13 UTC, cjreed121 commented
That would be since it is already installed but I did not but a if not exists check on the constraint. Now it should be there if you pull again.

2021-07-09 14:23 UTC, bmcutler commented
it shouldn't let you specify a threshold > max (non extra credit) points:
<img width="237" alt="Screen Shot 2021-07-09 at 10 22 32 AM" src="https://user-images.githubusercontent.com/5871417/125092788-b241a300-e09f-11eb-8845-fc464e947a2f.png">

2021-07-19 04:11 UTC, bmcutler requested changes
I tweaked the text, I'm happy with the UI, but we have a twig bug to fix.

When you make a new gradeable...  and immediately go to the autograding tab of edit gradeable, you get a twig error.  I think the error also comes when the gradeable is rebuilt?  

<img width="1203" alt="Screen Shot 2021-07-18 at 11 50 41 PM" src="https://user-images.githubusercontent.com/5871417/126101220-af81ef6e-3563-4ad5-86e8-f62619173042.png">

Also...  the gradeable is rebuilt even when you don't change the config?  I think we discussed that it should only rebuild when the config is changed.  (If that's not too complicated to pull off.)

2021-07-19 14:50 UTC, cjreed121 commented
I could not recreate the last issue you mentioned. I know it was an issue earlier in this PR but that should be fixed. Can you try that again with latest code?

2021-08-09 00:15 UTC, bmcutler approved these changes
yay!

2021-08-09 00:15 UTC, merged