[UI/UX:TAGrading] Fix spacing on Grading Panels Team List
Submitty/Submitty pull request #6619
Opened 2021-06-16 20:26 UTC by eddiekrystowski

### What is the current behavior?
The Team list takes up extra space at the top.
![image](https://user-images.githubusercontent.com/28243927/122286619-0f41a300-cebe-11eb-826a-22e40f1633f4.png)

### What is the new behavior?
The space has been consolidated.
![image](https://user-images.githubusercontent.com/28243927/122285984-5e3b0880-cebd-11eb-8aa9-d73ab6b91488.png)

Also, a quick refactor has been done on `Details.twig` to move some inline table styling to `details.css`.

### Other information?
While this solution doesn't always center the toolbar on all screen sizes, I think it is the best solution since it optimizes the toolbar space up top which leaves the most amount of room for the panels which are the most important parts.

2021-06-17 12:11 UTC, sbelsk approved these changes

2021-06-17 13:32 UTC, loadedskiffer requested changes
I think we should make it a drop down in order to conserve space and still have it centered at the same time.

2021-06-21 19:17 UTC, loadedskiffer approved these changes
Looks good to me and functions properly, Centering is preserved and minimal space is lost. 

> Just show everyone in the meeting tomorrow in case they don't like how the dropdown looks.

2021-06-22 00:23 UTC, bmcutler requested changes
Sorry to say, but we've got to redo the layout of this feature on this page.  
The display of the student name or team is still taking up some of the precious vertical space.  The name needs to be on the left, and the buttons should be arranged in the remaining space on the right.  

The dropdown does not sufficiently fix the problem, there is still wasted vertical space  above the buttons due to the awkward layout/placement of the name(s).

Also, I don't really like the appearance of the dropdown.  
It's implying to me the viewer that I could select to focus grading on a different team member.  So this isn't quite the visual we were going for.

2021-06-22 23:36 UTC, sbelsk reviewed
I don't know if this is the final way the names are going to be displayed, but just I took a lot at this and the page seems to be reacting well when adjusting the window size (it displays the names only if there is horizontal space for them). 
The only thing I noticed is that if you have your window relatively narrow before clicking "grade" on a specific team, when the grading interface loads, the text appears there by default even if there shouldn't be room for it:
![image](https://user-images.githubusercontent.com/71195502/123012603-8aa8c600-d390-11eb-80df-66885ef50203.png)
If you resize the window it immediately fixes itself.

2021-06-23 01:26 UTC, eddiekrystowski commented
Good catch. I'll update that.

2021-06-24 18:01 UTC, loadedskiffer requested changes
The Team names look great and nothing is broken but I'm pretty sure you didn't mean to include some of these changes in this PR.

2021-06-24 18:01 UTC, loadedskiffer commented on site/app/templates/grading/electronic/NavigationBar.twig
> +</script>
Pretty sure this commented out JS is here from when I was working on this and should be removed.

2021-06-24 19:38 UTC, loadedskiffer approved these changes

2021-07-02 04:30 UTC, bmcutler commented
@eddiekrystowski or @williamjallen  
Please resolve conflicts

2021-07-02 04:34 UTC, bmcutler approved these changes
tested quickly, yes, I like this now :). Thanks!

2021-07-06 18:51 UTC, bmcutler commented
@eddiekrystowski or @williamjallen
Please resolve conflicts

2021-07-07 23:27 UTC, bmcutler commented
@eddiekrystowski
Please look into failing test case...

2021-07-08 00:24 UTC, eddiekrystowski commented
@bmcutler Just flaky e2e tests, all good now.

2021-07-08 14:55 UTC, merged