[Dependency:Developer] Remove vbguest
Submitty/Submitty pull request #6659
Opened 2021-06-23 13:21 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Currently we use the vbguest plugin in vagrant. This is no longer necessary and creating issues while installing Ubuntu 20.04.

### What is the new behavior?
This PR removes the check for requiring vbguest.

### Other information?
To test make sure you remove vbguest from your system.
This can be done by doing: `vagrant plugin uninstall vagrant-vbguest`
Docs will also be updated to remove the step saying this is a requirement.

2021-06-23 14:02 UTC, MasterOdin requested changes
Have you manually triggered the Vagrant CI action to confirm that that runs through?

2021-06-23 14:02 UTC, MasterOdin commented on Vagrantfile
> -unless Vagrant.has_plugin?('vagrant-vbguest') || ENV.has_key?('SKIP_VBGUEST')
We can remove usage of the `SKIP_VBGUEST` flag from the vagrant CI job.

2021-06-23 14:15 UTC, cjreed121 commented
Just started them now [https://github.com/Submitty/Submitty/actions/runs/964612347](https://github.com/Submitty/Submitty/actions/runs/964612347). Will comment here the results.

2021-06-23 15:51 UTC, cjreed121 commented
Both 18.04 and 20.04 passed on the Vagrant CI action.

2021-06-23 19:00 UTC, cjreed121 commented
Documentation updated at https://github.com/Submitty/submitty.github.io/pull/351

2021-06-24 23:57 UTC, MasterOdin approved these changes

2021-06-25 02:03 UTC, merged