[Bugfix:Developer] Force Composer Install on Vagrant
Submitty/Submitty pull request #6735
Opened 2021-07-13 14:24 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
There are quite a few developers here that use PHPStorm rather than the code watcher script. PHPStorm will copy the files directly into the site folder while vagrant will copy the changes into the GIT repo on the VM. When a composer package is added or removed the changes would usually be found by the rsync command. The rsync only finds differences between site folder and GIT repo site folder which will always be equivalent with PHPStorm and therefore never update. This causes Submitty to break on the VM anytime a new composer package is installed and used in code.

### What is the new behavior?
The install script will always run composer install if using vagrant. In most cases the install script would just say nothing to install/remove and not slow anything down.

This also contains an addition to exclude from rsync for CSS linting as there is no reason to compare/send that.

2021-07-16 20:29 UTC, MasterOdin requested changes
I'm fine adding a way to force `composer install` to run, but this should be behind a runtime flag, and not always run within vagrant. I have no interest in having `composer install` run every time I run the installer as I do not use PHPStorm hooked directly into the installed site.

For context, I added these checks in as I've (and also @bmcutler) done work on Submitty while offline and wanted to avoid composer/npm failures around networking.

2021-07-16 20:35 UTC, cjreed121 commented
> I'm fine adding a way to force `composer install` to run, but this should be behind a runtime flag, and not always run within vagrant. I have no interest in having `composer install` run every time I run the installer as I do not use PHPStorm hooked directly into the installed site.
> 
> For context, I added these checks in as I've (and also @bmcutler) done work on Submitty while offline and wanted to avoid composer/npm failures around networking.

Yeah that sounds like a better option. I wasn't sure what the best way to go about this initially so I went with vagrant. Where would I put this runtime flag? Would this be something that goes on vagrant up or how does it work? I would also want to do this check everywhere the rsync command gets called as it also affects permissions, npm, and maybe something else.

2021-07-16 20:46 UTC, MasterOdin commented
The flag itself only needs to exist on the installer as the `vagrant up` is not affected by where PHPStorm is hooking in.

2021-09-12 17:53 UTC, MasterOdin approved these changes
Added a `shift` when we use the `quick` command so that `clean quick test` would work as expected. Otherwise, this looks fine. We probably want to add some documentation of using `quick` to the https://submitty.org/developer/phpstorm docs page?

2021-09-12 17:55 UTC, merged