[Bugfix:Submission] Fix Notebook Display bugs
Submitty/Submitty pull request #6748
Opened 2021-07-15 18:12 UTC by loadedskiffer

### What is the current behavior?

### What is the new behavior?

### Other information?

2021-07-18 15:08 UTC, williamjallen approved these changes

2021-07-18 15:08 UTC, williamjallen commented on site/app/templates/submission/homework/SubmitBox.twig
> +                    <input type="file" name="files" id="input-file{{ loop.index }}" class="hide" onchange="addFilesFromInput({{ loop.index }})" multiple aria-label="Select Files to upload"
you could use a ternary operator here if you want to make it fit on one line

2021-07-21 06:03 UTC, bmcutler requested changes
I think it looks good, but I'm not ready to approve this because I'm getting stuck testing the manual grading of notebook gradeables.  I get this twig error:

<img width="816" alt="Screen Shot 2021-07-21 at 1 52 31 AM" src="https://user-images.githubusercontent.com/5871417/126439040-3619450a-dcea-46cb-98c5-310a3a7c4973.png">

(seems like it is also broken on master)

2021-07-27 14:26 UTC, bmcutler commented
another twig error:

<img width="980" alt="Screen Shot 2021-07-27 at 10 24 10 AM" src="https://user-images.githubusercontent.com/5871417/127171414-d01e3fea-9f5a-4ea9-9778-5d81309307a6.png">

I got this clicking on ta grading for Notebook basic for the instructor user, which I had submtited to once.

It looks like it might be related to @DefinitiveAbove recent work?

2021-07-28 13:48 UTC, williamjallen requested changes
Code looks good.  I was able to produce the following Twig error by following the below sequence:
1. Closing the notebook_time_limit gradeable
2. Giving the user "student" a 1-day extension
3. Viewing the gradeable from the student account

![Untitled](https://user-images.githubusercontent.com/16820599/127333434-159e8f98-7fde-4965-8636-f72cea73d225.png)

2021-07-29 17:22 UTC, williamjallen approved these changes

2021-07-30 03:35 UTC, merged