[Bugfix:Developer] Adjust Markdown on Autograding Examples
Submitty/Submitty pull request #6827
Opened 2021-07-27 14:22 UTC by eddiekrystowski

### What is the current behavior?
The headers in `more_autograding_examples` uses the `###header` syntax.

### What is the new behavior?
The headers in `more_autograding_examples` uses the `### header` syntax to fit with the new [League/CommonMark](https://commonmark.thephpleague.com/) engine.

2021-07-27 18:16 UTC, loadedskiffer commented on more_autograding_examples/notebook_basic/config/config.json
>          // ======================================================================================================
forgot 1 space

2021-07-27 18:17 UTC, loadedskiffer requested changes
You forgot 1 space on line 108 of the notebook basic config, also do you think it makes sense to fix the back tick issue in this pr as well?

2021-07-27 20:09 UTC, eddiekrystowski commented
Thanks for catching that. Can you clarify what the backtick issue is?

2021-07-27 20:48 UTC, loadedskiffer approved these changes

2021-07-28 06:19 UTC, bmcutler approved these changes

2021-07-28 06:20 UTC, merged