[Feature:CourseMaterials] Course Materials New Tag
Submitty/Submitty pull request #6848
Opened 2021-07-29 18:56 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Right now you are only able to see what course materials there are but may be unsure if there is a new course material added.
Closes #5383

### What is the new behavior?
A new tag will appear to the right of the course material if it has not been viewed. Viewing, downloading, or downloading a containing folder will mark as an access to the course material. If a course material has at least 1 access it is considered viewed by that user.

2021-08-09 21:02 UTC, HenrikLam commented
Got the following frog robot error when I tried to insert a link to _https://www.google.com_ with the name _link to google_
> Oh no! Something irrecoverable has happened...
> 
> app\exceptions\OutputException (Code: 0) thrown in /usr/local/submitty/site/app/libraries/Output.php (Line 362) by:
>             throw new OutputException("{$e->getMessage()} in {$e->getFile()}:{$e->getLine()}");
> 
> 
> Message:
> Key "/var/local/submitty/courses/f21/sample/uploads/course_materials/" for array with keys "/var/local/submitty/courses/f21/sample/uploads/course_materials, /var/local/submitty/courses/f21/sample/uploads/course_materials/link-link+to+google" does not exist. in /usr/local/submitty/site/app/templates/course/CourseMaterials.twig:164
> 
> Stack Trace:
> #0 /usr/local/submitty/site/app/views/course/CourseMaterialsView.php(137): app\libraries\Output->renderTwigTemplate()
> #1 unknown file(unknown line): app\views\course\CourseMaterialsView->listCourseMaterials()
> #2 /usr/local/submitty/site/app/libraries/Output.php(224): call_user_func_array()
> #3 /usr/local/submitty/site/app/libraries/Output.php(193): app\libraries\Output->renderTemplate()
> #4 /usr/local/submitty/site/app/libraries/response/WebResponse.php(43): app\libraries\Output->renderOutput()
> #5 /usr/local/submitty/site/public/index.php(140): app\libraries\response\WebResponse->render()

2021-08-11 17:51 UTC, HenrikLam approved these changes
Looks good. Might be good to make the badge refresh on click rather than on next visit but could be done in another PR.

2021-08-11 17:51 UTC, HenrikLam commented on site/app/views/course/CourseMaterialsView.php
> +            //$seen[$course_material->getPath()] = $course_material->userHasViewed($this->core->getUser()->getId());
Can this be removed?

2021-08-11 18:01 UTC, HenrikLam reviewed
Looks good when I turned debug mode off, but I'm still getting the frog robot when debug mode is on. Might be an error on my end so I will do a vagrant destroy and up and test it again soon. Might be good to make the badge refresh on click rather than on next visit but could be done in another PR.

2021-08-12 00:27 UTC, HenrikLam commented
Everything seems to work after I did a vagrant destroy and up, I probably broke something on my end before.

2021-08-13 18:49 UTC, cjreed121 commented
This has a failing course materials test. The fix for this is in #6907 and this PR should not be merged until that is merged.

2021-08-17 04:03 UTC, bmcutler requested changes

2021-08-17 04:03 UTC, bmcutler commented on migration/migrator/data/course_tables.sql
> --- Name: course_materials_sections fk_section_id; Type: FK CONSTRAINT; Schema: public; Owner: -
wait, why are we deleting/replacing a a constraint for course_materials_sections?

2021-08-17 04:03 UTC, bmcutler commented on migration/migrator/data/course_tables.sql
> -ALTER TABLE ONLY public.course_materials_sections
same as above

2021-08-23 04:32 UTC, bmcutler commented
@cjreed121 
Hi Chris, can you please resolve the merge conflicts?

2021-08-28 14:18 UTC, bmcutler approved these changes

2021-08-28 14:18 UTC, merged