[Bugfix:TAGrading] Team Gradeable Revisions
Submitty/Submitty pull request #6864
Opened 2021-08-02 14:31 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
If you are a peer or limited access grader when grading a team gradeable, the bullet list says you can manage teams. Full access graders cannot manage teams.
Closes #6858 

### What is the new behavior?
Full access graders can now manage teams. Only if you are an instructor or full access graders can you see the bullet option to manage teams. Team names with a single quote were able to break the edit button from working which is now fixed as well.

2021-08-02 15:54 UTC, sbelsk approved these changes

2021-08-03 12:56 UTC, MasterOdin requested changes

2021-08-03 12:56 UTC, MasterOdin commented on site/app/controllers/grading/ElectronicGraderController.php
> +        $new_team_name = false;
Move this within the `else` branch where it's used.

2021-08-03 12:56 UTC, MasterOdin commented on site/app/controllers/grading/ElectronicGraderController.php
> +                $new_team_name = true;
Remove as unused.

2021-08-04 02:52 UTC, merged