[Refactor:TAGrading] Reorder Grading Pages
Submitty/Submitty pull request #6893
Opened 2021-08-04 13:58 UTC by cjreed121

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Right now when you click grade on an assignment, you are first directed to the status page which then you can go to the student index.

### What is the new behavior?
Clicking the grade button takes you right to the student index page. There is a grading stats button which can take you to that page. There is a new pop up on the student index for the responsibilities of graders. This message normally shows on the status page but that is being skipped so it will show here. It only shows the first time for each gradeable once you agree. Not agreeing will take you to course home page.

This uses localStorage to know if you have viewed the grading page before.

2021-08-05 14:31 UTC, williamjallen requested changes
The code looks good, except for one small section of inline CSS which was copied from the original page.  I do have a few concerns about the UI though.
1. When viewing a teams gradeable, the "Export Teams members" button is on a separate line from the rest of the buttons. 
![Untitled](https://user-images.githubusercontent.com/16820599/128366663-2980c9ae-b1e1-43bb-8530-c25f1f62b370.png)
2. In my opinion, the "Grading Stats" and "Responsibilities as a Grader" buttons should be secondary buttons, not primary buttons.
3. Perhaps we can discuss the exact arrangement of buttons later/make a future PR but to me, the page seems somewhat cluttered with buttons, particularly on the Instructor UI, and I wonder if it could be cleaned up somewhat.

2021-08-09 12:31 UTC, cjreed121 commented on site/app/templates/grading/electronic/GradeableMessage.twig
> +            <li style="margin-left:30px;margin-bottom:10px;">You may not use or share any of these materials or ideas without explicit permission from the author.</li>
Wouldn't that just then apply those styles to the whole <ul> tag and not the actual <li> tags? This is what I had copied from the previous page so this is what exists already. I could throw the CSS in details.css instead if you think that's a better option.

2021-08-09 13:06 UTC, williamjallen approved these changes

2021-08-10 03:25 UTC, bmcutler commented
@DefinitiveAbove please review this...
Related to open PR #6689, aren't we getting rid of the 'view=all'?

2021-08-11 05:55 UTC, DefinitiveAbove requested changes
Looks good to me for the most part; there's still a bit of inline CSS for one of the cancel buttons on the popup.

I'm not sure if it should be changed in this PR, but the "Export Teams Members" button is still on a separate line from the rest of the buttons as noted earlier.

> Related to open PR #6689, aren't we getting rid of the 'view=all'?

Yes; I'm not sure if it'd be better to remove it here or later in PR #6689.

2021-08-12 04:39 UTC, bmcutler commented
The new page sequence is much improved!

2021-08-12 04:40 UTC, merged