[Feature:Autograding] Show addition docker info in UI
Submitty/Submitty pull request #6965
Opened 2021-08-20 20:05 UTC by HenrikLam

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Currently (after #6961 and #6962) is merged, docker version and docker image statistics are not shown on the UI page.

### What is the new behavior?
The information is added, the docker version is also shown in a per machine basis. The image information is also added to the logs.

### Other information?

You can add new machine and capabilities into `autograding_workers.json` and use the UI to add a new image to the capability afterwards to see that all of the images information are displayed properly. Alternatively, you can also do a vagrant up from PR #6819 to create a worker VM on your machine which will allow for a full test of the UI and its functionality.

2021-08-23 22:50 UTC, shailpatels requested changes

2021-08-23 22:50 UTC, shailpatels commented on sbin/shipper_utils/get_docker_info.py
> +        return False
I think the exception should be logged somewhere if one is thrown

2021-08-23 22:50 UTC, shailpatels commented on sbin/shipper_utils/get_docker_info.py
> +    if (not printDockerInfo()):
Is the exit status being used anywhere? If not I think it would just be safe to call the function alone

2021-08-23 22:50 UTC, shailpatels commented on sbin/shipper_utils/update_and_install_workers.py
> +        docker_info = client.info()
`client.info()` can throw a `docker.errors.APIError` exception, this is rare but could happen if the docker service isn't running correctly and should probably be handled

2021-08-28 13:22 UTC, bmcutler commented
@HenrikLam 
Please resolve merge conflicts

2021-08-29 16:27 UTC, HenrikLam commented
@bmcutler the conflicts should be resolved now.

2021-09-01 22:23 UTC, shailpatels approved these changes
Changes looks good and works well with new submitty job to get docker information

2021-09-04 17:18 UTC, merged