[Refactor:Plagiarism] Move plagiarism to database
Submitty/Submitty pull request #6966
Opened 2021-08-22 15:28 UTC by williamjallen

### What is the current behavior?
Submitty's plagiarism detection system currently only operates on files.  Configuration data is stored in `config.json` files which are then passed to Lichen for processing.  Loading, storing, and managing `config.json` files is somewhat tricky and is a weakness in Plagiarism due to the amount of error checking required.  In addition, it is difficult to implement several upcoming features such as configuration templates and nightly reruns with the current system without having to either introduce new global Lichen files or iterate over all of the `config.json` files.

### What is the new behavior?
This PR moves all configuration info to the database.  When a Lichen run is started, the configuration information is pulled from the database and written to a `config.json` file which is then passed to Lichen.  Moving the configuration information to the database means that it will be much simpler to implement the nightly rerun feature, and the future configuration template feature, as well as slightly speeding up the time it takes to load the plagiarism main page and the plagiarism configuration form.

### Other information?
This is a breaking change which depends upon https://github.com/Submitty/Lichen/pull/61 to work properly.

2021-08-28 14:42 UTC, bmcutler commented
@williamjallen Please resolve conflicts

2021-08-31 16:57 UTC, williamjallen commented
> @williamjallen Please resolve conflicts

I believe that I have fixed the merge conflicts by performing another SQL dump.  I've looked through all of the changes in some detail but I'm not familiar enough with migrations (or SQL) to know if I have accidentally messed something up so it should be reviewed closely.

2021-09-01 16:59 UTC, cjreed121 approved these changes
PR looks good. Dumps look fine. I think some foreign key must have been missed in a prior PR with a dump which this captures now. You didn't need to dump the master submitty DB but that's fine.

2021-09-05 17:39 UTC, MasterOdin requested changes
I missed that #6975 depended on this PR, so please make the requested changes in that PR here please.

2021-09-15 20:57 UTC, sbelsk approved these changes
Works as described

2021-09-15 23:00 UTC, MasterOdin requested changes

2021-09-15 23:00 UTC, MasterOdin commented on sbin/submitty_daemon_jobs/submitty_jobs/jobs.py
> +        if '..' in semester or '..' in course or '..' in gradeable:
This does not have the same cast to `int` on `config_id` as the `RunLichen` job does.

2021-09-15 23:00 UTC, MasterOdin commented on site/app/controllers/admin/PlagiarismController.php
> +            $config_id = intval($config_id);
`intval` will never throw an exception. Worst case scenario, it converts the value to `0` for non integer values. I'm guessing you'd want to replace the catch with a `if (!$config_id)`.

2021-09-15 23:00 UTC, MasterOdin commented on site/app/controllers/admin/PlagiarismController.php
> +            catch (Exception $e) {
What exceptions are getting throw here? Are these things that'll normally happen, or is it that any exception that gets thrown is because of a bug?

2021-09-15 23:00 UTC, MasterOdin commented on site/app/controllers/admin/PlagiarismController.php
> +        // We don't want to catch any errors here becasue if something goes wrong, we want to know about it as developers/sysadmins
I'd remove this comment as we don't have this comment anywhere else we use `$em->flush()`.

2021-09-15 23:00 UTC, MasterOdin commented on site/app/controllers/admin/PlagiarismController.php
>          catch (Exception $e) {
what's the exception that'll get thrown?

2021-09-23 19:39 UTC, merged