[Bugfix:TAGrading] Grade Inquiry mode change "associated with specific component"
Submitty/Submitty pull request #7174
Opened 2021-10-03 00:07 UTC by joekrystowski

### What is the current behavior?
Currently, if a gradeable is changed to not allow by component grade inquiries after students have already submitted by component inquiries, the inquiries will not be displayed under the Stats page and the grader will be unable to resolve the inquiries.

### What is the new behavior?
When changing a gradeable from allowing component inquiries to not allowing by component inquiries, the instructor will be prompted with a warning. Should they chose to continue, one of the by component inquiries for each student who currently has one will be turned into a general inquiry, allowing the graders to see and respond to the inquiries as one general inquiry after the change. 

### Other information?
Note: The reverse (going from no component to by component) still does not work.

2021-10-04 14:27 UTC, cjreed121 requested changes

2021-10-04 15:56 UTC, joekrystowski commented on site/public/js/admin-gradeable-updates.js
> +                console.error('Failed to parse response from server: ', response);
If you try to concatenate and object to a string in javascript it will just turn into [object Object] which doesn't give any info about the object.

2021-10-04 16:10 UTC, joekrystowski commented
Also, one small thing I've just noticed, I need to actually add a check in to see if there are, in fact, already grade inquiries before I send the warning message.

2022-05-14 02:24 UTC, bmcutler commented
@cjreed121 
Please rereview this PR

2022-05-16 16:44 UTC, cjreed121 commented on site/app/templates/admin/admin_gradeable/AdminGradeableCreate.twig
> +        });
There is a bug with this. If you click cancel then refresh it still changes the radio button to no.

2022-05-20 00:16 UTC, cjreed121 approved these changes

2022-05-20 04:25 UTC, merged