[Bugfix:InstructorUI] Fix sorting of student activity
Submitty/Submitty pull request #7259
Opened 2021-10-18 00:08 UTC by joekrystowski

### What is the current behavior?
Currently, empty/NULL values on the student activity dashboard are treated as the highest values when sorting. So, for example, a student with no polls answered will be ranked above someone with 10 polls answered, even though they should be below those with 1 poll answered.

### What is the new behavior?
Now, empty/NULL values are treated as the lowest values when sorting. Fixes #7206

2021-11-19 02:17 UTC, loadedskiffer approved these changes
all columns are sorted correctly

2021-11-22 21:29 UTC, MasterOdin commented
Sorry for the merge conflict here @joekrystowski! Are you able to resolve? The files you edited were moved to `site/ts` and `site/tests/ts`, and you'll need to re-apply the changes onto them.

2021-12-13 15:56 UTC, williamjallen requested changes

2021-12-13 15:56 UTC, williamjallen commented on site/public/mjs/activity-dashboard.js
> +    else if (x == '' && y != '') {
It would be better to use the strict (`===` and `!==`) operators here instead of `==` and `!=`

2022-05-14 02:27 UTC, bmcutler commented
@williamjallen 
Can you rereview & take over making the necessary changes to get this PR merged?

2022-05-17 04:36 UTC, merged