[Feature:RainbowGrades] Upload rainbow customization.json
Submitty/Submitty pull request #7264
Opened 2021-10-18 19:47 UTC by eddiekrystowski

### What is the current behavior?
Currently, instructors must manually upload their customization.json file through Rainbow Grades.

### What is the new behavior?
Instructors can navigate to the Grade Reports page and manually upload their customization.json.
There is also a toggle to show the currently uploaded customization.json so instructors can sanity check that it got uploaded properly.

2021-11-01 06:19 UTC, MasterOdin requested changes

2021-11-01 06:19 UTC, MasterOdin commented on site/app/controllers/admin/ReportController.php
> +        if (!@copy($upload['tmp_name'], FileUtils::joinPaths($rainbow_grades_dir, 'customization.json'))) {
Prefer to use [`move_uploaded_file`](https://www.php.net/manual/en/function.move-uploaded-file.php) for `$_FILES` uploads instead of `copy`.

2021-11-01 06:19 UTC, MasterOdin commented on site/app/templates/admin/Report.twig
> +                    <form action="http://localhost:1511/courses/f21/sample/reports/rainbow_grades_customization/upload" method="POST" enctype="multipart/form-data">
```suggestion
                    <form action="{{ customization_upload_url }}" method="POST" enctype="multipart/form-data">
```

2021-11-01 06:19 UTC, MasterOdin commented on site/app/templates/admin/Report.twig
> +                    content: '```\n' ~ json ~ '\n```\n'
Can we specify JSON language in the codeblock for slightly nicer highlighting?

```suggestion
                    content: '```json\n' ~ json ~ '\n```\n'
```

2021-11-01 06:19 UTC, MasterOdin commented on site/app/templates/admin/Report.twig
> +                            >
Usual recommended style for these sorts of blocks is:
```suggestion
                            <button
                                onclick="promptCustomizationUpload.call(this)"
                                class="btn btn-primary key_to_click"
                                tabindex="0"
                                type="button"
                            >
```

Similar to if you had a long function or if statement, where the opener/closer are on its own line separate from the arguments.

2021-11-01 06:19 UTC, MasterOdin commented on site/public/js/grade-report.js
> +/*exported promptCustomizationUpload */
Ideally this would be a new file under `site/public/mjs/` directory and loaded as a module.

2021-11-01 06:19 UTC, MasterOdin commented on site/public/js/server.js
> +    const magic = () => {
While I appreciate easter eggs, I am staunchly opposed to this level of obfuscation, and evaling JS code on the fly. It's an attack vector waiting to happen as at a glance it's impossible tell what it's doing, and easy to slip unwarranted things in.

2021-11-29 21:07 UTC, jenaybarela approved these changes
It looks good!

2021-12-02 03:47 UTC, merged

2022-07-06 04:55 UTC, CouleeApps commented
I just gotta say, it makes me really amused to see someone maintain the rainbow easter egg 3 years after I wrote it. I hope it brought some humor to all the freshmen going through data structures :)

2022-07-06 05:07 UTC, bmcutler commented
@CouleeApps 
Your easter egg is much appreciated by both the energetic new kids and the grumpy seniors :)