[Feature:HelpQueue] Students can see number of people in each queue
Submitty/Submitty pull request #7306
Opened 2021-10-31 22:01 UTC by loadedskiffer

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
closes #7305 

### What is the new behavior?
Students can now view a table that shows the queue occupancy.
<img width="769" alt="pr25_1" src="https://user-images.githubusercontent.com/66340271/139602591-730115b7-3ad8-426d-9c0c-01adcbf4dafa.PNG">
Clicking the "View Queue Occupancy" button makes the table appear.
<img width="747" alt="pr25_2" src="https://user-images.githubusercontent.com/66340271/139602592-358f8ccb-ed36-47e7-b2ba-a86d56fe9f21.PNG">

### Other information?

2021-11-09 19:58 UTC, loadedskiffer commented
@BenKelly99 can you please take a look at this when you get a chance

2021-11-17 17:12 UTC, BenKelly99 requested changes

2021-11-17 17:12 UTC, BenKelly99 commented on site/app/templates/officeHoursQueue/QueueStatus.twig
> +<a id="close_queue_occupancy" onclick="toggleQueueOccupancy()" style="display: none"><button class="btn btn-secondary">Close Table</button></a>
Feels a little weird to have the button change color when toggled from "Open" to "Close". Can we use the same color for both?

2021-11-29 21:15 UTC, BenKelly99 approved these changes

2021-12-16 16:55 UTC, williamjallen requested changes

2021-12-16 16:55 UTC, williamjallen commented on site/app/models/OfficeHoursQueueModel.php
> +    public function getQueueOccupancy() {
This function should have a type hint added for the return type

2022-01-29 16:03 UTC, merged