[Refactor:InstructorUI] Refactor peer matrix UI
Submitty/Submitty pull request #7490
Opened 2021-12-27 02:54 UTC by williamjallen

### What is the current behavior?
https://github.com/Submitty/Submitty/issues/7039 describes an issue with the margins on the primary columns of the peer matrix interface in the instructor UI.  While working on the issue described, a handful of other minor UI issues were observed.

Before:
![](https://user-images.githubusercontent.com/49821332/132424025-b1d79151-c804-48b5-b52d-eed69861e15f.png)

### What is the new behavior?
This PR refactors the peer matrix UI to include a radio button option for choosing between "all grade all" and manually specifying number of others to grade, as well as removing excess styling code and removing excess margins.

After:
<img width="831" alt="after" src="https://user-images.githubusercontent.com/16820599/147429593-f52b059c-651f-4fc0-b9e6-b9f64aafa8e4.png">

### Other information?
Closes https://github.com/Submitty/Submitty/issues/7039

2022-01-30 03:49 UTC, williamjallen commented
@HenrikLam I have updated the layout of the checkboxes and radio buttons.  I'm still not entirely happy with the layout but I think it's an improvement at least.  I also tinkered with making the table the full width of the content pane but in my opinion, it looks rather ugly and cramped since it isn't aligned with the rest of the content on the page.  It does waste some space how it currently is, but since the primary element of the table is a list of user IDs which wrap, it isn't too big of an issue (in my opinion).  I have attached a screenshot of the full-width table.

Thoughts?

<img width="1161" alt="Untitled" src="https://user-images.githubusercontent.com/16820599/151685910-08d5bf43-e0db-441d-8ef8-59cf26faeb3a.png">

2022-02-01 17:03 UTC, HenrikLam requested changes
I am happy with how the UI looks after the changes, I do have one minor nitpick on the number input field being able to go below 0 though. This is probably not a big problem since instructors won't purposefully put in a negative number. Also is it intended that you can put 0 in that field? It seems to only clear the matrix which doesn't seem very useful...

2022-02-14 21:06 UTC, HenrikLam commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +            if ($(this).val() !== "") curr_student_ids.push($(this).val());
Is this convention allowed in JS files? Although this is not checked in twig files, perhaps we should follow the same convention throughout our files.

2022-02-14 21:06 UTC, HenrikLam commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +            if ($(this).val() !== "") add_student_ids.add($(this).val());
Same as above.

2022-02-14 22:36 UTC, HenrikLam commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +            if ($(this).val() !== "") add_student_ids.add($(this).val());
Sorry, one more here...

2022-02-14 22:39 UTC, HenrikLam approved these changes
Looks good to me.

2022-02-24 02:24 UTC, MasterOdin requested changes

2022-02-24 02:24 UTC, MasterOdin commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +                <div class="">
Let's get rid of the `class=""`

2022-02-24 02:24 UTC, MasterOdin commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +        let form = $("#admin-gradeable-edit-peers-form");
Use `const` if not redefining the variable. This is true of most of the usages of `let` in this diff.

2022-02-24 02:24 UTC, MasterOdin commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +    <h2> Options for Peer Matrix </h2>
Having the additional spaces surrounding the text in the header strikes me as...weird.
```suggestion
    <h2>Options for Peer Matrix</h2>
```

2022-02-24 02:29 UTC, MasterOdin commented on site/app/templates/admin/admin_gradeable/AdminGradeablePeers.twig
> +    <br>
Not asking for a change on this as it's not a huge thing, but if we wanted to strictly follow best accessibility / web practices, we should only use the `<br>` tag for line breaks in text where the break is significant (e.g. if writing a poem or an address). We should __not__ be using them to put margins between elements, rather relying on CSS `margin` to do this. Similar, for `<input>` tags we want on individual lines should be wrapped in a `<div>`. While it'd be nice to fix this, if it's a non-trivial amount of effort, fine to not deal with this.

2022-03-30 20:52 UTC, merged