[Bugfix:TAGrading] Improve grading index column order
Submitty/Submitty pull request #7743
Opened 2022-03-14 15:05 UTC by DefinitiveAbove

### What is the current behavior?
* #7732 

### What is the new behavior?
Closes #7732 
Grading index in anon mode changed to have columns in the same order as non-anon mode.

The `Grading` column in anon-mode now behaves identically to non-anon mode when a limited-access grader or above is viewing the grading index (students will only see their own grading score in peer grading).
![image](https://user-images.githubusercontent.com/15370948/158200228-2cbe1775-edc8-4a75-b81d-7cdf83d9ea90.png)

2022-03-30 21:11 UTC, williamjallen requested changes

2022-03-30 21:11 UTC, williamjallen commented on site/app/views/grading/ElectronicGraderView.php
> +            if ($this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER && $gradeable->getLimitedAccessBlind() == 2) {
```suggestion
            if ($this->core->getUser()->getGroup() === User::GROUP_LIMITED_ACCESS_GRADER && $gradeable->getLimitedAccessBlind() === 2) {
```

2022-03-30 21:11 UTC, williamjallen commented on site/app/views/grading/ElectronicGraderView.php
> +            if ($this->core->getUser()->getGroup() == User::GROUP_LIMITED_ACCESS_GRADER && $gradeable->getLimitedAccessBlind() == 2) {
Is it possible to replace `2` with a constant here?

2022-04-07 00:08 UTC, shailpatels commented on site/app/templates/grading/electronic/Details.twig
> +            {% elseif graded_gradeable.isTaGradingComplete() and core.getUser().getGroup() < 4 and graded_gradeable.isPeerGradingComplete() %}
Could use the function `accessGrading` to make it more explicit what that check is doing

```suggestion
            {% elseif graded_gradeable.isTaGradingComplete() and core.getUser().accessGrading() and graded_gradeable.isPeerGradingComplete() %}
```

2022-05-10 15:18 UTC, bmcutler commented
@williamjallen @shailpatels 
Please re-review

2022-05-11 20:45 UTC, williamjallen approved these changes
Changes look good and appear to work correctly.  My only comment is that one column is labeled "Grading" in anonymous mode and "TA Grading" otherwise.

2022-05-13 13:10 UTC, williamjallen approved these changes

2022-05-13 13:21 UTC, merged