[Feature:Plagiarism] Add color customization
Submitty/Submitty pull request #7889
Opened 2022-05-14 16:25 UTC by williamjallen

### What is the current behavior?
The current color scheme for the plagiarism interface has poor contrast and is somewhat distracting when trying to compare two submissions.

Current interface:
<img width="1171" alt="before" src="https://user-images.githubusercontent.com/16820599/168440112-f94ec94d-f944-4ed5-b4dc-b9b5713259c9.png">

### What is the new behavior?
The default colors have been adjusted to improve the contrast.  Additionally, the ability to customize the colors has been added.  Colors are chosen using a standard HTML5 color picker, and are saved in local storage for use across multiple sessions and configurations.

New interface with default colors:
<img width="1170" alt="after" src="https://user-images.githubusercontent.com/16820599/168440318-cf4c36f5-b254-4f07-988a-72618f438235.png">

Highlighting key with customizable colors:
<img width="767" alt="plag_highlighting_key" src="https://user-images.githubusercontent.com/16820599/168440352-11236ddb-5624-4c26-b292-0f562c78fd96.png">

2022-05-17 02:07 UTC, shailpatels requested changes
I think you want to use the `input` event instead of onchange for color pickers, for color pickers onchange is inconsistent, especially on mac which opens up the native color picker and does not close it after a selection. Also if a user sets a color and then immediately closes the model the color might not get saved or set correctly.

2022-05-17 19:32 UTC, Eceptonsu requested changes
The "reset color" button updated the colors for the first time after I changed the colors, but when I did it for the second time, the update is not instant, a refresh is needed at this point.

2022-05-18 14:53 UTC, williamjallen commented
Good catch.  Changes have been made.

2022-05-18 19:05 UTC, Eceptonsu approved these changes

2022-05-19 14:35 UTC, merged