PyPDF2 version update
Submitty/Submitty pull request #7938
Opened 2022-05-25 11:28 UTC by akshatbatra

### What is the current behavior?
Related to #7289, some PDF files are not accepted by PyPDF2.

### What is the new behavior?
Active maintenance of PyPDF2 has resulted in it being more dependable while working with corrupt PDFs.
PyPDF2 is now able to work with files such as [broken.pdf](https://github.com/Submitty/Submitty/files/7422603/broken.pdf) with `strict=False` set, it can now deal with xref table not being present at the specified location.
Required version of PyPDF2 has been updated to 1.28.2 and its deprecated usage has been replaced with latest recommendations.

2022-05-25 14:59 UTC, cjreed121 commented
This is a duplicate of https://github.com/Submitty/Submitty/pull/7926. One of these should be closed.

2022-05-25 15:20 UTC, bmcutler commented
Yes please, make a PR to the other repo :)

2022-05-30 00:30 UTC, Eceptonsu approved these changes
It works well for me even though it is a bit slow.

2022-06-01 03:09 UTC, shailpatels approved these changes
Thanks for the fix and good to hear that pypdf2 is under active maintenance again!

Tested with regular and bulk upload and both appeared to work as expected

2022-06-01 14:38 UTC, MasterOdin requested changes

2022-06-01 14:38 UTC, MasterOdin commented on sbin/submitty_daemon_jobs/submitty_jobs/bulk_qr_split.py
>          pdf_writer = PdfFileWriter()
We'll need to update the class names while we're at it as the `PdfFile*` version has been deprecated in favor of the shorter names.

```suggestion
        pdfPages = PdfReader(filename, strict=False)
        pdf_writer = PdfWriter()
```

2022-06-01 15:20 UTC, MasterOdin approved these changes

2022-06-01 15:24 UTC, MasterOdin commented
Before merging this, we need to improve how we manage python dependencies so that they get updated as part of running `INSTALL_SUBMITTY_HELPER.sh` instead of on `install_system.sh`, as otherwise all code that relies on the new version of PyPDF2 will break until manually run `pip install -U PyPDF2` (with appropriate chmod).

2022-06-04 03:04 UTC, merged