[Bugfix:CourseMaterials] All course materials get deleted
Submitty/Submitty pull request #8094
Opened 2022-06-26 13:37 UTC by akshatbatra

### What is the current behavior?
Creating a folder with a particular name and then deleting it causes all course materials to get deleted.
Steps to reproduce:
1.) Add new course material by clicking on "Upload Course Materials" and typing in `%2e` (encoded form of `.`) or `%2e%2e` as the subdirectory name, select a file and click submit.
2.) Make sure that there are some files/folders other than this folder in order to verify the behavior.
2.) Delete the newly created folder named `%2e` or `%2e%2e`.
3.) See that all the course materials get removed.

### What is the new behavior?
A check has been added to prevent the deletion of the course materials folder.

2022-06-29 17:04 UTC, tkoz0 reviewed
When a directory is created with the name `%2e`, it seems that there is no way to delete it. Deletion of the `course_materials` directory is prevented, but so is deletion of a directory named `%2e`.

2022-06-29 18:05 UTC, tkoz0 reviewed
Upon further investigation, other issues can happen due to decoding substrings such as `%2e` or `%2f`. For example,
1. Upload a file to a directory named `1%2f2` (decoded to `1/2`).
2. Upload a file to directory `1/2`.
3. Delete directory `1%2f2`
4. Observe that `1/2` is deleted but `1%2f2` remains.

2022-07-05 20:43 UTC, akshatbatra commented
It has been identified that this issue is there for zip files such as [file.zip](https://github.com/Submitty/Submitty/files/9049579/file.zip), so, a check has been added to take care of that.
.

2022-07-06 03:27 UTC, cjreed121 requested changes

2022-07-06 03:27 UTC, cjreed121 commented on site/app/controllers/course/CourseMaterialsController.php
> +        if ($path === $this->core->getConfig()->getCoursePath() . "/uploads/course_materials") {
Rather than concatenating strings can you use FileUtils::joinPaths

2022-07-11 19:31 UTC, cjreed121 approved these changes

2022-07-11 21:04 UTC, tkoz0 approved these changes
Works as expected now.

2022-07-11 23:37 UTC, merged