[Bugfix:Autograding] Mermaid Sequence Diagram Fix
Submitty/Submitty pull request #8103
Opened 2022-06-28 16:07 UTC by Eceptonsu

### What is the current behavior?
The mermaid sequence diagrams for network gradeables have messages overlapping with each other most likely due to broken y values for the elements in the SVG.

### What is the new behavior?
The messages in the mermaid sequence diagrams now have line breaks and other elements have correct y values.
![image](https://user-images.githubusercontent.com/79226246/176240334-3b059e8b-68ad-4e39-8eae-9ac7700e4c19.png)

### Other information?
This is a temporary fix by adding delays.

2022-06-29 00:53 UTC, williamjallen requested changes
I noted a couple minor things.  Otherwise, things look good.  How difficult would it be to use a callback as noted in the comment instead of this (quite hacky) approach?  I'm not familiar with this part of the codebase, but it seems like it would likely be a rather simple change.

It's possible that all you need to do is put the `mermaid.init()` call inside a `$( document ).ready()` function so it doesn't get run until the page finishes loading.

2022-06-29 00:53 UTC, williamjallen commented on grading/python/submitty_router.py
> +        outfile.write(f'{start}: {"<br/>".join(str_lines)}\n')
This change shouldn't be necessary since `<br>` tags don't need to be closed.

2022-06-29 00:53 UTC, williamjallen commented on site/app/templates/autograding/AutoChecks.twig
> +                // TODO: This is a TEMPERARY fix, use callback
```suggestion
                // TODO: This is a TEMPORARY fix, use callback
```

2022-06-29 00:54 UTC, williamjallen commented on grading/python/submitty_router.py
> +        outfile.write(f'{start}: {"<br/>".join(str_lines)}\n')
Oops, forgot the suggestion (and apparently can't edit in afterwards)
```suggestion
        outfile.write(f'{start}: {"<br>".join(str_lines)}\n')
```

2022-06-29 07:58 UTC, Eceptonsu commented
> I noted a couple minor things. Otherwise, things look good. How difficult would it be to use a callback as noted in the comment instead of this (quite hacky) approach? I'm not familiar with this part of the codebase, but it seems like it would likely be a rather simple change.
> 
> It's possible that all you need to do is put the `mermaid.init()` call inside a `$( document ).ready()` function so it doesn't get run until the page finishes loading.

Thanks for reminding me of this approach, it worked perfectly fine.

2022-06-30 01:35 UTC, williamjallen approved these changes

2022-06-30 05:31 UTC, merged