[Testing:Developer] Add new eslint rules
Submitty/Submitty pull request #8132
Opened 2022-07-03 17:44 UTC by williamjallen

### Please check if the PR fulfills these requirements:

* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
The Javascript `==` and `!=` operators are generally not recommended because they can behave in [unexpected ways](https://dorey.github.io/JavaScript-Equality-Table/).  Our `eslint` configuration does not currently specify which operators are preferred.

While exploring our `eslint` configuration, I also noticed that the `space-before-blocks` rule is not enabled.

I have observed inconsistencies in code style relating to each of these rules while reviewing code recently.

### What is the new behavior?
This PR adds the [`eqeqeq`](https://eslint.org/docs/latest/rules/eqeqeq) and [`space-before-blocks`](https://eslint.org/docs/latest/rules/space-before-blocks) rules to our `eslint` configuration.

A documentation PR to update [this page](https://submitty.org/developer/software_and_system_design/coding_style_guide/javascript) will be forthcoming.

2022-07-03 18:05 UTC, MasterOdin commented
Could we split this into two PRs, one for `eqeqeq` and one for `space-before-blocks`? I think the latter can be merged pretty instantly as it's just style changes, but the former I think we can do some amount of code changes / longer PR review where we currently just ignore the rule.

2022-07-03 19:57 UTC, williamjallen commented
Alright, will do.  Do you have suggestions for other good rules that should be added?  I looked through the list and didn't see anything that stood out, but I'm not familiar with what rules are considered to be common practice/useful.

2022-07-03 20:54 UTC, MasterOdin commented
Looking at #8133, I would recommend adding [`@typescript-eslint/type-annotation-spacing`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/type-annotation-spacing.md). As we grow the usage of modules, I would also recommend adding the `import/order` rule from [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) with following definition:

```js
    'import/order': [
      'error',
      {
        alphabetize: { caseInsensitive: true, order: 'asc' },
        groups: [
          ['builtin', 'external'],
          'parent',
          'sibling',
          'index',
          'object',
        ],
        'newlines-between': 'always',
      },
    ],
```

Otherwise, not sure there's anything in particular that jumps out at me, but some amount of this is just growing the style guide stuff organically as we see people differing on style, and going "can we mandate particular style here?"

2022-07-04 01:12 UTC, MasterOdin requested changes

2022-07-04 01:12 UTC, MasterOdin commented on site/public/js/admin-team-form.js
>          if (found || $(this).val() == '') {
We could replace this with `===` only if we're confident that we're not relying on entering this if statement when `$(this).val()` is `0` or `[]` as those are both `== ''`

2022-07-04 01:12 UTC, MasterOdin commented on site/public/js/autograding-status.js
>                          if (info.interactive != 0) {
Similar to above, we can replace these only if confident that it cannot be `''` or `[]`, so probably safe to just leave these as disabled for now.

2022-07-04 01:13 UTC, MasterOdin commented
Another rule would be [`prefer-arrow-callback`](https://eslint.org/docs/latest/rules/prefer-arrow-callback) as the standard in most code bases in my experience these days are in using arrow functions.

2022-07-04 02:38 UTC, williamjallen commented
`prefer-arrow-callback` is [listed](https://github.com/Submitty/Submitty/blob/a350062895539e5c52e5e2ea3529d7a7f80ff704/site/.eslintrc.json#L31) in our `.eslintrc.json` file but unless I'm misunderstanding the usage of this rule, it doesn't seem to be enforced.  Example: https://github.com/Submitty/Submitty/blob/a350062895539e5c52e5e2ea3529d7a7f80ff704/site/public/js/directory.js#L11

I'll poke around in the `eslint` config some more tomorrow to figure out what's wrong.  I'll also look over the changes in this PR to resolve anything which can be done safely such as the ones requested in an earlier comment.

2022-07-04 02:41 UTC, MasterOdin commented
Ah, it's because of the usage of `this` within the anonymous function. I missed that. Solution there would be to work to drop jQuery as a dependency I suppose.

2022-07-22 14:19 UTC, tkoz0 commented
Why is it that you are leaving quite a few `==` and `!=` as ignored? Is it because of the need to test the changes?

2022-07-22 14:29 UTC, MasterOdin requested changes

2022-07-22 14:29 UTC, MasterOdin commented on site/public/js/confetti.js
>          if (e.code === 'Enter' && canvas.style.display != 'none') {
```suggestion
        if (e.code === 'Enter' && canvas.style.display !== 'none') {
```

2022-07-22 14:29 UTC, MasterOdin commented on site/public/js/system-update.js
>          if ($(toggleAllButton).hasClass('collapsed') != $(button).hasClass('collapsed')) {
```suggestion
        if ($(toggleAllButton).hasClass('collapsed') !== $(button).hasClass('collapsed')) {
```

[`$.hasClass`](https://api.jquery.com/hasclass/) only returns a boolean.

2022-07-22 14:29 UTC, MasterOdin commented on site/ts/activity-dashboard.js
>      if (i == 0 || i == 8) {
```suggestion
    if (i == 0 || i === 8) {
```

2022-07-22 14:29 UTC, MasterOdin commented on site/ts/activity-dashboard.js
>      else if ((i <= 7 && i >= 4) || i == 9) {
```suggestion
    else if ((i <= 7 && i >= 4) || i === 9) {
```

2022-07-22 14:29 UTC, MasterOdin commented on site/ts/activity-dashboard.js
>          if (i != n && $(`#${i}`).children('i').hasClass('fa-angle-up')) {
All usages of this function pass `n` as a number.

```suggestion
        if (i !== n && $(`#${i}`).children('i').hasClass('fa-angle-up')) {
```

2022-07-22 14:29 UTC, MasterOdin commented on site/ts/activity-dashboard.js
>          else if (i != n && $(`#${i}`).children('i').hasClass('fa-angle-down')) {
Same here

```suggestion
        // eslint-disable-next-line eqeqeq
        else if (i !== n && $(`#${i}`).children('i').hasClass('fa-angle-down')) {
```

2022-07-22 20:02 UTC, MBon1 commented on site/public/js/user-profile.js
>                      if (response.data.utc_offset != offset) {
I was able to get the same result when changing the time zone in the user profile after replacing `response.data.utc_offset != offset` with `response.data.utc_offset !== offset`.

2022-07-22 20:31 UTC, MBon1 commented on site/public/js/docker_interface.js
>              if ($(this).text() == this_filter) {
In the jQuery documentations, `.data` can return any type.  However, in my testing, it looks like in this function (`filterOnClick`), `.data` is only returning a `string`, the selected filter's name.

2022-07-26 18:03 UTC, MBon1 commented on site/public/js/forum.js
>              if (file_array[part-1][j].name == filename) {
I was able to get the same result when uploading an attachment to a forum post after replacing `file_array[part-1][j].name == filename` with `file_array[part-1][j].name === filename`.  When getting the type of `file_array[part-1][j].name` and `filename`, `string` is returned for both.

2022-07-26 18:19 UTC, MBon1 commented on site/public/js/forum.js
>      if (load_page == 0) {
The same behavior was produced when scrolling through the discussion forum posts after replacing `load_page == 0` with `load_page === 0`.  When getting the type of `load_page`, `number` is returned.

2022-07-26 18:24 UTC, MBon1 requested changes
Including my previous comments, there were a couple of places that I found using `===` instead of `==` could work.  The files include `forum.js`, `docker_interface.js`, and `user-profile.js`.

2022-07-26 18:24 UTC, MBon1 commented on site/public/js/forum.js
>              if (count == 0) {
The same behavior was produced when scrolling through the discussion forum posts after replacing `count == 0` with `count === 0`.  When getting the type of `count`, `number` is returned.

2022-07-26 18:24 UTC, MBon1 commented on site/public/js/forum.js
>              if (count == 0) {
While I was unable to trigger this `else` condition, the same behavior would likely occur if `count == 0` is replaced with `count === 0` as the code here is almost identical to the preceding condition.

2022-07-28 17:27 UTC, williamjallen commented
> Why is it that you are leaving quite a few `==` and `!=` as ignored? Is it because of the need to test the changes?

Yes.  This PR actually turned out to not be as bad as I expected, but many linting PRs are difficult to test so we usually ignore any pre-existing errors which can't be corrected easily.  In some cases such as the previous requested changes, we can be certain that the change won't break anything.  In other cases, it is sometimes difficult to determine what type a variable might be so we simply ignore the changes.

2022-07-29 02:11 UTC, MasterOdin approved these changes
Yeah, I suspect we could resolve each of these by going through one by one, but in the sake of progress, and not letting more of these errors enter the codebase, I would say merge this now, and the remaining ignored errors can be slowly cleaned up as people touch the containing code, or some entrepreneurial soul wishes to clean it up separately.

2022-08-01 19:12 UTC, MBon1 approved these changes

2022-08-01 21:52 UTC, merged