[Feature:TAGrading] Fixed Columns for easy grading
Submitty/Submitty pull request #8173
Opened 2022-07-14 09:38 UTC by immortalcodes

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Adds the feature as requested in #7437 
Student column moves with the grid during grading,which casuse difficulties in grading as TA/Instructor have to go back and forth between the student column and the column  to mark and  make sure that they are marking the same row.

### What is the new behavior?
Now the student and other info columns remain fixed in the place which makes the grading easier.
![image](https://user-images.githubusercontent.com/92226302/178952623-f9db5b34-1762-43a3-8d4d-8cd8e1122a18.png)

### Other information?

2022-07-14 12:34 UTC, williamjallen submitted a review, later dismissed

2022-07-14 12:34 UTC, williamjallen commented on site/public/css/simple-grading.css
> +    background: white;
Should this be fixed to white, or should it be changed to a variable listed in `colors.css` like the ones used elsewhere in these changes?

2022-07-19 02:50 UTC, shailpatels requested changes
I tested this on windows firefox and chrome and got a strange issue where the animation and color of selecting a checkbox doesn't show anymore.

On main:
![before](https://user-images.githubusercontent.com/12129065/179653596-eb895974-67f5-4def-8637-e9c347819a1c.gif)

After installing the branc
![after](https://user-images.githubusercontent.com/12129065/179653638-0e93bdd8-af9a-40bb-98e6-0e8a28dd54d5.gif)
h

In both browsers I can connect to the websockets server and I do not see any console errors. Are you able to check off students? I tested with a new gradeable created under the sample course

2022-07-20 18:33 UTC, Eceptonsu approved these changes
Works for me.

2022-07-22 15:02 UTC, tkoz0 commented
I'm seeing unexpected behavior with several checkpoints. In this image, I have selected checkpoint 1 with the arrow keys by moving left, but it is hidden behind the student information.
![image](https://user-images.githubusercontent.com/13438573/180467475-e7f6d1c7-a3e6-4bf9-b286-7e29159ff01c.png)
I also want to ask what the keyboard controls are supposed to be because I don't think it's clear or stated anywhere.

2022-07-24 22:44 UTC, Eceptonsu commented
> I'm seeing unexpected behavior with several checkpoints. In this image, I have selected checkpoint 1 with the arrow keys by moving left, but it is hidden behind the student information. ![image](https://user-images.githubusercontent.com/13438573/180467475-e7f6d1c7-a3e6-4bf9-b286-7e29159ff01c.png) I also want to ask what the keyboard controls are supposed to be because I don't think it's clear or stated anywhere.

The keyboard works for me. But one thing I noticed is that the title of the table is not at the center with respect to the window, it is located at the center of the entire table.
![image](https://user-images.githubusercontent.com/79226246/180668480-117e97dd-2b1c-4342-a631-5905c978327d.png)
![image](https://user-images.githubusercontent.com/79226246/180668821-dc8d3a0c-4e6f-44d5-9683-f63021492eea.png)

2022-07-25 17:08 UTC, immortalcodes commented
Actually, the thing is that the fixed columns are overlapping the scrollable columns, this might not be entirely a problem since scrolling through the touchpad works well, there are possible solutions through javascript but looking for something simpler.

2022-07-31 11:05 UTC, immortalcodes commented
![image](https://user-images.githubusercontent.com/92226302/182023035-0f8a4b88-3730-4e08-9ee0-aedeefdd8ecd.png)
I tried a lot of things but I guess the fix would look  something  like this.
In this, the upper title gets fixed on the left side of the table. 
The problem is with the column span which makes the title scrollable which otherwise would remain fixed.

2022-08-16 01:29 UTC, shailpatels approved these changes
Looks good, latest changes move the registration section name to the left side and not centered which I don't think is important since it remains visible the entire time

2022-09-07 17:10 UTC, merged