[Feature:Calendar] Add Calendar Sidebar Button Out of Debug
Submitty/Submitty pull request #8179
Opened 2022-07-14 20:02 UTC by MBon1

### What is the current behavior?

 - Currently, the calendar button on the sidebar is only viewable when debugging is enabled.
### What is the new behavior?
 - Even when debugging is not enabled, the calendar button will now appear on the sidebar.
### Other information?
**How did you test**
 - Disable config/database.json, set the “debugging_enabled” field to false. I used the following command to do this: 
   - `php -r '$arr = json_decode(file_get_contents("/usr/local/submitty/config/database.json"), true); $arr["debugging_enabled"] = false; file_put_contents("/usr/local/submitty/config/database.json", json_encode($arr, JSON_PRETTY_PRINT));'`
- Log into Submitty as a student, TA, and instructor. Check if each can see the "Calendar" button in the sidebar and if selecting the button sends the user to the Calendar page.
- For each user, check if the "Calendar" button is still visible and usable after going into a course and a Gradeable.
- When testing was completed, I re-enabled debugging with the following command: 
    - `php -r '$arr = json_decode(file_get_contents("/usr/local/submitty/config/database.json"), true); $arr["debugging_enabled"] = true; file_put_contents("/usr/local/submitty/config/database.json", json_encode($arr, JSON_PRETTY_PRINT));'`

2022-07-20 08:25 UTC, Eceptonsu approved these changes

2022-07-22 14:13 UTC, tkoz0 requested changes

2022-07-22 14:13 UTC, tkoz0 commented on site/app/controllers/GlobalController.php
Looks good except you should adjust the indentation here.

2022-07-22 17:27 UTC, tkoz0 approved these changes
Looks good

2022-07-23 05:39 UTC, merged