[UI/UX:Submission]Office hour staff text color
Submitty/Submitty pull request #8394
Opened 2022-09-14 10:45 UTC by billyvande

### What is the current behavior?
Text color is different in dark mode. 

### What is the new behavior?
Since the objective is to make text color same. Now, office hour text has same color in dark mode.

2022-09-14 14:55 UTC, cjreed121 requested changes
Rather than adding hard coded CSS. We should be able to match up the classes on both. You'll see that one of the labels has classes `btn` and `filter-buttons` while the other just has `btn`. Let's keep it consistent so they both have `btn` and `filter-buttons`.

2022-09-17 12:39 UTC, billyvande commented
Thanks for corrections. This is my first time contributing to an open source. 
I update Office hours header and match the class.

2022-09-17 23:26 UTC, cjreed121 requested changes
I used WAVE to check accessibility and there was some contrast errors with this. If you can quickly make the changes I've noted it should fix them and I think this is then good to merge.

2022-09-17 23:26 UTC, cjreed121 commented on site/app/templates/officeHoursQueue/QueueHeader.twig
> +                <label tabindex="0" class="btn filter-buttons"  style="word-wrap: break-word; border-color: {{ viewer.getColorFromCode(queue['code']) }}; background: {{ viewer.getColorFromCode(queue[
Can you remove `color: inherit` here

2022-09-17 23:26 UTC, cjreed121 commented on site/app/templates/officeHoursQueue/QueueHeader.twig
> +                <label tabindex="0" class="btn filter-buttons"  style="word-wrap: break-word; border-color: {{ viewer.getColorFromCode(queue['code']) }}; background: {{ viewer.getColorFromCode(queue[
Also remove here too

2022-09-20 09:56 UTC, billyvande commented on site/app/templates/officeHoursQueue/QueueHeader.twig
> +                <label tabindex="0" class="btn filter-buttons"  style="word-wrap: break-word; border-color: {{ viewer.getColorFromCode(queue['code']) }}; background: {{ viewer.getColorFromCode(queue[
yes, sure!

2022-09-20 10:11 UTC, billyvande commented
Before : 
![image](https://user-images.githubusercontent.com/75759804/191228296-fc290c37-1dc9-4c1b-aa85-2a4a507e27db.png)
After : 
![image](https://user-images.githubusercontent.com/75759804/191228796-06e26d65-9874-4a0f-b03a-c2f4b5089ad7.png)

I wish my PR solve the issues.

2022-09-20 15:42 UTC, cjreed121 commented
Please leave the title as is so it complies with https://submitty.org/developer/getting_started/how_to_contribute

2022-09-25 03:53 UTC, merged