Display name changes
Submitty/Submitty pull request #8477
Opened 2022-10-04 17:34 UTC by shinyclovers

### What is the current behavior?
Office Hours status (for students) doesn't show who is helping the student.

### What is the new behavior?
This PR addresses #8432 and updates the Office Hours queue history accordingly
<img width="301" alt="image" src="https://user-images.githubusercontent.com/36224157/193884559-bc399c64-860f-481f-935d-ea85810b49f7.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/36224157/193885259-7fad15d3-5c6f-4da4-879a-8edeaa4c6065.png">

### Other information
I see that there is a lot of duplicate code to find the display name of a person, I wonder if there is a function that I could use in order to grab the preferred display name of a particular user?

2022-10-29 23:50 UTC, cjreed121 requested changes
It definitely seems to work well. To answer your question in the PR, you could just select the whole row when you join with users. Then create a PHP User model from that. There are functions called `getDisplayedFirstName` and `getDisplayedLastName` in the User model which would probably be useful to you. It would cut down on code reuse here and make the queries shorter.

2022-10-31 19:20 UTC, jssunray34 commented
Looks good and works well for both instructor/full-access grader and limited access grader! Agree with Chris that you can reuse existing code (the functions you want to use are in `site/app/models/User.php`) for database queries. Also, in the Twig files you can probably reduce repetitive code by creating a variable (e.g., `displayed_name`) that is set to either "Firstname Lastname" or "Firstname LastInitial." depending on what type of user the helper is.

2022-10-31 19:23 UTC, jssunray34 approved these changes

2022-11-17 18:48 UTC, williamjallen requested changes

2022-11-17 18:48 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +                END AS helper_firstname,
The `COALESCE()` command may be more efficient here.  The same comment applies to the other queries being modified.

2022-11-17 18:48 UTC, williamjallen commented on site/app/models/OfficeHoursQueueModel.php
> +        if ($group <= 2) {
What does the number 2 mean here?  It would be better to replace it with a constant which indicates its meaning.

2022-11-17 18:48 UTC, williamjallen commented on site/app/models/OfficeHoursQueueModel.php
> +    public function getDisplayName($first_name, $last_name, $group) {
Type hints should be added to these functions

2023-01-23 06:49 UTC, cjreed121 approved these changes
Looks good to me!

2023-01-27 22:13 UTC, williamjallen approved these changes
Good work on this!

2023-01-28 16:52 UTC, merged