[Feature:LecturePoll] Separate Future Polls into Tomorrow's Polls and Future Polls
Submitty/Submitty pull request #8519
Opened 2022-10-18 04:39 UTC by jssunray34

### What is the new behavior?
"Future Polls" have been separated into "Tomorrow's Polls" and "Future Polls."

Closes #8500

2022-10-19 15:22 UTC, williamjallen requested changes
Code generally looks good.  It would probably be good to add some tests to `site/cypress/e2e/polls.spec.js` for this case.

2022-11-11 22:58 UTC, williamjallen requested changes

2022-11-11 22:58 UTC, williamjallen commented on site/cypress/e2e/polls.spec.js
> +        cy.wait(1000);
Adding `cy.wait()` calls can result in flaky tests in the CI and should generally be avoided.  Is there another way to do this?

2022-11-15 01:19 UTC, jssunray34 commented
@williamjallen I removed the `wait()` call, and the test still passes. I had initially added it because a similar test does the same (for "Poll Cypress Test"). Do you have any suggestions for how to guarantee the test passes with respect to timing?

Also, something weird was happening where I was inputting what I thought would be tomorrow's date into the date field within my cypress test. However, it appears to be two days ahead (and thus the test fails), and I'm trying to figure out what is going on since it worked previously. Could you see if you're getting the same behavior when you run the test suite?

2022-11-15 01:21 UTC, jssunray34 commented
Also, one of the lint tests is failing, but I'm not sure why (the error message is not very clear to me).

2022-11-15 02:05 UTC, williamjallen commented
I believe that the failing python linting test will be resolved by updating from main.  

As for your failing e2e test, it looks like it is trying to navigate to `/courses/f22/sample/polls`, and is receiving an error page at that point.  Does the main polls page currently work for both students and instructors?

2022-11-15 02:08 UTC, williamjallen commented
I also just remembered why there was a `cy.wait()` command in there originally.  When you click the dropdown, a rather trivial AJAX request is made to update a cookie, which was timing out in the CI occasionally.  I have removed that request in my changes to #6708, so I think any potential flakiness in the tests should be resolved by that PR.

2022-11-26 23:25 UTC, jssunray34 commented
@williamjallen I looked into the failing e2e tests and am unsure where the error is coming from. I also made sure that both the student and instructor poll pages do not error out when a new poll (to be released "tomorrow") is added. The test suite does not fail locally, so it's a bit difficult to debug. Would you be able to take a look if you have a chance?

2022-11-27 20:13 UTC, williamjallen commented
I saw some similar issues with the tests while working on #6708, so for now I think it is best to wait for #6708 to be merged and then I can fix this PR to work with the new system.

2023-01-24 20:46 UTC, jssunray34 commented
What is the status of this PR?

2023-01-27 22:03 UTC, williamjallen commented
#6708 will (hopefully) be finished and merged this weekend.  Since this PR conflicts with #6708 significantly, I'll take over updating this PR to use Doctrine after that's merged.

2023-02-27 17:56 UTC, EdenBendheim commented
I saw #6708 was merged, if you would not like to review this further I would be happy to test this PR @williamjallen :).

2023-02-28 23:58 UTC, williamjallen commented
> I saw #6708 was merged, if you would not like to review this further I would be happy to test this PR @williamjallen :).

 It needs an (almost) complete rewrite to use the new Doctrine backend.  I promised that I'd do it and I haven't gotten around to it yet.  I was actually planning to work on it this week, but if you're interested you're welcome to take it on instead.

2023-04-05 04:33 UTC, closed without merging