Grade inquiries display name
Submitty/Submitty pull request #8608
Opened 2022-11-15 04:27 UTC by jssunray34

### What is the new behavior?

For grade inquiries, the display name is "Preferredfirstname Preferredlastname" for instructors and full access graders and is "Preferredfirstname Last initial" for limited access graders.

2022-11-16 00:20 UTC, williamjallen requested changes

2022-11-16 00:20 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +        return intval($this->course_db->rows()[0]['user_group']) == 3;
```suggestion
        return intval($this->course_db->row()['user_group']) === 3;
```

2022-11-16 00:20 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +        return intval($this->course_db->rows()[0]['user_group']) == 3;
It would also probably be good to replace the number 3 with a constant which indicates what it means.

2022-11-16 00:20 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +        return intval($this->course_db->rows()[0]['user_group']) <= 2;
```suggestion
        return intval($this->course_db->row()['user_group']) <= 2;
```

2022-11-16 00:20 UTC, williamjallen commented on site/app/libraries/database/DatabaseQueries.php
> +        return intval($this->course_db->rows()[0]['user_group']) <= 2;
Same comment here about using a defined constant instead of the number 2.

2022-11-16 00:20 UTC, williamjallen commented on site/app/views/submission/HomeworkView.php
> +                    $is_instructor_or_full_access_grader = $this->core->getQueries()->isInstructorOrFullAccessGraderPost($post['user_id']);
Doing this in a foreach loop is going to cause a *lot* of queries.  Separate queries are very slow, and are the main cause of slowness across Submitty, so we want to minimize the number of queries being made total.  You can click "Show Details" at the bottom of any page in the development environment to see each of the queries being made.  Any repeated queries should be eliminated if at all possible.

2023-01-23 21:25 UTC, jssunray34 commented
What is the status of this PR?

2023-02-08 02:41 UTC, williamjallen requested changes
This PR seems to be on track, but there are a handful of small issues with it still.

1. There are still several queries embedded in loops.  This will result in a large number of queries and significantly affect performance.  You can see the queries being made by clicking "Show Page Details" at the bottom of the page in the development environment.  You can also see the total number of queries generated in the yellow warning banner at the top of the page.
2. This PR needs to be updated to use the given/family name terminology instead of first/last name

2023-03-10 19:07 UTC, 04vmatsibekker commented
Yeah I agree with William maybe having so many queries in a for loop is not such a good idea. Also it seems this branch has some conflicts that you'll have to resolve. But great job!

2023-03-10 19:10 UTC, 04vmatsibekker commented on site/app/views/submission/HomeworkView.php
> +                    $first_name = $this->core->getQueries()->getUserById($post['user_id'])->getDisplayedFirstName();
Now I don't know a lot about queries, but if you look in the file Submitty\site\tests\app\libraries\AccessTester.php on line 38, you can perhaps store the information from $this->core->getQueries() in a variable $queries, and then you can use that variable to find information for the variables $is_staff, $first_name, and $last_name.

2023-03-10 19:10 UTC, 04vmatsibekker commented on site/app/views/submission/HomeworkView.php
> +                    $first_name = $this->core->getQueries()->getUserById($post['user_id'])->getDisplayedFirstName();
Yeah I agree with William maybe having so many queries in a for loop is not such a good idea. Also it seems this branch has some conflicts that you'll have to resolve. But great job!

2023-03-14 20:08 UTC, 04vmatsibekker commented on site/app/views/submission/HomeworkView.php
> +                    $first_name = $this->core->getQueries()->getUserById($post['user_id'])->getDisplayedFirstName();
Also I am getting an error when loading the site

![image](https://user-images.githubusercontent.com/117249183/225124359-532e1f92-adfc-4613-a790-0eb0c1e11ba5.png)

2023-03-15 02:28 UTC, williamjallen commented
It seems like a bad merge happened somewhere along the way here.  These changes should be reverted so that there aren't 350+ files changed.

2023-05-18 19:54 UTC, bmcutler commented
closed, will be replaced by #9048

2023-05-18 19:54 UTC, closed without merging