[UI/UX:System] Changing SAML Management page colors
Submitty/Submitty pull request #8625
Opened 2022-11-22 19:13 UTC by jenaybarela

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
Currently there is an ugly brown color on the SAML Management. There is also some misalignment with the activate and deactivate button.

### What is the new behavior?
![image](https://user-images.githubusercontent.com/25368899/203398764-2647562d-8675-4318-9b88-9445269d16de.png)

### Other information?

2022-11-22 22:40 UTC, williamjallen commented
Minor UI question: Is there a reason why we need the "Active?" column if there's already a button which clearly indicates whether the user is active or not?

2023-02-07 15:07 UTC, jenaybarela commented
I got rid of the active column and justified things to the left
![Screenshot 2023-02-07 100359](https://user-images.githubusercontent.com/25368899/217282853-d0436484-4fa3-4008-9a78-6759876e4794.png)

2023-02-08 02:45 UTC, williamjallen commented
Would it be possible to include a screenshot of the "before" picture to compare to the "after" picture included in the PR body?

2023-02-08 02:48 UTC, williamjallen requested changes

2023-02-08 02:48 UTC, williamjallen commented on site/app/templates/superuser/SamlManager.twig
> +                        <button class="btn btn-primary" style="padding: 6px 21px">Activate</button>
This padding shouldn't be set manually like this.  I'm not certain what the intent is, but doing this is prone to conflicts in the future, given that the button already has padding set.  If we were to change the styling of the `btn`  class, this particular button would be left behind.

2023-04-28 03:10 UTC, merged