User assignment settings
Submitty/Submitty pull request #8632
Opened 2022-11-28 19:21 UTC by jssunray34

**draft PR

### What is the new behavior?

The user_assignment_settings.json file is now visible in the TA grading interface (for now it is in the submissions folder).

Closes #8459

2022-12-12 22:40 UTC, jssunray34 commented on site/app/libraries/Access.php
> +        if (count($subpart_values) < count($subpart_types)) {
@ashergottlieb I removed "version" from "subparts" but as a result had to modify `path.read.submissions`. I can continue playing around with seeing if we can specify a single file in Access.php, but wanted wanted to see if the change I made is any better?

One question I had is why do we not want users to be able to access outside the version directory?

2023-05-18 19:58 UTC, bmcutler commented
@musaabimran -- please take over work on this PR.
with @cjreed121 's help.

2023-07-12 01:40 UTC, williamjallen submitted a review, later dismissed
@musaabimran It looks like you've checked in a bunch of irrelevant changes.  Please revert them.

2023-07-12 01:57 UTC, cjreed121 requested changes
Also make sure that the file isn't readable in anonymous mode.

2023-07-12 01:57 UTC, cjreed121 commented on site/app/libraries/Access.php
> +            "subparts" => ["gradeable", "submitter"],
By only doing this, a student could now access this file which is not intended behavior. Instead a new element needs to be added to directories for the higher level directory.

2023-07-12 01:57 UTC, cjreed121 commented on site/app/models/gradeable/AutoGradedVersion.php
> +                }
Rather than looping over all files in that directory, you could check the files existence right away.

2023-07-12 01:57 UTC, cjreed121 commented on site/app/views/grading/ElectronicGraderView.php
> +        }
You could just check if grading access is allowed for the user which would cleanup the code a lot.

2023-12-14 06:25 UTC, musaabimran approved these changes

2024-02-24 16:17 UTC, bmcutler commented
@musaabimran  or @cjreed121 
Can you please resolve the merge conflicts?

2024-04-09 18:04 UTC, merged