[Feature:InstructorUI] Added course_id column
Submitty/Submitty pull request #8777
Opened 2023-01-27 19:01 UTC by tkoz0

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
No `course_id` column in the database.

### What is the new behavior?
Added `course_id` column to the database to store an extra string for university-specific course (section) identifying information.

### Other information?

Step 1 of #8770. Tested by performing insert/update operations in the main Submitty database.

2023-01-31 21:11 UTC, kraduc requested changes
Main review is the comment about dropping the column.

I'm not 100% sure if we need to worry about a possible state in which the sync migration is up and the adding column migration is down. If we do, these should probably be combined into one migration with two sql execute statements for the up migration and for the down migration. Otherwise, it is probably fine as it is.

2023-02-01 18:54 UTC, pbailie commented on migration/migrator/migrations/course/20230126130456_add_course_id_column.py
> +DROP COLUMN IF EXISTS course_id
This information is available from the registrar, so its loss could be recovered.

2023-02-01 18:54 UTC, pbailie commented on migration/migrator/migrations/master/20230126125745_add_course_id_column.py
> +DROP COLUMN IF EXISTS course_id
This information is available from the registrar, so data loss can be recovered.

2023-02-01 20:01 UTC, bmcutler commented
@pbailie I agree, let's name it course_section_id

2023-02-23 18:11 UTC, pbailie approved these changes

2023-02-24 20:52 UTC, merged