[Testing:Developer] Increase PHPStan level to 5
Submitty/Submitty pull request #8857
Opened 2023-02-08 03:36 UTC by williamjallen

### What is the current behavior?
PHPStan is currently set to level 4.  No errors are generated by PHPStan if the specified type does not match the type passed to a function.  This results in many cases of dubious type inference, where the code happens to work as expected, but not necessarily in a readable way.  As we start preparing to switch to PHP 8.x, it is possible that many of these cases will become problematic due to changes in type conversion.  In particular, I am worried about the changes in comparisons between strings and integers outlined [here](https://www.php.net/manual/en/migration80.incompatible.php).

For reference, the PHPStan rule levels can be found here: https://phpstan.org/user-guide/rule-levels

### What is the new behavior?
I have increased PHPStan's rule level to level 5.  This will ensure that types match when specified.  An attempt was made to cut down the number of errors, but only relatively safe changes were made.  The rest of the errors have been added to the baseline.

2023-02-14 17:58 UTC, mahi-pas commented
Error on "seek team/partner" button in teams
![image](https://user-images.githubusercontent.com/47994802/218819093-0dca8c41-26eb-4eb3-8b9f-e2d717e69b8b.png)
![image](https://user-images.githubusercontent.com/47994802/218819175-9f3863c5-9a9f-4d78-a191-75360a37adf0.png)
if I click the button, the screen becomes this error

2023-02-14 18:09 UTC, mahi-pas commented
It appears the buttons (documentation and run query) in SQL toolbox aren't working, they are pressed but nothing happens
![image](https://user-images.githubusercontent.com/47994802/218821245-0f29c892-d902-4c52-afbf-7cb4a079d84e.png)

2023-02-14 18:11 UTC, mahi-pas commented
Not sure if this is just because I'm running on vagrant but in office hours queue, today's history is blank, even after I clicked finish helping on Alyssa P Hacker. It says the websocket isn't connected
![image](https://user-images.githubusercontent.com/47994802/218821636-15c99618-de4f-4425-9985-b460575071fb.png)

2023-02-15 01:13 UTC, williamjallen commented
@mahi-pas Thanks for finding these issues!  I will look into them.

Just a comment about reviewing: it is generally better to request changes instead of commenting if you find an issue like this.  You can do that by going to the "Files Changed" tab at the top of this page and clicking "Review changes"

2023-02-16 15:29 UTC, williamjallen commented
@mahi-pas 

1. "seek team/partner" error -- this seems to exist on `main` as well, so it is a bug which should be fixed, but is unrelated to my changes in this PR.  From a brief glance at the offending code, this issue seems to be unrelated to types altogether.  This function will throw an exception if no rows are returned, which is the source of the error you found.
https://github.com/Submitty/Submitty/blob/4d6120e98b3ef3be3a4f48573a55c72081bc5781/site/app/libraries/database/DatabaseQueries.php#L3446-L3456
2. I am unable to identify any issues with the SQL toolbox.  Writing a SQL query, and then clicking "Run Query" generates the expected results.  In your screenshot, I don't see a `FROM` clause in your SQL query, which might be causing issues.  Try something like `SELECT * FROM polls`.
3. OH Queue -- I am unable to find any issues on the office hours queue.  It is normal to not see anyone in the "today's history" section, because you probably created your VM more than a day ago.  If you add a new student to the queue and then finish helping them, the new student should show up in the history.  As for the websockets issue, that is probably a problem with your local environment.

2023-03-11 09:10 UTC, cjreed121 reviewed
Changes all look good. Couple comments to possibly make things shorter/simpler.

2023-03-11 09:10 UTC, cjreed121 commented on site/app/controllers/admin/AdminGradeableController.php
> +            }
Could we just use `strcmp`?

2023-03-11 09:10 UTC, cjreed121 commented on site/app/libraries/plagiarism/PlagiarismUtils.php
> +            }
Could we just return the difference between a's start and b's start?

2023-03-22 04:06 UTC, cjreed121 requested changes

2023-03-22 04:06 UTC, cjreed121 commented on site/app/controllers/admin/AdminGradeableController.php
> +            return strcmp($a, $b);
Haven't looked too much at this but wouldn't we want this instead?
```suggestion
            return strcmp($a[0], $b[0]);
```

2023-03-24 21:18 UTC, merged