[Refactor:System] Separate UTM variable from ARM
Submitty/Submitty pull request #8890
Opened 2023-02-11 03:41 UTC by skara9

#### Current Behavior
The VM installation scripts currently check for an `aarch64` architecture and assign the shell variable `UTM_ARM` to track it.
Also, the install script skips installing haskell stack for ARM machines.

#### Updated Behavior
* A separate `--utm` flag has been added to indicate running on UTM, differentiating between ARM configurations not running on UTM and configurations of any architecture running on UTM.
* A `DEV_VM` variable has been created to indicate a script running on either Vagrant or UTM.
* Furthermore, the install script has been updated to install haskell stack for ARM given that stack ships an ARM binary since [v2.9.1](https://github.com/commercialhaskell/stack/releases/tag/v2.9.1).

Partly addresses #7885

2023-03-03 22:59 UTC, bmcutler commented
@MasterOdin Can you help review this please? thanks

2023-03-06 05:07 UTC, MasterOdin requested changes
Changes overall seem reasonable given the concept that we are potentially supporting multiple different VM platforms. Some minor comments.

2023-03-06 05:07 UTC, MasterOdin commented on .setup/install_system.sh
> +export UTM=0
add `export DEV_VM=0` up here as well.

2023-03-07 20:32 UTC, tkoz0 commented
I tested `vagrant up` on this branch and it works as expected. My host OS is Ubuntu 22.04 on an Intel x86_64 CPU and my hypervisor for the VM is VirtualBox 6.1.

2023-03-17 21:14 UTC, bmcutler commented
@MasterOdin could you please re-review?  Thanks!

2023-03-31 18:13 UTC, EdenBendheim reviewed
I ran into an installation error:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/114759691/229197866-b5f714e5-09cd-4d46-83aa-153a41678552.png">

Not too sure of how to fix it. Looked around in Install_system and the files for installing it were there.

2023-04-04 08:59 UTC, merged

2023-04-04 09:04 UTC, MasterOdin commented
@EdenBendheim You're hitting that error when going through UTM? I think we stopped trying to install that package from Ubuntu 20.04 and onwards though so I'm not sure why you're hitting that assuming you're installing Ubuntu 20.04. If you're trying to install an older Ubuntu, that's unsupported.