[Features:TAGrading] Auto open Images
Submitty/Submitty pull request #8984
Opened 2023-02-28 20:17 UTC by ANS1514

### Please check if the PR fulfills these requirements:

### What is the current behavior?

Images don't auto open in the TA grading panel

### What is the new behavior?
Images will auto open in the TA grading panel and will stay open even if you refresh the page.

### Other information?

I made a course on my local machine and created a discussion forum thread and made a post with an attachment. Then I made a homework linked to that thread, made a submission then went to grade it and use the discussion forum panel in the TA grader to see if the image opened.

2023-03-01 02:50 UTC, cjreed121 requested changes
Do you think you could instead put this logic into [DiscussionForumPanel.twig](https://github.com/Submitty/Submitty/blob/main/site/app/templates/grading/electronic/DiscussionForumPanel.twig)? That is much more closely tied to where we want this to happen. This would add a lot of extra computation on the forum since it would never apply.

2023-03-18 02:13 UTC, williamjallen requested changes

2023-03-18 02:13 UTC, williamjallen commented on site/app/templates/forum/CreatePost.twig
> +
This change seems to be unrelated and should be reverted

2023-03-18 02:13 UTC, williamjallen commented on site/app/templates/grading/electronic/DiscussionForumPanel.twig
> +});
All of this code should probably be moved to the relevant `.js` file.  Perhaps `ta-grading.js`.

2023-04-01 20:41 UTC, williamjallen requested changes
One quick change to prevent potential merge conflicts with other PRs and I'll approve.

2023-04-01 20:41 UTC, williamjallen commented on site/public/js/forum.js
> +
This line is unrelated to the rest of the changes and should be reverted.

2023-04-07 03:22 UTC, williamjallen approved these changes

2023-04-11 16:19 UTC, merged