<Bugfix:Submission> Notebook Copy In Multiple Choice
Submitty/Submitty pull request #9020
Opened 2023-03-10 17:32 UTC by 04vmatsibekker

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
If there is a multiple choice where two of the values are the same, the notebook gradeable will be built.

### What is the new behavior?
The Notebook will not be built and will display an error message.
![image](https://user-images.githubusercontent.com/117249183/224383679-aeda3d82-bc59-41e6-90ea-5215b10527a5.png)

### Other information?

2023-03-10 19:47 UTC, williamjallen requested changes

2023-03-10 19:47 UTC, williamjallen commented on grading/load_config_json.cpp
> +              for (++it_next; it_next != choices.end(); ++it_next){
I believe this variable declaration can be moved into the for-loop declaration

2023-03-10 19:47 UTC, williamjallen commented on grading/load_config_json.cpp
> +                  std::cout  << "ERROR: " << it.value() << " == " << it_next.value() << std::endl;
```suggestion
                if (value == value_next) {
                  std::cout  << "ERROR: " << it.value() << " == " << it_next.value() << std::endl;
                }
```

2023-03-10 19:47 UTC, williamjallen commented on grading/load_config_json.cpp
> +                  std::cout  << "ERROR: " << it.value() << " == " << it_next.value() << std::endl;
This error message isn't very descriptive.  It would be better to indicate both the problem and a suggested resolution.

2023-03-10 20:41 UTC, 04vmatsibekker commented
@williamjallen
Does the new text that is outputted as the error message look better?

2023-03-10 21:00 UTC, williamjallen commented
The code changes seem reasonable to me.  I'll leave the feature/functionality review to someone more knowledgeable about this part of the codebase.

2023-03-14 17:35 UTC, Eceptonsu approved these changes
Tested on my machine, works well.

2023-03-14 21:12 UTC, merged