[Bugfix:Forum] Websocket order fix
Submitty/Submitty pull request #9089
Opened 2023-03-24 03:54 UTC by ANS1514

### What is the current behavior?

Say that two people have the discussion forum open. If student1 were to create a post it would show up at the top of the page, above pinned threads, for student2. Ideally this is not the case and it shows up below the pinned threads.

### What is the new behavior?
The behavior I saw in my tests show that the post now shows up below the pinned threads.

### Other information?

I tested this behavior by making pinned posts and regular posts in the discussion forum on a Submitty site on microsoft edge and I saw how it changed a seperate submitty site I had open on google chrome.

2023-03-24 18:58 UTC, ch3nnyj approved these changes
I have reviewed and tested your changes and can assure you it has fixed the issue. Your code looks functional and I don't see any changes that need to be made. You have ensured that the insertion is below every pinned discussion. Nice work!

2023-03-24 20:59 UTC, williamjallen commented on site/public/js/forum.js
> +                                let spot_after_announcements = $('.thread_box_link').first();
This variable doesn't appear to be reassigned after the initial declaration, so it should be defined as a constant.

```suggestion
                                const spot_after_announcements = $('.thread_box_link').first();
```

2023-04-07 03:18 UTC, williamjallen requested changes
This new code is quite a hack, but not particularly out of character for the discussion forum code unfortunately, so I'll approve it as long as the functionality is correct.

The original issue is fixed, but now you have the opposite problem: both regular posts and new announcements appear under the previous announcements when updating via websockets.  When you reload the page, the new announcements move to the top of the list.  The intent here is for new posts to show up in the same order they are displayed when the page is first loaded.

2023-04-08 14:00 UTC, williamjallen approved these changes

2023-04-08 15:16 UTC, merged