E2e testing - just trying stuff out
Submitty/Submitty pull request #9105
Opened 2023-03-27 16:37 UTC by 04vmatsibekker

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

### What is the new behavior?

### Other information?

2023-04-08 14:48 UTC, williamjallen requested changes

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
> +#     description: 'A name to include in the greeting'
This should probably be removed

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
> +#       shell: bash
Same here

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
> +descriptions: 'Uses the composite action to copy and set up files'
Should these be a bit more descriptive?

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
Should the filename be a bit more descriptive?

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
> +      shell: bash
I believe this only needs to be installed for the selenium tests (for the tests in `tests/e2e/test_accessibility.py` specifically)

2023-04-08 14:48 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
> +      shell: bash
This is only necessary for the selenium tests

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> -
It might be good to restore the space between jobs to aid readability

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +          - shellcheck
We can shave off another 3-4 minutes from the overall running time by not adding these as dependencies.

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
>              run: sudo bash tests/test_site_error_log.sh
This needs to be run after every job.  Perhaps there is a way to do this automatically by adding something like [this](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost) to the setup action you created.

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +    e2eCypressTwo:
I don't think there's a need to have two separate Cypress jobs here.  All of the stuff in this job takes less than 5 minutes to complete, based on the most recent CI runs.  The setup will likely take longer than the actual testing here.

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +              - 5432:5432
I don't think we need Postgres for the integration tests

2023-04-08 14:48 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +        steps:
I think most of the stuff in this section can be eliminated.  The integration tests are mostly unit tests, and don't need the sample courses or website to be working as far as I am aware.

2023-04-08 14:50 UTC, williamjallen commented
Given the number of commits here, you might also consider squashing your current changes into a single commit.

2023-04-08 16:23 UTC, 04vmatsibekker commented on .github/actions/set-up-composite/action.yml
I am pretty sure the filename has to be called action.yml for it to work. That is at least what I have seen when looking it up.

2023-04-08 22:02 UTC, williamjallen commented on .github/actions/set-up-composite/action.yml
Sure, but can `set-up-composite` be changed?

2023-04-09 00:31 UTC, 04vmatsibekker commented on .github/actions/set-up-composite/action.yml
yup and I will change it

2023-04-15 13:49 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +          - shellcheck
Something like [this](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) might work.  If I'm understanding the docs correctly, it should kill all the other running jobs whenever a job with the fail fast option fails.

2023-06-03 13:57 UTC, williamjallen requested changes
I still need to do a more thorough review, I'll leave these comments here in the meantime:

2023-06-03 13:57 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +            - uses: shivammathur/setup-php@2.25.1
It looks like this dependency has been updated since you created this PR.  Please bump the version to 2.25.2 like we have on main.

2023-06-03 13:57 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +          - uses: shivammathur/setup-php@2.25.1
Same here

2023-06-03 13:57 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +    e2eSelenium:
It might be good to add some whitespace here to make it clear that this is a new job

2023-06-03 13:57 UTC, williamjallen commented on .setup/pip/system_requirements.txt
> +numpy==1.24.2
This change should be reverted.

2023-06-03 13:57 UTC, williamjallen commented on .github/workflows/submitty_ci.yml
> +          image: postgres
It would be good to add a comment here stating why postgres is listed here, as well a TODO to remove it eventually.

2023-06-06 02:05 UTC, williamjallen requested changes
In general, I think things are looking pretty good here and we should be able to get this merged pretty soon.  We can probably make some more improvements eventually, but this should serve as a decent starting place at least.

Something to note: It looks like the regular e2e job is marked as "waiting".  I don't see an e2e job listed in the yaml file, so I assume that the waiting job is related to the `workflow_dispatch` trigger and will go away once this is merged.

Unrelated to the PR itself, but general development advice:  Good commit messages help you stay organized, and help reviewers understand why each commit was made.  Currently I see this:
![image](https://github.com/Submitty/Submitty/assets/16820599/9c18df1d-cccf-460b-94f6-48713d5d9e14)
These commit messages tell me *what* was changed, but not *why*.  I can see what was changed by looking at the diff, so the commit message is rather useless.  A better commit message would be something like "Add comment about x, y, and z" or "Re-add database service to integration tests", for example.

2023-06-08 23:28 UTC, williamjallen approved these changes
Changes seem reasonable to me.  Any further changes can be made as separate PRs.

2023-06-09 01:18 UTC, merged