[Feature:Autograding] Autograding example for Verilog
Submitty/Submitty pull request #9231
Opened 2023-04-27 19:05 UTC by tkoz0

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?
There is no autograding example using Verilog.

### What is the new behavior?
An example has been added for Verilog autograding.

### Other information?
The docker container be pushed to a Submitty Docker Hub account before approving this PR.

2023-04-28 00:19 UTC, AdamTuhacek approved these changes
Looks good, I was able to set up a test gradable using the sample files and the autograder works as expected.

2023-05-02 17:39 UTC, prestoncarman commented on grading/execute.cpp
> +    { "iverilog",                "/usr/bin/iverilog" },
My question is more about the whole docker process then this PR.
* Where is the Submitty docker image defined. Does the image contain the Submitty code base?
* I am wondering why you need to add verlog commands here? My initial thought was they would only be accessible in the docker.

2023-05-15 16:11 UTC, prestoncarman commented on grading/execute.cpp
> +    { "iverilog",                "/usr/bin/iverilog" },
Thanks for clarifying.

2023-05-17 12:34 UTC, saumyaborwankar requested changes
I think there is just one change needed in the config.json file. Along with rebasing with main. I had to bring your changes to my branch and test them due to an error while executing the `submitty_install` inside the VM. 


"ERROR: docker.errors.DockerException: Error while fetching server API version: request() got an unexpected argument 'chunked'"

2023-05-17 12:34 UTC, saumyaborwankar commented on more_autograding_examples/verilog_hello_world/config/config.json
> +        "container_image": "tkoz0/submitty-verilog"
I think this needs to be changed to "tkoz0/submitty-verilog:latest" as there is a need to add this custom docker to the "Docker UI" section which will only accept a docker with the correct tag <Image name>:<tag>. And currently there is no way of manipulating the alias of the docker added.

2023-05-19 00:18 UTC, prestoncarman commented
Would it make sense to have a Submitty supported **verilog** docker image? Or is this not a common use case?

2023-07-28 18:41 UTC, bmcutler commented
@saumyaborwankar please update now that https://github.com/Submitty/DockerImages/pull/17 was merged

2023-12-12 18:51 UTC, cjreed121 approved these changes
Tested locally and works as expected

2023-12-12 19:42 UTC, merged