[Refactor:Submission] Change regrade to grade_inquiry
Submitty/Submitty pull request #9398
Opened 2023-06-06 17:02 UTC by NiaHeermance

### What is the current behavior?
While the Grade Inquiry feature has been by its current name to users for a while, in the code, it was referred to by "regrade_request" or sometimes simply "regrade." This name was confusing because the term "regrade" is already used for adding submissions to the grading queue.

### What is the new behavior?
All appropriate places in the code and database have been renamed from "regrade_request" to "grade_inquiry".

2023-06-08 15:27 UTC, musaabimran commented
I've checked out the PR, and it's spot-on! It was totally necessary because that word "regrade" was causing a ton of issues. The changes made in the PR tackle those problems.

2023-06-08 15:28 UTC, musaabimran approved these changes
I've checked out the PR, and it's spot-on! It was totally necessary because that word "regrade" was causing a ton of issues. The changes made in the PR tackle those problems.

2023-06-09 14:13 UTC, mahi-pas requested changes

2023-06-09 14:32 UTC, mahi-pas requested changes

2023-06-09 14:43 UTC, NiaHeermance commented on site/public/js/server.js
Actually, that function is no longer used, so I have deleted it and pushed a new commit. Thanks for the catch!

2023-06-09 19:36 UTC, mahi-pas commented
Did some basic grade inquiry testing. Looks good to me

2023-06-09 19:43 UTC, mahi-pas approved these changes
LGTM

2023-06-12 19:25 UTC, merged