Cypress submission
Submitty/Submitty pull request #9406
Opened 2023-06-10 19:00 UTC by im-ajaymeena

fixes #9347

2023-06-19 17:18 UTC, im-ajaymeena commented on site/cypress/e2e/submission.spec.js
> +    const fileDir = 'cypress/fixtures/submissions';
I couldn't find ways to make cypress to access files outside `cypress` directory, if you have any suggestion let me know

2023-08-28 01:54 UTC, williamjallen requested changes

2023-08-28 01:54 UTC, williamjallen commented on site/cypress/e2e/cypress-feature/submission.spec.js
> +function setupTestStart() {
Why does this need to be in a function?  It would be more clear to simply put it in the `beforeEach()`.

2023-08-28 01:54 UTC, williamjallen commented on site/cypress/e2e/cypress-feature/submission.spec.js
> +function removeSuccessPopup() {
This function is only used in one spot and thus can be inlined as well.

2023-08-28 01:54 UTC, williamjallen commented on site/cypress/e2e/cypress-feature/submission.spec.js
> +    let submissionCount = 0;
Should this be a Cypress variable?

2023-08-28 01:54 UTC, williamjallen commented on site/cypress/e2e/cypress-feature/submission.spec.js
> +    });
You could generate these tests dynamically with `array.forEach()`, and then inline the `makeSubmission()` function.  See [here](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/fundamentals__dynamic-tests/cypress/e2e/list-spec.cy.js) for an example.

2023-08-29 01:02 UTC, williamjallen approved these changes
Seems reasonable to me.

2023-08-29 01:07 UTC, merged