Change course spaces
Submitty/Submitty pull request #9453
Opened 2023-06-20 18:28 UTC by 04vmatsibekker

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

### What is the new behavior?

### Other information?

2023-06-21 00:30 UTC, williamjallen requested changes
The PR body needs to be filled out so it is clear why this PR is necessary and what changes were made.

2023-06-21 00:30 UTC, williamjallen commented on migration/migrator/migrations/master/202306205342134_add_course_and_semester_constraint.py
> +    database.execute("ALTER TABLE terms DROP CONSTRAINT no_surrounding_spaces_semester")
`up()` and `down()` should each contain a single `database.execute()` call to make sure the entire migration gets rolled back as a single transaction if something goes wrong.

2023-06-22 02:35 UTC, williamjallen commented on migration/migrator/migrations/master/202306205342134_add_course_and_semester_constraint.py
> +    database.execute(sql)
These lines are pretty long, so it would probably be a good idea to break them into multiple lines (although still as part of a single string).

2023-06-22 20:02 UTC, bmcutler commented
If we're adding a constraint, let's make it a more useful constraint, not limited only to spaces on the calendar page.
(I think this constraint is not even strong enough for that use -- spaces in the middle could also break things).

Semester & should be restricted to letters, numbers, underscore & dash like the owner & group.
Also, please name the constraint similarly to the owner & group constraints.

2023-06-22 20:02 UTC, bmcutler requested changes
(see comment above)

2023-06-23 18:56 UTC, bmcutler approved these changes

2023-06-23 18:59 UTC, merged