[Feature:CourseMaterials] move files
Submitty/Submitty pull request #9497
Opened 2023-06-30 01:53 UTC by 04vmatsibekker

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

Instructors can upload file, but once they do so, there is no way to change file name/file location
### What is the new behavior?
Now instructors can change the file name/location, and display a different file name (link_title, for now) to non-owners of file.

New UI for both file/URL changes
![Edit](https://user-images.githubusercontent.com/29582421/164058099-a3ffb2fd-5330-4c5d-af19-9b2575777dc6.PNG)

### Other information?

2023-06-30 01:53 UTC, 04vmatsibekker commented
#9464

2023-06-30 01:59 UTC, williamjallen commented
Is there a reason why you made multiple PRs with the same changes and closed one of them?  This seems to be almost identical to #9464 and #9497.

2023-07-12 01:42 UTC, ziesski approved these changes
Looks good :)

2023-07-17 03:33 UTC, cjreed121 requested changes

2023-07-17 03:33 UTC, cjreed121 commented on site/app/controllers/MiscController.php
> +        if ($dir == 'submissions') {
```suggestion
        if ($dir === 'submissions') {
```

2023-07-17 03:33 UTC, cjreed121 commented on site/app/controllers/MiscController.php
> +            }
Is there a reason adding this is in this PR? I feel it should be a separate PR?

2023-07-17 03:33 UTC, cjreed121 commented on site/app/controllers/course/CourseMaterialsController.php
> +            }
You could use the php function `dirname` to clean this up a bit and not do as many substrings and position checks

2023-07-17 03:33 UTC, cjreed121 commented on site/app/libraries/FileUtils.php
> +     * empty subdirectories inside that directory
Update this comment

2023-07-17 03:33 UTC, cjreed121 commented on site/app/libraries/FileUtils.php
> +        }
The file `test..test.out` is a valid filename which does not cause a parent directory issue. Are we now blocking that?

2023-07-17 03:33 UTC, cjreed121 commented on site/app/controllers/course/CourseMaterialsController.php
> +                rename($course_material->getPath(), $new_path);
Why not only rename?

2023-07-20 20:16 UTC, cjreed121 requested changes

2023-07-20 20:16 UTC, cjreed121 commented on site/app/libraries/FileUtils.php
> +        }
Is this just checking if the first or last 2 characters are `..`? A better check you can do is too iterate over all of the directory names and see if they equal `..`. You can just split by `/`.

2023-07-21 14:17 UTC, NiaHeermance requested changes
I am able to move files around and download them as intended.

2023-07-21 15:32 UTC, NiaHeermance approved these changes
I am able to move files to new paths as well. I approve!

2023-07-21 17:41 UTC, merged