Preliminary idea of what to do
Submitty/Submitty pull request #9521
Opened 2023-07-12 19:12 UTC by mahi-pas

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### What is the current behavior?

### What is the new behavior?

### Other information?

2023-07-24 18:29 UTC, 04vmatsibekker approved these changes

2023-07-27 18:32 UTC, NiaHeermance requested changes
As a student, indeed Notebook files do not download. However, as an instructor, they do, an unintended behavior.

2023-07-27 18:57 UTC, NiaHeermance requested changes
Additionally, TA and Grader also have the Notebook files downloaded when they should not.

2023-07-27 19:20 UTC, NiaHeermance approved these changes
The notebook files do not download for all users now. Yay!

2023-07-28 15:53 UTC, bmcutler requested changes
For the development course Notebook Filesubmission gradeable I uploaded these 2 files in the Problem 4 box:

<img width="369" alt="Screenshot 2023-07-28 at 11 51 44 AM" src="https://github.com/Submitty/Submitty/assets/5871417/5b4a875a-7836-465e-9bf5-17af3a9aff2a">

However, since the name problem_3_animal.txt matches the instructor chosen name for another question, this file is incorrectly excluded from both the individual file download list and the zip of all files:

<img width="506" alt="Screenshot 2023-07-28 at 11 52 53 AM" src="https://github.com/Submitty/Submitty/assets/5871417/a10db0da-9b60-4c08-b6e9-391432d97e5b">

2023-08-07 11:37 UTC, NiaHeermance approved these changes
Works and looks good! I'm approving since my suggested change is small/doesn't effect functionality, but I would recommend adding a function comment to canStudentDownloadFile since our linter looks for that now.

2023-08-07 11:37 UTC, NiaHeermance commented on site/app/models/gradeable/Gradeable.php
> +    public function canStudentDownloadFile(int $version, string $file_path, string $root_path): bool {
You should add a function comment about the parameters and return type.

2023-08-08 16:31 UTC, merged