[Feature:Calendar] Calendar Color Select + Legend
Submitty/Submitty pull request #9658
Opened 2023-08-14 15:29 UTC by mahi-pas

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?
Students couldn't select colors or see a legend where all the colors are displayed

### What is the new behavior?
Students can select what color the course is displayed as well as see a legend
![image](https://github.com/Submitty/Submitty/assets/47994802/2843e6c5-feca-4ba4-bf41-949ff9876d3b)
![image](https://github.com/Submitty/Submitty/assets/47994802/9f99489a-3de4-41c3-b461-444f80729922)

Additionally, there are 8 color options for light and dark modes. These colors all pass WAVE's guidelines for contrast with text.
These are calendars with all colors displayed:
![Screenshot from 2023-08-14 15-54-17](https://github.com/Submitty/Submitty/assets/47994802/d13a0169-09b8-4e8f-b826-3f16998aad96)
![Screenshot from 2023-08-14 15-33-11](https://github.com/Submitty/Submitty/assets/47994802/4d5e8425-7b00-4a38-b193-21f60d2cc1d7)
![Screenshot from 2023-08-14 15-33-43](https://github.com/Submitty/Submitty/assets/47994802/be8e5491-f66a-4bef-838e-958453d7a21c)
*Note: Due to changing color options, this has also changed the colors used in other places such as docker container colors. Please check to make sure nothing has broken.*

### Other information?
Yet to add:
Using course names rather than codes

2023-08-14 18:17 UTC, mahi-pas commented
For colors, I'm going to test each category color using this jquery function
```js
$('.cal-gradeable-item').each(function(i) {
    $(this).css('background-color', `var(--category-color-${i})`);
})
```

2023-08-16 16:12 UTC, 04vmatsibekker requested changes
Looks pretty good. One thing that I will say though, is that we are unable to distinguish course notes by color. As you can see in the image below, the announcement in the class blank, has a colored border, but the blank note has no color indication. Is there any that you can maybe add? Or do you think this would be a separate PR. 
<img width="707" alt="image" src="https://github.com/Submitty/Submitty/assets/117249183/2dc8ebec-f0e0-41e1-a97e-ea07a7b3a3c5">

2023-08-17 17:52 UTC, NiaHeermance approved these changes
Looks great!!! I wish yellow was a color though, ha ha. Approved!

2023-08-18 13:24 UTC, ziesski approved these changes

2023-08-18 15:13 UTC, mahi-pas commented on site/app/templates/admin/Docker.twig
> +                        <span class="badge badge-{{ capability_to_color[capability] % 12 }}">{{capability}}</span>
This modulo is making sure that it doesn't go past 12 colors. Although I should change it to 8. I did this so we can reduce the number of category colors down the line

2023-08-18 17:15 UTC, 04vmatsibekker approved these changes

2023-08-18 18:43 UTC, merged