Late days
Submitty/Submitty pull request #9691
Opened 2023-08-20 16:17 UTC by musaabimran

### What is the current behavior?
When 9223372036854775807 is entered in late days this error appears.
![image](https://github.com/Submitty/Submitty/assets/96174078/6db51c5e-581d-4266-b15e-f7e7b781f5a7)

### What is the new behavior?
The error does not occur and a limit is set on number of late days (10000).  Closes #9690

2023-08-21 00:05 UTC, williamjallen requested changes

2023-08-21 00:05 UTC, williamjallen commented on site/app/templates/admin/Configuration.twig
> +                <strong> Maximum Late Days : 10,000 </strong> <br>
This change just makes the UI more cluttered, and is entirely meaningless to most instructors.  The API error response should be more than enough to determine what went wrong if for some reason an instructor decides to award more than 27 years worth of late days...

2023-08-24 17:20 UTC, Youssef-Chip commented
> 

I apologize, I was mistaken, I was testing the bug on another page. Your bugfix actually works on the course settings page. However I found another bug in the late days allowed page and have implemented another bugfix there

2023-08-24 17:21 UTC, musaabimran commented
> > 
> 
> I apologize, I was mistaken, I was testing the bug on another page. Your bugfix actually works on the course settings page. However I found another bug in the late days allowed page and have implemented another bugfix there

No worries, I am glad you got the fix.

2023-08-24 17:25 UTC, Youssef-Chip approved these changes

2023-08-24 20:44 UTC, merged