[System:Developer] Save VM after vagrant up job
Submitty/Submitty pull request #9766
Opened 2023-09-09 02:30 UTC by IDzyre

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

### What is the new behavior?

### Other information?

2023-10-12 00:33 UTC, williamjallen requested changes

2023-10-12 00:33 UTC, williamjallen commented on .github/workflows/vagrant_up.yaml
> +      - uses: actions/checkout@v3
It looks like you might have had a bad merge conflict here.  This should be bumped to `v4` to match the latest version on main.

2023-10-24 02:03 UTC, williamjallen commented on .github/workflows/vagrant_up.yaml
> +        run: NO_SUBMISSIONS=1 vagrant up
Is there enough disk space to make submissions?  Most developers who are downloading this VM are going to want the sample courses to be set up already.

2024-02-07 21:46 UTC, ziesski approved these changes
I tested this feature with my intel Mac, with virtual box.
This was very smooth and fast!
With my old intel mac, vagrant destroy and up takes at least 1.5 hours, but with this PR it took less than 10 mins on initial up, and from then on it takes less than 5 mins for VM to be up and running. (as it skips the download process). 
One thing to mention tho is that it ends without any notification/prompt(green duck). 
So I was slightly confused when it terminated. Should add some info when process completes.

2024-02-24 01:15 UTC, VVVITH approved these changes
Test with Arm M1 chip Mac using qemu, it goes well now.

2024-02-24 06:11 UTC, merged