[Feature:API] Student Override Back Into Course
Submitty/Submitty pull request #9768
Opened 2023-09-09 16:16 UTC by NiaHeermance

### What is the current behavior?
When student's are dropped from a course by automated scripts, they have no way of rejoining the instructor without contacting the instructor. This can cause them to get behind on work, and the instructor has to manage readding students.

### What is the new behavior?
The No Access page for a course now has an option for students to rejoin a course, provided they meet certain conditions:

- The student was not manually removed from the course by the instructor
- The student was in the course to begin with
- It is within two weeks of the start of the term OR the student has accessed a gradeable, poll, forum post, course material, etc within the last 72 hours.

This PR address issue #9738 but does not close it, as future PRs will address other parts of that issue.

### Images
![image](https://github.com/Submitty/Submitty/assets/51209504/1f264d3c-6a91-4185-bea6-b5193b3802a8)
and then,
![image](https://github.com/Submitty/Submitty/assets/51209504/2cd9e95e-e309-4a89-891b-6b7c7464b2bc)

2023-09-22 02:45 UTC, cjreed121 requested changes
2 changes then this looks good to be merged

2023-09-22 02:45 UTC, cjreed121 commented on site/app/controllers/SelfRejoinController.php
> +            return new RedirectResponse("$course_url/no_access");
It's better to use buildCourseUrl here

2023-09-22 02:45 UTC, cjreed121 commented on site/app/controllers/SelfRejoinController.php
> -            );
You can do core->addErrorMessage() to give the client some idea of what happened.

2023-09-26 03:35 UTC, cjreed121 approved these changes
Looks good to me. My only comment would be to add tests to ensure functionality but that could wait.

2023-09-27 04:21 UTC, merged

2023-10-06 18:51 UTC, pbailie commented
This PR should have no impact on or conflict with my sysadmin scripts.