[Features:System] Recently Dropped Icon
Submitty/Submitty pull request #9818
Opened 2023-09-27 15:02 UTC by NiaHeermance

### What is the current behavior?
There is no way for instructors to see the recently dropped students. Recently dropped students can rejoin a course, so it can be useful for an instructor to know who can readd themselves and who needs a manual readd.

### What is the new behavior?
There is now an icon for recently dropped students.

### Images
![image](https://github.com/Submitty/Submitty/assets/51209504/102773dd-2c1b-4309-b91e-d693f8f15aa4)

2024-05-31 15:29 UTC, micpap25 requested changes
Works as intended on the user end, just a few code nitpicks

2024-05-31 15:29 UTC, micpap25 commented on site/ts/activity-dashboard.js
> -
Can this be undone? It clutters up the PR.

2024-05-31 15:29 UTC, micpap25 commented on site/app/controllers/admin/UsersController.php
> +        $can_rejoin_in_null = [];
Is "can rejoin in null" a good name? Would "can rejoin" suffice?

2024-05-31 15:29 UTC, micpap25 commented on site/app/controllers/SelfRejoinController.php
>          // If never accessed course but today is within first two weeks of term, can re-add self.
How is "never accessed course" enforced here? If it isn't, this line should be changed to avoid confusion

2024-05-31 19:44 UTC, williamjallen commented
Is this ready for review?  It is currently a draft and there are outstanding review comments to resolve, so I have moved this back to "Work in Process".

2024-06-04 18:26 UTC, micpap25 commented
PR should be merged per @bmcutler, the CI issue is a performance issue from excessive requests since the `canRejoinCourse` function wasn't designed with calling on lots of users at once. Opening a new issue for that.

2024-06-04 19:10 UTC, micpap25 approved these changes

2024-06-06 15:14 UTC, ziesski approved these changes
Didn't test the functionality, but the code looks good. As described in new issue, it does have excessive query, which should be optimized, we could add new column or re-write the query into one giant query.

2024-06-06 15:58 UTC, merged