Warning message for late submissions for team assignments #9549
Submitty/Submitty pull request #9951
Opened 2023-10-31 21:19 UTC by RitaLei123

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

When a instructor gives only one team member a late day extension, and the other team members don't have an extension, all the other team members will get a zero when the team member with the extension submits.

### What is the new behavior?
When the team member with a late day extension submits, they will be notified with a alert box saying like this:
<img width="935" alt="image" src="https://github.com/Submitty/Submitty/assets/117528498/7e544331-a95c-426d-9f3b-32a652b3b1c4">

### Other information?

1. Go to the instructor and create a late gradable.
2. Remove all the late days and extensions that exists for the student.
3. Give one student in a team a late day extension and not the rest of them (this can be done by clicking no when asked should all the team members be given a extension).
4. Go to the student with a late day extension and submit something for that assignment.
5. The alert box should pop up upon submission.

2023-11-02 01:33 UTC, Youssef-Chip approved these changes
The new changes do effectively handle that edge case. The code also looks clean and the logic makes sense.

2023-11-03 13:15 UTC, taorif25 requested changes
I wasn't able to reproduce the bug exactly, but this PR still seems to solve some issues for team extensions. On main, when only one student had an extension, the warning was already showing up for me. However, even when all members of the team had the exception, the warning would still show up. 
Here's a screenshot with both team members having an extension:
![image](https://github.com/Submitty/Submitty/assets/143554378/4280f19d-5a48-4d34-a40d-4e31f7e6e71e)

On this branch, when only one student had an extension, the warning would show up. But when all team members had the extension, the warning would not show up, which is good.
One suggestion would be to use this new logic to get rid of this red warning box if all team member have an extension:
![image](https://github.com/Submitty/Submitty/assets/143554378/da0b654e-e357-48fc-8399-44306175586c)

2023-11-03 14:06 UTC, taorif25 commented
> > I wasn't able to reproduce the bug exactly, but this PR still seems to solve some issues for team extensions. On main, when only one student had an extension, the warning was already showing up for me. However, even when all members of the team had the exception, the warning would still show up. Here's a screenshot with both team members having an extension: ![image](https://user-images.githubusercontent.com/143554378/280288861-4280f19d-5a48-4d34-a40d-4e31f7e6e71e.png)
> > On this branch, when only one student had an extension, the warning would show up. But when all team members had the extension, the warning would not show up, which is good. One suggestion would be to use this new logic to get rid of this red warning box if all team member have an extension: ![image](https://user-images.githubusercontent.com/143554378/280288385-da0b654e-e357-48fc-8399-44306175586c.png)
> 
> This red warning box should appear because in that picture you submitted, the user had already a bad submission. The red box should disappear after you make a valid (late) submission, but it should stay to warn the user that the current version they have is a bad submission.

Ok it turns out there were 2 assignments called closed peer team homework in sample. Red box went away when submitting on the correct assignment!

2023-11-03 14:07 UTC, taorif25 approved these changes

2023-11-07 17:35 UTC, merged