[Bugfix:Forum] Disable scroll and drag on EditThread popup
Submitty/Submitty pull request #9980
Opened 2023-11-10 19:28 UTC by teazhi

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Previously able to drag popup around when editing threads, as well as scroll in the background behind/around the modal.

### What is the new behavior?
Disabled the draggable feature and disabled the page scroll when modal is open.

### Other information?

Testing:
Edit a thread in discussion forum and attempt to drag the popup around and scroll in the area around the popup.

2023-11-14 03:42 UTC, VVVITH commented
could you please attach some pictures and give more detail info about what are you tring to solve? or attach a relate issue? I don't understand your description sorry.

2023-11-14 19:56 UTC, oskurtt commented
Tested branch and everything looks good. One small thing to note, please be consistent with programming convention. For example, when/where to indent, spacing, variable naming and etc.

2023-11-17 20:11 UTC, DarthNyan requested changes
Few code quality things I noticed. Otherwise, it works to disable dragging.

2023-11-21 20:14 UTC, RitaLei123 approved these changes
The three step review process:
Is the proposed change a good idea?
Yes, it is unnecessary for the box to be draggable and the background to be scrollable. When the screen size is smaller, the box is harder to use if it’s been dragged.

Did the author take the right approach?
It appears that the author removed the code that allows the box to be draggable.

Are all the implementation details correct?
Yes, the implementation details are correct.

Manual testing:
Reproduce on main: The box was draggable and the background was scrollable.
Check topic branch
Reproduce on main again: The box is no longer draggable and the background is not scrollable.

A few other things to check:
If a UI change: light/dark modes, different screen sizes: It works for different screen sizes.

2023-11-24 05:42 UTC, RitaLei123 reviewed
Drag and Scroll (For future development, New Feature was not applied to these areas)
- Calendar
- Office Hours Queue --|> Open New Queue
                                   --|> Edit Existing Queue
                                   --|> Edit Announcement
                                   --|> Send Message
- Course Materials --|> All the Blue Buttons
- Manage Student --|> Edit Student
                              --|> All the Blue Buttons
- Manage Graders --|> Edit Grader
                              --|> Demote Grader
                              --|> All the Blue Buttons
- Student Photos --|> Upload Student Photos

2023-12-09 15:12 UTC, williamjallen requested changes

2023-12-09 15:12 UTC, williamjallen commented on site/app/templates/forum/CreatePost.twig
> +                <a class="post_button edit-post-button key_to_click" tabindex = "0" onClick="showEditPostForm({{ post.id }}, {{ post.thread_id }}, {{ post_buttons.edit.shouldEditThread }}, {{ render_
This change is unrelated to the rest of the PR and should be reverted.

2023-12-09 15:12 UTC, williamjallen commented on site/app/templates/generic/Popup.twig
> +        <div class="popup-box" onClick="{{ block('close_click_action') }}">
@DarthNyan is correct here.  This change should be reverted.

2023-12-12 19:56 UTC, VVVITH approved these changes
Work as discribed. I have removed the unrelated code changes. Need more reviews and merge.

2023-12-12 23:23 UTC, DarthNyan approved these changes
Looks good to me. You've made a few whitespace changes that I don't think are necessary, but they also don't hurt readability so I think they're fine to stay.

2023-12-12 23:29 UTC, VVVITH commented
> Looks good to me. You've made a few whitespace changes that I don't think are necessary, but they also don't hurt readability so I think they're fine to stay.

I think the whitespace changes is ok. The changes is going to match the tabs to make it more clear in my view.

2023-12-13 12:39 UTC, cjreed121 approved these changes

2023-12-13 13:35 UTC, merged