[Refactor:Calendar] Luxon Date Objects
Submitty/Submitty pull request #9989
Opened 2023-11-14 21:16 UTC by oskurtt

### Please check if the PR fulfills these requirements:

* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant
* [ ] Screenshots are attached to Github PR if visual/UI changes were made

### What is the current behavior?

Fixes #<9731>
We use the builtin JS date library in a number of places. While this mostly works, we keep getting bit by browser implementation specific stuff and pitfalls because it's not a very developer friendly interface. This is especially a bit hairy as we then do bits of math with these dates, which is equally error prone. Many of the strings passed in do not follow the ISO8601 format and rely on non-standard browser behavior to parse the date.
### What is the new behavior?
Instead of using the builtin JS date library, we will be using Luxon. I have only made this change in latedays.js so the team can review and approve of integrating Luxon for the rest of Submitty.
### Other information?

2023-11-17 16:01 UTC, taorif25 approved these changes
Code changes are straightforward and successfully convert the files to luxon dates. I tested calendar features impacted by this branch and everything seems to be working as expected. Looks good!

2023-11-17 19:21 UTC, DarthNyan approved these changes
Looks good to me.

The only thing I would change, and this is very minor, but in showEditPostForm you could append the ":00" to validIsoString where it's declared so that it is a valid ISO string on its own. That way you wouldn't need to append stuff to it in line 879. But that's just my personal preference.

2023-11-17 21:12 UTC, williamjallen commented
Can you please update the PR title to reflect the fact that you are refactoring a few specific files

2023-12-12 18:52 UTC, bmcutler commented
@oskurtt 
please resolve merge conflicts

2023-12-12 19:25 UTC, DarthNyan requested changes
Calendar and Forum still work, but the changes to drag-and-drop.js don't seem to be related to Luxon.

2023-12-12 19:25 UTC, DarthNyan commented on site/public/js/drag-and-drop.js
Changes in this file should probably be in a separate PR. They don't appear to have much to do with Luxon and I don't know what they're supposed to do.

2024-04-03 03:39 UTC, williamjallen commented
@DarthNyan Would you be interested in taking over this PR?  Most of the content seems to be good, but the changes to the file you commented on contain an XSS vulnerability, and are seemingly irrelevant.  You could probably just revert anything that that is broken/unnecessary, and we could merge whatever is left.

2024-04-26 16:38 UTC, DarthNyan approved these changes

2024-04-27 02:40 UTC, williamjallen approved these changes

2024-04-27 02:41 UTC, cjreed121 approved these changes

2024-04-27 02:57 UTC, merged